SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09ARS_SUKIRO_D_MF IRO衍伸性商品之資料擷取 交易最大日期

-- =============================================
Alter PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKIRO_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		INSERT INTO MONITORDATA_STAGE (
		    BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
		    CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
		    LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE,  FIL9,
		    SOURCE, CREATOR, LIMIT_MATURITY, PRODUCT_CODE,EXT_DATE)
		SELECT
			trim(SUKIRO_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKIRO_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKIRO_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE, -- 衍生性金融商品
			trim(SUKIRO_TRADE_ID) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKIRO_TRADE_DATE AS TX_DATE,
			trim(SUKIRO_CUST_NAME2) AS CUSTOMER_NAME,
			trim(SUKIRO_CUSTOMER_ID) AS CUSTOMER_ID,
			trim(SUKIRO_CPTY_COUNTRY_RISK)	AS COUNTRY_COD,
			'USD'	AS CURENCY_COD,
			SUKIRO_RISK_AMT As TRAN_AMOUNT,
			SUKIRO_RISK_AMT AS LIMIT,
			'USD' AS LIMIT_COD,
			SUKIRO_MATURITY_DATE	AS MATURITY_DATE,
			SUKIRO_EXT_DATE AS AS_OF_DATE,
			'ARS_SUKIRO_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKIRO_MATURITY_DATE AS LIMIT_MATURITY,
			--TRIM(SUKIRO_CPTY_BUSINESS) AS INDUSTRY,
			--1,
			'IRO' AS PRODUCT_CODE,
			@EXT_DATE
		FROM
			ARS_SUKIRO_D_MF
		WHERE
			SUKIRO_EXT_DATE = (select max(SUKIRO_EXT_DATE) from ARS_SUKIRO_D_MF WHERE SUKIRO_EXT_DATE <= @EXT_DATE) AND
			SUKIRO_BUY_SELL ='1' AND
			SUKIRO_CPTY_COUNTRY_RISK <> 'TW' AND
			(SUKIRO_MATURITY_DATE is null or DATEADD(DAY,@BufferDate,SUKIRO_MATURITY_DATE) >= @EXT_DATE)

	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
