SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKNFX 衍生性商品(NDF及保證金交易)之資料擷取 交易最大日期

-- =============================================
Alter PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKNFX_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,CUR_BOUGHT,CUR_SOLD,EXT_DATE)
		SELECT
			TRIM(SUKFX_BRANCH_NO) AS BRANCH_NO,
			CASE
				WHEN SUBSTRING(SUKFX_CUSTOMER_ID, 2, 1) < 'A' AND SUKFX_TX_TYPE IN('02', '03') THEN '077'
				WHEN SUKFX_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKFX_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
				END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE,
			TRIM(SUKFX_TRAN_NO) AS TRAN_NO,
			CASE WHEN SUBSTRING(SUKFX_CUSTOMER_ID, 2, 1) < 'A' AND SUKFX_TX_TYPE IN('02', '03') THEN '018'
				 ELSE '016' END AS BUSINESS_UNIT,
			SUKFX_TX_DATE AS TX_DATE,
			TRIM(SUKFX_CUST_NAME1) AS CUSTOMER_NAME,
			TRIM(SUKFX_CUSTOMER_ID) AS CUSTOMER_ID,
			TRIM(SUKFX_CPTY_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(SUKFX_OBJECT_CCY) AS CURENCY_COD,
			SUKFX_OBJECT_AMT As TRAN_AMOUNT,
			NULL AS PERMIT_NO,
			SUKFX_OBJECT_AMT AS LIMIT,
			TRIM(SUKFX_OBJECT_CCY) AS LIMIT_COD,
			SUKFX_VALUE_DATE0 AS MATURITY_DATE,
			SUKFX_EXT_DATE AS AS_OF_DATE,
			0 AS REVOLVE_MK,
			'ARS_SUKNFX_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKFX_VALUE_DATE0 as LIMIT_MATURITY,
			--TRIM(SUKFX_CPTY_BUSINESS) AS INDUSTRY,
			--1,
			SUKFX_CUR_BOUGHT AS CUR_BOUGHT,
			SUKFX_CUR_SOLD AS CUR_SOLD,
			@EXT_DATE
		FROM ARS_SUKNFX_D_MF
		WHERE SUKFX_EXT_DATE = (select MAX(SUKFX_EXT_DATE) FROM ARS_SUKNFX_D_MF WHERE SUKFX_EXT_DATE < @EXT_DATE) AND
			  (SUKFX_VALUE_DATE0 is null or DATEADD(DAY,@BufferDate,SUKFX_VALUE_DATE0) >= @EXT_DATE) AND
			  SUKFX_TX_TYPE IN('02', '03', '04', '05') AND
			  SUKFX_CPTY_COUNTRY_RISK <> 'TW';
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
