SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	06外貸系統(外幣貸款系統) 交易最大日期

-- =============================================
CREATE PROCEDURE [dbo].[usp_Souce06_By_FL_FLMST_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

	DECLARE @BufferDate INT = 14; -- 到期日緩衝時間
		DECLARE @MaxExtDate DATE = (SELECT MAX(FLMST_EXT_DATE) FROM FL_FLMST_D_MF WHERE FLMST_EXT_DATE <= @EXT_DATE);

		-- 原本用 CTE 寫法，但下方 INSERT 對 TEMP 有 3 處引用；SQL Server 的 CTE 不會被物化，
		-- 每引用一次就會把下面的 JOIN 全部重新展開執行一次，等於同樣的工作跑 3 遍。
		-- 改用 #TEMP 實體化一次，並把 MAX(FLMST_EXT_DATE) 移出、只計算一次。
		SELECT
			   FLMST_RECV_BRANCH, FLMST_LC_NO, FLMST_NEGO_DATE, FLMST_CUST_ID,
			   FLMST_ADVANCE_BALANCE, FLMST_APRV_NO_1, FLMST_MATURITY, FLMST_EXT_DATE,
			   FLMST_LOAN_TYPE,
			   right(mf.BUSINS_CODE,6) INDUSTRY,
			   CIF.CIF_CUST_NAME,CR.CountryCode2,
			   LINE.FMLINE_LINE_AMT,LINE.FMLINE_REVOLING_TYPE,
			   LINE.FMLINE_LINE_EXPIRY,
			   LINE.FMLINE_MULT_MERGED_MARK,
			   LINE.FMLINE_MULT_MERGED_APRV_NO,
			   CUR.CRCY_ENG_NAME AS CURNAME,
			   CUR1.CRCY_ENG_NAME AS CURNAME1
		INTO #TEMP
		FROM FL_FLMST_D_MF MF
		LEFT JOIN DAILY_CIF_TMP CIF ON FLMST_CUST_ID = CIF.CIF_ID_NO
		LEFT JOIN FM_FMLINE_D_MF LINE ON
			LINE.FMLINE_EXT_DATE = FLMST_EXT_DATE AND
			LINE.FMLINE_DATE_TYPE = '10' AND
			FLMST_APRV_TYPE_1 = LINE.FMLINE_LINE_TYPE AND
			FLMST_CUST_ID = LINE.FMLINE_CUST_ID AND
			FLMST_RECV_BRANCH = LINE.FMLINE_BRANCH AND
			FLMST_APRV_NO_1 = LINE.FMLINE_APRV_NO
		LEFT JOIN CountryMaster CR on TRIM(FLMST_FINAL_RISK_CNTY) = CR.CountryCode4
		INNER JOIN MIS_CRCY_REF CUR ON TRIM(FLMST_CURENCY) = TRIM(CUR.CRCY_CODE)
		INNER JOIN MIS_CRCY_REF CUR1 ON TRIM(FLMST_APRV_CUR_1) = TRIM(CUR1.CRCY_CODE)
		WHERE FLMST_EXT_DATE = @MaxExtDate AND
			  TRIM(FLMST_FINAL_RISK_CNTY) NOT IN('0000','1001') AND
			  TRIM(FLMST_DATA_TYPE) = '0' AND　-- 待確認
			  NOT(FLMST_LOAN_TYPE = '10' AND ISNULL(FLMST_SUBSTITUTE_REMIT_MK, '') = 'Y') AND --註記邏輯可能要調整
			  TRIM(FLMST_DATA_STATUS) in ('0', '2', '4') AND -- 2是催收資料 -- 0 一般資料
			  (FLMST_MATURITY IS NULL OR DATEADD(DAY,@BufferDate,FLMST_MATURITY) >= @EXT_DATE);

		-- FMLINE 未來 會添加一個風險國欄位
		-- ELLSTAPV 用分行加核准編號 去串 抓國家
		-- FLMST 原本風險國欄位

		INSERT INTO MonitorData (
		    BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
		    CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
		    PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,INDUSTRY,INDUSTRY_Type,EXT_DATE)
		SELECT
			TRIM(FLMST_RECV_BRANCH) as BRANCH_NO,
			'064' as DIVISION_NO,
			'02' as PRODUCT_TYPE,
			TRIM(FLMST_LC_NO) as TRAN_NO,
			'011' as BUSINESS_UNIT,
			FLMST_NEGO_DATE as TX_DATE,
			TRIM(CIF_CUST_NAME) as CUSTOMER_NAME,
			TRIM(FLMST_CUST_ID) as CUSTOMER_ID,
			CountryCode2 as COUNTRY_COD,
			TRIM(CURNAME) as CURENCY_COD,
			FLMST_ADVANCE_BALANCE as TRAN_AMOUNT,
			TRIM(FLMST_APRV_NO_1) as PERMIT_NO,
			FMLINE_LINE_AMT as [LIMIT],
			TRIM(CURNAME1) as LIMIT_COD,
			FLMST_MATURITY as MATURITY_DATE,
			FLMST_EXT_DATE as AS_OF_DATE,
			CASE FMLINE_REVOLING_TYPE WHEN '1' THEN 1
				 ELSE 0
				 END as REVOLVE_MK,
			'FL_FLMST_D_MF1' as FIL9,
			'06' as source,
			'system' as creator,
			FMLINE_LINE_EXPIRY as LIMIT_MATURITY,
			INDUSTRY as INDUSTRY,
			1,
			@EXT_DATE AS EXT_DATE
		FROM #TEMP
		WHERE TRIM(FLMST_LOAN_TYPE) IN ('24','26')
		UNION ALL
		SELECT
			TRIM(FLMST_RECV_BRANCH) as BRANCH_NO,
			'067' as DIVISION_NO,
			'02' as PRODUCT_TYPE,
			TRIM(FLMST_LC_NO) as TRAN_NO,
			'013' as BUSINESS_UNIT,
			FLMST_NEGO_DATE as TX_DATE,
			TRIM(CIF_CUST_NAME) as CUSTOMER_NAME,
			TRIM(FLMST_CUST_ID) as CUSTOMER_ID,
			CountryCode2 as COUNTRY_COD,
			TRIM(CURNAME) as CURENCY_COD,
			FLMST_ADVANCE_BALANCE as TRAN_AMOUNT,
			TRIM(FLMST_APRV_NO_1) as PERMIT_NO,
			FMLINE_LINE_AMT as [LIMIT],
			TRIM(CURNAME1) as LIMIT_COD,
			FLMST_MATURITY as MATURITY_DATE,
			FLMST_EXT_DATE as AS_OF_DATE,
			CASE FMLINE_REVOLING_TYPE WHEN '1' THEN 1
				 ELSE 0
				 END as REVOLVE_MK,
			'FL_FLMST_D_MF2' as FIL9,
			'06' as source,
			'system' as creator,
			FMLINE_LINE_EXPIRY as LIMIT_MATURITY,
			INDUSTRY as INDUSTRY,
			1,
			@EXT_DATE AS DATADATE
		FROM #TEMP
		WHERE TRIM(FLMST_LOAN_TYPE) IN ('25','27','28','29')
		UNION ALL
		SELECT
			TRIM(FLMST_RECV_BRANCH) as BRANCH_NO,
			CASE TRIM(FLMST_RECV_BRANCH)
				WHEN '091' THEN '091'
				WHEN '095' THEN '077'
			ELSE '064'
			END as DIVISION_NO,
			CASE WHEN FLMST_LOAN_TYPE IN ('01','02','03','04','05','06','07','08','11','12','13')
					THEN '02'
				WHEN FLMST_LOAN_TYPE = '09'
					THEN '01'
				WHEN FLMST_LOAN_TYPE = '10'
					THEN '12'
				ELSE '02'
			END as PRODUCT_TYPE,
			TRIM(FLMST_LC_NO) as TRAN_NO,
			CASE WHEN TRIM(FLMST_RECV_BRANCH) IN ('091','095')
				THEN '018'
			ELSE '011'
			END as BUSINESS_UNIT,
			FLMST_NEGO_DATE as TX_DATE,
			TRIM(CIF_CUST_NAME) as CUSTOMER_NAME,
			TRIM(FLMST_CUST_ID) as CUSTOMER_ID,
			CountryCode2 as COUNTRY_COD,
			TRIM(CURNAME) as CURENCY_COD,
			--CASE WHEN FLMST_LOAN_TYPE = '10'
			--	THEN FLMST_ADVANCE_BALANCE + FLMST_DISCOUNT_INT
			--	ELSE FLMST_ADVANCE_BALANCE END as TRAN_AMOUNT,
			FLMST_ADVANCE_BALANCE as TRAN_AMOUNT, -- 未來換上面那個
			TRIM(FLMST_APRV_NO_1) as PERMIT_NO,
			FMLINE_LINE_AMT as [LIMIT],
			TRIM(CURNAME1) as LIMIT_COD,
			FLMST_MATURITY as MATURITY_DATE, -- 改成close_date
			FLMST_EXT_DATE as AS_OF_DATE,
			CASE FMLINE_REVOLING_TYPE WHEN '1' THEN 1
				 ELSE 0
				 END as REVOLVE_MK,
			'FL_FLMST_D_MF3' as FIL9,
			'06' as source,
			'system' as creator,
			FMLINE_LINE_EXPIRY as LIMIT_MATURITY,
			INDUSTRY as INDUSTRY,
			1,
			@EXT_DATE AS DATADATE
		FROM #TEMP
		WHERE TRIM(FLMST_LOAN_TYPE) NOT IN ('24','25','26','27')
		UNION ALL
		SELECT  -- 額度檔
			TRIM(LINE.FMLINE_BRANCH) as BRANCH_NO,
			CASE TRIM(FLMST_RECV_BRANCH)
				WHEN '091' THEN '091'
				WHEN '095' THEN '077'
			ELSE '064'
			END as DIVISION_NO,
			'' as PRODUCT_TYPE, ---目前沒辦法分產品別
			'' as TRAN_NO,
			CASE WHEN TRIM(FLMST_RECV_BRANCH) IN ('091','095')
				THEN '018'
			ELSE '011'
			END as BUSINESS_UNIT,
			LINE.FMLINE_APRV_DATE as TX_DATE,
			TRIM(CIF_CUST_NAME) as CUSTOMER_NAME,
			TRIM(FMLINE_CUST_ID) as CUSTOMER_ID,
			 --ISNULL(LINE.FMLINE_FINAL_RISK_CNTY,ELL.RISK_NACTION_ID) as COUNTRY_COD,
			LINE.BUSINS_CODE as COUNTRY_COD, -- 要跟其他TABLE 拿，等資訊步道給我 -- LINE.FMLINE_FINAL_RISK_CNTY
			'' as CURENCY_COD,
			'' as TRAN_AMOUNT,
			LINE.FMLINE_APRV_NO as PERMIT_NO,
			LINE.FMLINE_LINE_AMT as [LIMIT],
			LINE.FMLINE_LINE_CURENCY as LIMIT_COD,
			LINE.FMLINE_LINE_EXPIRY as MATURITY_DATE,
			LINE.FMLINE_EXT_DATE as AS_OF_DATE, -- 不確定
			CASE LINE.FMLINE_REVOLING_TYPE WHEN '1' THEN 1
				 ELSE 0
				 END as REVOLVE_MK,
			'FM_FMLINE_D_MF' as FIL9,
			'06' as source,
			'system' as creator,
			FMLINE_LINE_EXPIRY as LIMIT_MATURITY,
			'' as INDUSTRY, -- 待確認
			1,
			@EXT_DATE AS DATADATE
		FROM FM_FMLINE_D_MF LINE
		--LEFT JOIN ELLSTAPV ELL ON LINE.FMLINE_CUST_ID = ELL.ELLSTAPV_CUST_ID AND LINE.FMLINE_APRV_NO = ELLSTAPV_APRV_NO  -- 未來要串這個去看國別
		-- 未來FM_FMLINE_D_MF 會有多一個欄位是 FMLINE_OBBS_APRV_NO 海外核准號碼，是為了RISKLINEO 匯入是對應 APROVE_NO，如果有就不用匯入RISKLINEO
		-- RISKLINED 核准編號對應 FMLINE_APRV_NO，如果有就排除RISKLINED
		LEFT JOIN FL_FLMST_D_MF FLMST ON
			LINE.FMLINE_EXT_DATE = FLMST_EXT_DATE AND
			LINE.FMLINE_DATE_TYPE = '10' AND
			FLMST_APRV_TYPE_1 = LINE.FMLINE_LINE_TYPE AND
			FLMST_CUST_ID = LINE.FMLINE_CUST_ID AND
			FLMST_RECV_BRANCH = LINE.FMLINE_BRANCH AND
			FLMST_APRV_NO_1 = LINE.FMLINE_APRV_NO
		LEFT JOIN DAILY_CIF_TMP CIF ON LINE.FMLINE_CUST_ID = CIF.CIF_ID_NO
		WHERE FLMST.FLMST_ACNT_BRANCH IS NULL

	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
