SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	04存放銀行同業 交易最大日期

-- =============================================
Alter PROCEDURE [dbo].[usp_Souce04_By_LS_LSRSA_D_MF_ACNOD_STG] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		
		INSERT INTO MonitorData (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY, EXT_DATE)
		SELECT
			'D01' AS BRANCH_NO,
			'091' AS DIVISION_NO,
			'04' AS PRODUCT_TYPE,
			TRIM(APRV_NO) AS TRAN_NO,
			'018' AS BUSINESS_UNIT,
			EXT_DATE AS TX_DATE,
			TRIM(ENG_NAME) AS CUSTOMER_NAME,
			TRIM(ISIN_CD) AS CUSTOMER_ID,
			TRIM(COUNTRY) AS COUNTRY_COD,
			TRIM(CURRENCY) AS CURENCY_COD,
			LN_BAL AS TRAN_AMOUNT,
			NULL AS PERMIT_NO,
			LN_BAL AS LIMIT,
			TRIM(CURRENCY) AS LIMIT_COD,
			DATEADD(month, 1, GETDATE()) AS MATURITY_DATE,
			EXT_DATE AS AS_OF_DATE,
			'LS_LSRSA_D_MF' AS FIL9,
			'04' AS source,
			'system' AS creator,
			DATEFROMPARTS(YEAR(GETDATE()), 12, 31) AS LIMIT_MATURITY,
			--right(BUSINS_CODE,6) AS INDUSTRY,
			--1,
			@EXT_DATE AS EXT_DATE
		FROM LS_LSRSA_D_MF
		WHERE (SELECT MAX(EXT_DATE) FROM LS_LSRSA_D_MF WHERE EXT_DATE <= @EXT_DATE) = EXT_DATE AND
			LEFT(ACC_CODE, 5) = '11021' AND
			TRIM(COUNTRY) <> 'TW' AND
			LEFT(TRIM(ISIN_CD), 4) <> 'FCBK' 
		UNION ALL
		SELECT
			'098' AS BRANCH_NO,
			'069' AS DIVISION_NO,
			'04' AS PRODUCT_TYPE,
			NULL AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			ACNOD_EXT_DATE AS TX_DATE,
			'HSBC (GLOBAL CUSTODY CASH)' AS CUSTOMER_NAME,
			'HSBCHKHHGCC' AS CUSTOMER_ID,
			'GB' AS COUNTRY_COD,
			TRIM(ACNOD_CRCY_CODE) AS CURENCY_COD,
			ACNOD_OPER_DATE_BAL_INF AS TRAN_AMOUNT,
			NULL AS PERMIT_NO,
			ACNOD_OPER_DATE_BAL_INF AS LIMIT,
			TRIM(ACNOD_CRCY_CODE) AS LIMIT_COD,
			DATEFROMPARTS(YEAR(GETDATE()), 12, 31) AS MATURITY_DATE,
			ACNOD_EXT_DATE AS AS_OF_DATE,
			'ACNOD_STG' AS FIL9,
			'04' AS source,
			'system' AS creator,
			DATEFROMPARTS(YEAR(GETDATE()), 12, 31) AS LIMIT_MATURITY,
			--null AS INDUSTRY,
			--null,
			@EXT_DATE AS DATADATE
		FROM ACNOD_STG
		WHERE ACNOD_BRANCH_CODE = '092' AND
	　		 ACNOD_ACC5_CODE = '11134' AND
			ACNOD_ACC5_SUB_CODE = '001' AND
			ACNOD_LAST_BAL_MARK = 'Y' AND
			(SELECT MAX(ACNOD_EXT_DATE) FROM ACNOD_STG WHERE ACNOD_EXT_DATE <= @EXT_DATE) = ACNOD_EXT_DATE;

	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
