SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKNMM 拆款業務之資料擷取 交易最大日期

-- =============================================
CREATE PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKNMM_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		INSERT INTO MonitorData (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY, INDUSTRY,INDUSTRY_Type,EXT_DATE)
		SELECT
			TRIM(SUKMM_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKMM_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKMM_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			CASE TRIM(SUKMM_TRN_TYPE) WHEN '1' THEN '09'   -- 「09拆款」
									  WHEN '3' THEN '04'   -- 「04存同」
				 END AS PRODUCT_TYPE,
			TRIM(SUKMM_TRAN_NO) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKMM_TX_DATE AS TX_DATE,
			TRIM(SUKMM_CUST_NAME1) AS CUSTOMER_NAME,
			TRIM(SUKMM_SWIFT_ID) AS CUSTOMER_ID,
			TRIM(SUKMM_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(SUKMM_CURENCY_COD) AS CURENCY_COD,
			ABS(SUKMM_TRAN_AMOUNT) AS TRAN_AMOUNT,
			NULL AS PERMIT_NO,
			ABS(SUKMM_TRAN_AMOUNT) AS [LIMIT],
			TRIM(SUKMM_CURENCY_COD) AS LIMIT_COD,
			SUKMM_MATURITY_DATE AS MATURITY_DATE,
			SUKMM_EXT_DATE AS AS_OF_DATE,
			1 AS REVOLVE_MK,
			'ARS_SUKNMM_D_MF' AS FIL9,
			'09' AS source,
			'system' AS creator,
			SUKMM_MATURITY_DATE AS LIMIT_MATURITY,
			TRIM(SUKMM_CPTY_TYPE) AS INDUSTRY,
			1,
			@EXT_DATE AS EXT_DATE
		FROM ARS_SUKNMM_D_MF
		WHERE
			SUKMM_EXT_DATE = (select max(SUKMM_EXT_DATE) from ARS_SUKNMM_D_MF WHERE SUKMM_EXT_DATE < @EXT_DATE) AND
			(SUKMM_MATURITY_DATE IS NULL OR SUKMM_MATURITY_DATE > SUKMM_EXT_DATE) AND -- 並去除當日到期之資料
			TRIM(SUKMM_TRN_TYPE) IN ('1','3') AND -- 只抓取正的
			SUKMM_COUNTRY_RISK <> 'TW' AND
			--(
			--	-- 條件1：非 group_id = '99999' 的客戶
			--	(TRIM(SUKMM_CUST_NAME1) NOT IN (SELECT customer_name FROM groupdata WHERE group_id = '99999'))
			--	OR
			--	-- 條件2：group_id = '99999' 的客戶，但排除 TWD 幣別
			--	(TRIM(SUKMM_CUST_NAME1) IN (SELECT customer_name FROM groupdata WHERE group_id = '99999')
			--	 AND SUKMM_CURENCY_COD <> 'TWD')
			--) AND
			EXISTS (
				SELECT 1
				FROM ARS_SUKNMM_D_MF MF2
				WHERE	MF2.SUKMM_TRN_TYPE = ARS_SUKNMM_D_MF.SUKMM_TRN_TYPE AND -- 只抓取正的
						MF2.SUKMM_COUNTRY_RISK = ARS_SUKNMM_D_MF.SUKMM_COUNTRY_RISK AND
						MF2.SUKMM_EXT_DATE = ARS_SUKNMM_D_MF.SUKMM_EXT_DATE AND
						MF2.SUKMM_MATURITY_DATE = ARS_SUKNMM_D_MF.SUKMM_MATURITY_DATE AND
						LEFT(MF2.SUKMM_SWIFT_ID, 4) = LEFT(SUKMM_SWIFT_ID, 4)
				GROUP BY LEFT(MF2.SUKMM_SWIFT_ID, 4)
				HAVING SUM(ABS(MF2.SUKMM_TRAN_AMOUNT)) > 0)
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
