SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKSWP 之資料擷取 交易最大日期

-- =============================================
Alter PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKSWP_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MonitorData (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,PRODUCT_CODE,EXT_DATE)
		SELECT
			TRIM(SUKSWP_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKSWP_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKSWP_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE,
			TRIM(SUKSWP_EXTERNAL_ID) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKSWP_TX_DATE AS TX_DATE,
			TRIM(SUKSWP_CUST_NAME) AS CUSTOMER_NAME,
			TRIM(SUKSWP_CUSTOMER_ID) AS CUSTOMER_ID,
			TRIM(SUKSWP_CPTY_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(SUKSWP_CURRENCY) AS CURENCY_COD,
			SUKSWP_RISK_AMT As TRAN_AMOUNT,
			SUKSWP_RISK_AMT AS LIMIT,
			TRIM(SUKSWP_CURRENCY) AS LIMIT_COD,
			SUKSWP_OPTIONEXPIRYDATE AS MATURITY_DATE,
			SUKSWP_EXT_DATE AS AS_OF_DATE,
			'ARS_SUKSWP_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKSWP_OPTIONEXPIRYDATE as LIMIT_MATURITY,
			--TRIM(SUKSWP_CPTY_BUSINESS) AS INDUSTRY,
			--1,
			'IRO' AS PRODUCT_CODE,
			@EXT_DATE AS EXT_DATE
		FROM ARS_SUKSWP_D_MF
		WHERE SUKSWP_EXT_DATE = (select max(SUKSWP_EXT_DATE) from ARS_SUKSWP_D_MF WHERE SUKSWP_EXT_DATE <= @EXT_DATE) AND
			(SUKSWP_OPTIONEXPIRYDATE is null or DATEADD(DAY,@BufferDate,SUKSWP_OPTIONEXPIRYDATE) >= @EXT_DATE) AND
			SUKSWP_BUY_SELL ='B' AND
			SUKSWP_CPTY_COUNTRY_RISK <> 'TW';
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
