SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKBDO衍伸性商品之資料擷取 交易最大日期

-- =============================================
Alter PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKBDO_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE,  FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY, PRODUCT_CODE,EXT_DATE)
		SELECT
			trim(SUKBDO_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKBDO_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKBDO_DESK)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE, -- 衍生性金融商品
			trim(SUKBDO_POSITIONID) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKBDO_TX_DATE	AS TX_DATE,
			trim(SUKBDO_CUST_NAME) AS CUSTOMER_NAME,
			trim(SUKBDO_CUSTOMER_ID) AS CUSTOMER_ID,
			trim(SUKBDO_CPTY_COUNTRY_RISK) AS COUNTRY_COD,
			'USD' AS CURENCY_COD,
			SUKBDO_RISK_AMT As TRAN_AMOUNT,
			SUKBDO_RISK_AMT AS LIMIT,
			'USD' AS LIMIT_COD,
			SUKBDO_OPTIONEXPIRYDATE	AS MATURITY_DATE,
			SUKBDO_EXT_DATE AS AS_OF_DATE,
			'ARS_SUKBDO_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKBDO_OPTIONEXPIRYDATE as LIMIT_MATURITY,
			--TRIM(BUSINS_CODE) AS INDUSTRY,
			--1,
			'BO' AS PRODUCT_CODE,
			@EXT_DATE AS EXT_DATE
		FROM ARS_SUKBDO_D_MF
		WHERE
			(SUKBDO_OPTIONEXPIRYDATE is null or DATEADD(DAY,@BufferDate,SUKBDO_OPTIONEXPIRYDATE) >= @EXT_DATE) and
			SUKBDO_EXT_DATE = (select max(SUKBDO_EXT_DATE)from ARS_SUKBDO_D_MF WHERE SUKBDO_EXT_DATE <= @EXT_DATE) AND
			SUKBDO_BUY_SELL ='1' AND
			SUKBDO_CPTY_COUNTRY_RISK <> 'TW'


	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
