SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	01OBBS海外債券(OSBDKF02_MF) 轉檔，根據分行交易最大日期

-- =============================================
Alter PROCEDURE [dbo].[usp_Souce01_OBBS_By_OSBDKF02_MF] @EXT_DATE AS DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

	--Declare @EXT_DATE Date = '2026-09-01';
	Declare @BufferDate INT = 14;
	IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL
			DROP TABLE #TEMP;
	SELECT *
	INTO #TEMP
	FROM OSBDKF02_MF a
	WHERE TRIM(OSBDKF02_ISSUER_COUNTRY) <> 'TW' AND
		-- 檢查是否為最新資料
		EXISTS (
			SELECT 1
			FROM (
				SELECT OSBDKF02_BRANCH_NO, MAX(OSBDKF02_EXT_DATE) AS MAX_DATE
				FROM OSBDKF02_MF
				WHERE OSBDKF02_EXT_DATE <= @EXT_DATE
				GROUP BY OSBDKF02_BRANCH_NO
			) Latest
			WHERE
				a.OSBDKF02_BRANCH_NO = Latest.OSBDKF02_BRANCH_NO AND
				a.OSBDKF02_EXT_DATE = Latest.MAX_DATE
		) AND
		LEFT(OSBDKF02_AC_9, 5) not in ('22501','13007') AND --文件編號：D211150
		(OSBDKF02_MATURITY_DATE IS NULL OR DATEADD(DAY,@BufferDate,OSBDKF02_MATURITY_DATE) >= @EXT_DATE)

	INSERT INTO MonitorData (
	    BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
	    CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
	    PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE,  FIL9,
	    SOURCE, CREATOR, LIMIT_MATURITY,EXT_DATE)
	SELECT
		TRIM(OSBDKF02_BRANCH_NO) AS BRANCH_NO,
		'077' AS DIVISION_NO,
		'08' AS PRODUCT_TYPE,  -- 08 有價証券投資
		TRIM(OSBDKF02_TRAN_NO) AS TRAN_NO, --交易編號
		'018' AS BUSINESS_UNIT,
		OSBDKF02_DOWN_DATE AS TX_DATE, --訂約日期
		TRIM(OSBDKF02_CUST_NAME1) AS CUSTOMER_NAME,
		TRIM(OSBDKF02_SWIFT_ID) AS CUSTOMER_ID,
		TRIM(OSBDKF02_ISSUER_COUNTRY) AS COUNTRY_COD,
		TRIM(OSBDKF02_CURENCY_COD) AS CURENCY_COD,
		(OSBDKF02_BALANCE_AMT / OSBDKF02_PRICE) *100 AS TRAN_AMOUNT, -- 改抓OSBDKF02_BALANCE_AMT
		TRIM(OSBDKF02_LINE_PERMIT_NO) + OSBDKF02_BRANCH_NO AS PERMIT_NO, --核准編號
		(OSBDKF02_BALANCE_AMT / OSBDKF02_PRICE) *100 AS LIMIT, --核准額度 -- 改抓OSBDKF02_BALANCE_AMT
		TRIM(OSBDKF02_CURENCY_COD) AS LIMIT_COD, --幣別
		OSBDKF02_MATURITY_DATE AS MATURITY_DATE,
		OSBDKF02_TX_DATE AS AS_OF_DATE,
		'OSBDKF02_MF' AS FIL9,
		'01' AS SOURCE,
		'system' AS CREATOR,
		OSBDKF02_MATURITY_DATE AS LIMIT_MATURITY,
		--TRIM(BUSINS_CODE) AS INDUSTRY,
		--2,
		@EXT_DATE AS EXT_DATE


	FROM #TEMP
	--國家風險餘額計算步驟：
	--	一、	依「CUST-NAME1」加總「BOND PRICE」之折美金值加總之金額如小於0，則不計入。
	--	三、	將各「CUST-NAME1」之加總「BOND PRICE」折美金值，依國碼別加總  ???
	WHERE EXISTS (
			SELECT 1
			FROM #TEMP MF2
			WHERE TRIM(MF2.OSBDKF02_CUST_NAME1) = TRIM(#TEMP.OSBDKF02_CUST_NAME1) AND
			MF2.OSBDKF02_BRANCH_NO = #TEMP.OSBDKF02_BRANCH_NO
			GROUP BY TRIM(MF2.OSBDKF02_CUST_NAME1), MF2.OSBDKF02_BRANCH_NO
			HAVING SUM(MF2.OSBDKF02_BOND_PRICE) > 0
		);
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
