SET NOCOUNT ON;
SET XACT_ABORT ON;

-- DataMigrationByDwService.MigrateAllAsync 每日對這兩張表分別執行
--   ExecuteDeleteAsync()  WHERE LNSLNKD_EXT_DATE = @date   （OS_LNSLNKD_D_MF）
--   ExecuteDeleteAsync()  WHERE LNSSECD_EXT_DATE = @date   （OS_LNSSECD_D_MF）
-- 再整批 BulkInsertAsync 寫回。這兩張表目前完全沒有索引（heap table），且不像
-- OSBDKF02_MF/OSFXKF02_MF/OSISKF02_MF/OSMMKF02_MF/OS_LNSMSTD_D_MF/OS_LNSLMSD_D_MF
-- 那樣被任何 usp_Souce01_OBBS_By_* SP 用到，所以 2026090101 那批補索引完全沒涵蓋到，
-- 每天的 ExecuteDeleteAsync 都要全表掃描，跟 DAILY_CIF_TMP 是同一種風險。這裡補上
-- 各自 EXT_DATE 欄位的索引。

IF OBJECT_ID(N'[dbo].[OS_LNSLNKD_D_MF]', N'U') IS NULL
    THROW 59412, N'缺少資料表 dbo.OS_LNSLNKD_D_MF。', 1;
IF OBJECT_ID(N'[dbo].[OS_LNSSECD_D_MF]', N'U') IS NULL
    THROW 59413, N'缺少資料表 dbo.OS_LNSSECD_D_MF。', 1;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[OS_LNSLNKD_D_MF]') AND [name] = N'IX_OS_LNSLNKD_D_MF_ExtDate')
    THROW 59414, N'dbo.OS_LNSLNKD_D_MF 已存在索引 IX_OS_LNSLNKD_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[OS_LNSSECD_D_MF]') AND [name] = N'IX_OS_LNSSECD_D_MF_ExtDate')
    THROW 59415, N'dbo.OS_LNSSECD_D_MF 已存在索引 IX_OS_LNSSECD_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;

BEGIN TRY
    BEGIN TRANSACTION;

    CREATE NONCLUSTERED INDEX [IX_OS_LNSLNKD_D_MF_ExtDate] ON [dbo].[OS_LNSLNKD_D_MF]
    (
        [LNSLNKD_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_OS_LNSSECD_D_MF_ExtDate] ON [dbo].[OS_LNSSECD_D_MF]
    (
        [LNSSECD_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
