-- =============================================================
-- 2026091602 MonitorData 轉檔改為暫存表 + 短交易換入（方案 C）＋ DW 轉檔補 ARS_SUKBD2_D_MF
-- 依序執行：01 建立 MONITORDATA_STAGE、ARS_SUKBD2_D_MF → 02 SP 改寫（27 支）+ usp_TransferData + usp_MonitorData_Publish → 03 移除 2 支未使用的舊 SP
-- 本檔可重複執行（IF NOT EXISTS / CREATE OR ALTER / DROP IF EXISTS）
-- =============================================================
-- ---------- 01_Table/ARS_SUKBD2_D_MF.sql ----------
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
-- =============================================
-- ARS_SUKBD2_D_MF：DW（DTARS.ARS_SUKBD2_D_MF）附買回／附賣回交易檔在 SQL Server 的落地表
--   由 TransferDataAPI DataMigrationByDwService 每日以 EXT_DATE 刪除後 BulkInsert，
--   再由 usp_Souce09_By_ARS_SUKBD2_D_MF 轉進 MONITORDATA_STAGE。
--   只保留 Entity（FirstBank_Entity/DWEntity/ARS_SUKBD2_D_MF.cs）用到的欄位。
--   SUKBD2_TRADE_DAY／SUKBD2_END_DATE 在 Oracle 是 CHAR(8) yyyyMMdd，轉入時已解析成 date。
--
--   正式機此表先前為手動建立、欄位不明，本腳本採「不存在就建；存在則逐欄補齊缺少的欄位」，
--   可重複執行。既有欄位若型別不同不會自動改，請以 SqlServerSchemaValidation 結果人工處理。
-- =============================================
IF OBJECT_ID(N'[dbo].[ARS_SUKBD2_D_MF]', N'U') IS NULL
BEGIN
	DECLARE @FilegroupSql NVARCHAR(MAX) = N'';
	SET @FilegroupSql += N'CREATE TABLE [dbo].[ARS_SUKBD2_D_MF](
	[SUKBD2_BRANCH_NO] [nvarchar](3) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[SUKBD2_TRADE_NO] [nvarchar](20) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[SUKBD2_TRADE_TYPE] [nvarchar](2) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[SUKBD2_TRADE_DAY] [date] NULL,
	[SUKBD2_END_DATE] [date] NULL,
	[SUKBD2_REPO_CCY] [nvarchar](3) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[SUKBD2_REPO_AMOUNT] [decimal](17, 2) NULL,
	[SUKBD2_ISSUER_ID] [nvarchar](40) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[SUKBD2_ISSUER_APPID] [nvarchar](11) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[SUKBD2_ISSUER_COUNTRY] [nvarchar](2) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[SUKBD2_EXT_DATE] [date] NULL,
	[Create_date] [datetime] NOT NULL CONSTRAINT [DF_ARS_SUKBD2_D_MF_Create_date] DEFAULT (getdate()),
	[Create_user] [nvarchar](20) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL CONSTRAINT [DF_ARS_SUKBD2_D_MF_Create_user] DEFAULT (''system'')
) ON [NCRMS_TAB]';
	IF FILEGROUP_ID(N'NCRMS_TAB') IS NULL
		SET @FilegroupSql = REPLACE(@FilegroupSql, N'[NCRMS_TAB]', N'[PRIMARY]');
	EXEC sys.sp_executesql @FilegroupSql;
END
GO

-- 既有表逐欄補齊（正式機手動建立的版本可能缺欄位）
IF COL_LENGTH(N'dbo.ARS_SUKBD2_D_MF', N'SUKBD2_BRANCH_NO') IS NULL
	ALTER TABLE [dbo].[ARS_SUKBD2_D_MF] ADD [SUKBD2_BRANCH_NO] [nvarchar](3) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL;
IF COL_LENGTH(N'dbo.ARS_SUKBD2_D_MF', N'SUKBD2_TRADE_NO') IS NULL
	ALTER TABLE [dbo].[ARS_SUKBD2_D_MF] ADD [SUKBD2_TRADE_NO] [nvarchar](20) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL;
IF COL_LENGTH(N'dbo.ARS_SUKBD2_D_MF', N'SUKBD2_TRADE_TYPE') IS NULL
	ALTER TABLE [dbo].[ARS_SUKBD2_D_MF] ADD [SUKBD2_TRADE_TYPE] [nvarchar](2) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL;
IF COL_LENGTH(N'dbo.ARS_SUKBD2_D_MF', N'SUKBD2_TRADE_DAY') IS NULL
	ALTER TABLE [dbo].[ARS_SUKBD2_D_MF] ADD [SUKBD2_TRADE_DAY] [date] NULL;
IF COL_LENGTH(N'dbo.ARS_SUKBD2_D_MF', N'SUKBD2_END_DATE') IS NULL
	ALTER TABLE [dbo].[ARS_SUKBD2_D_MF] ADD [SUKBD2_END_DATE] [date] NULL;
IF COL_LENGTH(N'dbo.ARS_SUKBD2_D_MF', N'SUKBD2_REPO_CCY') IS NULL
	ALTER TABLE [dbo].[ARS_SUKBD2_D_MF] ADD [SUKBD2_REPO_CCY] [nvarchar](3) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL;
IF COL_LENGTH(N'dbo.ARS_SUKBD2_D_MF', N'SUKBD2_REPO_AMOUNT') IS NULL
	ALTER TABLE [dbo].[ARS_SUKBD2_D_MF] ADD [SUKBD2_REPO_AMOUNT] [decimal](17, 2) NULL;
IF COL_LENGTH(N'dbo.ARS_SUKBD2_D_MF', N'SUKBD2_ISSUER_ID') IS NULL
	ALTER TABLE [dbo].[ARS_SUKBD2_D_MF] ADD [SUKBD2_ISSUER_ID] [nvarchar](40) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL;
IF COL_LENGTH(N'dbo.ARS_SUKBD2_D_MF', N'SUKBD2_ISSUER_APPID') IS NULL
	ALTER TABLE [dbo].[ARS_SUKBD2_D_MF] ADD [SUKBD2_ISSUER_APPID] [nvarchar](11) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL;
IF COL_LENGTH(N'dbo.ARS_SUKBD2_D_MF', N'SUKBD2_ISSUER_COUNTRY') IS NULL
	ALTER TABLE [dbo].[ARS_SUKBD2_D_MF] ADD [SUKBD2_ISSUER_COUNTRY] [nvarchar](2) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL;
IF COL_LENGTH(N'dbo.ARS_SUKBD2_D_MF', N'SUKBD2_EXT_DATE') IS NULL
	ALTER TABLE [dbo].[ARS_SUKBD2_D_MF] ADD [SUKBD2_EXT_DATE] [date] NULL;
IF COL_LENGTH(N'dbo.ARS_SUKBD2_D_MF', N'Create_date') IS NULL
	ALTER TABLE [dbo].[ARS_SUKBD2_D_MF] ADD [Create_date] [datetime] NOT NULL CONSTRAINT [DF_ARS_SUKBD2_D_MF_Create_date] DEFAULT (getdate());
IF COL_LENGTH(N'dbo.ARS_SUKBD2_D_MF', N'Create_user') IS NULL
	ALTER TABLE [dbo].[ARS_SUKBD2_D_MF] ADD [Create_user] [nvarchar](20) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL CONSTRAINT [DF_ARS_SUKBD2_D_MF_Create_user] DEFAULT ('system');
GO

-- 每日轉檔以 EXT_DATE 刪除／SP 以 MAX(EXT_DATE) 找最新批次，需要此索引（2026090101 已建者略過）
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[ARS_SUKBD2_D_MF]') AND [name] = N'IX_ARS_SUKBD2_D_MF_ExtDate')
BEGIN
	DECLARE @IndexSql NVARCHAR(MAX) = N'CREATE NONCLUSTERED INDEX [IX_ARS_SUKBD2_D_MF_ExtDate] ON [dbo].[ARS_SUKBD2_D_MF] ([SUKBD2_EXT_DATE] ASC) ON [NCRMS_IDX]';
	IF FILEGROUP_ID(N'NCRMS_IDX') IS NULL
		SET @IndexSql = REPLACE(@IndexSql, N'[NCRMS_IDX]', N'[PRIMARY]');
	EXEC sys.sp_executesql @IndexSql;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.extended_properties
               WHERE major_id = OBJECT_ID(N'[dbo].[ARS_SUKBD2_D_MF]') AND name = N'MS_Description'
                 AND minor_id = COLUMNPROPERTY(OBJECT_ID(N'[dbo].[ARS_SUKBD2_D_MF]'), N'Create_date', 'ColumnId'))
	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'建置時間', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ARS_SUKBD2_D_MF', @level2type=N'COLUMN',@level2name=N'Create_date';
GO

-- ---------- 01_Table/MONITORDATA_STAGE.sql ----------
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
-- =============================================
-- MONITORDATA_STAGE：每日轉檔的暫存表
--   轉檔流程（usp_TransferData、各 usp_Souce*、C# 各 Source、usp_TransferAfterUpdateMonitorData）
--   全部寫入此表，正式表 MONITORDATA 只在最後由 usp_MonitorData_Publish 以短交易換入，
--   避免長時間鎖住正式表。欄位需與 MONITORDATA 完全一致（PK_ID 除外可獨立配號）；
--   MONITORDATA 日後新增欄位時，此表必須同步新增，否則 usp_MonitorData_Publish 會擋下並報錯。
--   只建 (EXT_DATE, SOURCE) 索引供清除與去重查詢使用，不複製正式表其他索引，寫入更快。
-- =============================================
IF OBJECT_ID(N'[dbo].[MONITORDATA_STAGE]', N'U') IS NULL
BEGIN
	DECLARE @FilegroupSql NVARCHAR(MAX) = N'';
	SET @FilegroupSql += N'CREATE TABLE [dbo].[MONITORDATA_STAGE](
	[PK_ID] [int] IDENTITY(1,1) NOT NULL,
	[GROUP_NO] [nvarchar](20) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[UNIT_NO] [nvarchar](20) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[BRANCH_NO] [nvarchar](20) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[TX_DATE] [date] NULL,
	[AS_OF_DATE] [date] NULL,
	[PRODUCT_TYPE] [nvarchar](2) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[TRAN_NO] [nvarchar](25) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[CUSTOMER_NAME] [nvarchar](40) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[CUSTOMER_ID] [nvarchar](11) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[COUNTRY_COD] [nvarchar](2) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[CURENCY_COD] [nvarchar](3) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[TRAN_AMOUNT] [decimal](18, 2) NULL,
	[TO_USD_AMT] [decimal](18, 2) NULL,
	[PERMIT_NO] [nvarchar](20) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[LIMIT] [decimal](18, 2) NULL,
	[LIMIT_COD] [nvarchar](3) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[TO_USD_LIMIT] [decimal](18, 2) NULL,
	[REVOLVE_MK] [bit] NOT NULL CONSTRAINT [DF_MONITORDATA_STAGE_REVOLVE_MK] DEFAULT ((0)),
	[FIL9] [nvarchar](100) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[SOURCE] [nvarchar](100) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[CREATOR] [nvarchar](8) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[LIMIT_MATURITY] [date] NULL,
	[MATURITY_DATE] [date] NULL,
	[GROUP_NAME] [nvarchar](100) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[INDUSTRY] [nvarchar](6) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[INDUSTRY_Type] [int] NULL,
	[PRODUCT_CODE] [nvarchar](20) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[CUR_BOUGHT] [nchar](3) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[CUR_SOLD] [nchar](3) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[RISKFACTOR] [decimal](10, 2) NULL,
	[WEIGHTS] [int] NULL,
	[DATADATE] [date] NULL,
	[Create_Date] [date] NULL CONSTRAINT [DF_MONITORDATA_STAGE_Create_Date] DEFAULT (getdate()),
	[Create_DateTime] [datetime] NULL CONSTRAINT [DF_MONITORDATA_STAGE_Create_DateTime] DEFAULT (getdate()),
	[Create_user] [nvarchar](20) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL CONSTRAINT [DF_MONITORDATA_STAGE_Create_user] DEFAULT (''System''),
	[Year] [int] NULL,
	[Month] [int] NULL,
	[Week] [int] NULL,
	[EXT_DATE] [date] NULL,
	[Mark] [bit] NULL,
	[Lock] [bit] NULL,
	[TOP_Limit_USD_Amount] [decimal](18, 2) NULL,
	[TOP_Limit_Amount] [decimal](18, 2) NULL,
	[TRAN_FXRATE] [decimal](18, 10) NULL,
	[LIMIT_FXRATE] [decimal](18, 10) NULL,
	[CAL_TO_USD_AMT] [decimal](18, 2) NULL,
	[CAL_TO_USD_LIMIT] [decimal](18, 2) NULL,
	[TOP_Permit_No] [nvarchar](13) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[TOP_Limit_Cod] [nvarchar](3) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[TOP_Country_Cod] [nvarchar](2) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[TOP_Limit_Maturity] [date] NULL,
 CONSTRAINT [PK_MONITORDATA_STAGE] PRIMARY KEY CLUSTERED
(
	[PK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_TAB]
) ON [NCRMS_TAB]';
	IF FILEGROUP_ID(N'NCRMS_TAB') IS NULL
		SET @FilegroupSql = REPLACE(@FilegroupSql, N'[NCRMS_TAB]', N'[PRIMARY]');
	EXEC sys.sp_executesql @FilegroupSql;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MONITORDATA_STAGE_EXTDATE_SOURCE' AND object_id = OBJECT_ID(N'[dbo].[MONITORDATA_STAGE]'))
BEGIN
	DECLARE @IndexSql NVARCHAR(MAX) = N'';
	SET @IndexSql += N'CREATE NONCLUSTERED INDEX [IX_MONITORDATA_STAGE_EXTDATE_SOURCE] ON [dbo].[MONITORDATA_STAGE]
(
	[EXT_DATE] ASC,
	[SOURCE] ASC
)
INCLUDE([BRANCH_NO],[PERMIT_NO],[FIL9]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX]';
	IF FILEGROUP_ID(N'NCRMS_IDX') IS NULL
		SET @IndexSql = REPLACE(@IndexSql, N'[NCRMS_IDX]', N'[PRIMARY]');
	EXEC sys.sp_executesql @IndexSql;
END
GO

-- 部署後即刻驗證：正式表的每個欄位在暫存表都要存在，缺任何一個就停止部署
IF EXISTS (
	SELECT 1
	FROM sys.columns m
	WHERE m.object_id = OBJECT_ID(N'[dbo].[MONITORDATA]')
	  AND NOT EXISTS (
		SELECT 1 FROM sys.columns s
		WHERE s.object_id = OBJECT_ID(N'[dbo].[MONITORDATA_STAGE]') AND s.name = m.name))
BEGIN
	DECLARE @Missing NVARCHAR(MAX) = (
		SELECT STUFF((
			SELECT N', ' + m.name
			FROM sys.columns m
			WHERE m.object_id = OBJECT_ID(N'[dbo].[MONITORDATA]')
			  AND NOT EXISTS (
				SELECT 1 FROM sys.columns s
				WHERE s.object_id = OBJECT_ID(N'[dbo].[MONITORDATA_STAGE]') AND s.name = m.name)
			FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 2, N''));
	DECLARE @Msg NVARCHAR(4000) = N'MONITORDATA_STAGE 缺少 MONITORDATA 的欄位：' + @Missing + N'，請先補齊欄位再繼續部署。';
	THROW 50010, @Msg, 1;
END
GO

-- ---------- 02_StoredProcedure/01_usp_Souce01_OBBS_By_OS_LNSMSTD_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	01OBBS之海外各業務交易資料(OS_LNSMSTD_D_MF) 轉檔，根據分行交易最大日期 交易檔

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce01_OBBS_By_OS_LNSMSTD_D_MF] @EXT_DATE AS DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL
			DROP TABLE #TEMP;

		SELECT DISTINCT Trim(LNSMSTD_BRANCH_NO) AS BRANCH_NO,
		'077' AS Unit_NO,--處級單位代號
		case Trim(LNSMSTD_TX_TYPE)
			WHEN 'SL' THEN '01'  -- 聯合貸款
			WHEN 'GU' THEN '12'  -- 保證
			WHEN 'E3' THEN '03'  -- 保兌
			--WHEN 'E5' THEN '10'  -- 應收帳款承購 --賢欽 2025/11/13 說不用
		ELSE '02' -- 一般放款
		end AS PRODUCT_TYPE,--產品別
		Trim(LNSMSTD_TX_NO) AS TRAN_NO,--交易代號
		'018' AS Group_NO, --事業群代號 海外分行只有海外事業群 所以018
		cast(LNSMSTD_BEGIN_DATE as date) AS TX_DATE, --原始初貸日 = 交易日期
		Trim(LNSLMSD_CUSTOMER_NAME) AS CUSTOMER_NAME, --客戶姓名 -- 空要抓 c100 ，依據跟客戶ID 分行
		Trim(LNSMSTD_CUSTOMER_ID) AS CUSTOMER_ID, -- 客戶ID
		Trim(Isnull(LNSLMSD_COUNTRY_RISK,Isnull(LNSLMSD_REG_COUNTRY,''))) AS COUNTRY_COD,--交易國家 空 要抓c100
		Trim(LNSMSTD_CURRENCY) AS CURENCY_COD, --幣別
		LNSMSTD_BALANCE AS TRAN_AMOUNT, -- 交易金額
		Trim(LNSLMSD_APP_NO) AS PERMIT_NO,--核准編號
		ISNULL(LNSLMSD_APP_AMT,LNSMSTD_BALANCE) AS LIMIT,--核准額度  空 抓 交易金額
		ISNULL(Trim(LNSLMSD_CURRENCY),LNSMSTD_CURRENCY) AS LIMIT_COD, --核准幣別 空 抓交易幣別
		LEFT(LNSMSTD_MATURITY, 8) AS MATURITY_DATE,--到期日
		LNSMSTD_DATA_DATE AS AS_OF_DATE,--資料日期
		CASE TRIM(Isnull(LNSLMSD_CIRCLE,'')) WHEN 'Y' THEN 1 ELSE 0 END AS REVOLVE_MK,--是否循環 空 為 0
		'OS_LNSMSTD_D_MF' AS FIL9,-- 行業別主檔 只有授信產品
		'01' AS source,
		'system' AS creator,
		LNSMSTD_ACC_CODE_INT_9, -- 判斷是否為利息
		LNSMSTD_ACCRUE_INT,--利息
		LNSLMSD_MATURITY AS LIMIT_MATURITY, --額度到期日 空 可能要無限大
		--TRIM(LNSM.BUSINS_CODE) AS INDUSTRY, -- 行業別主檔 只有授信產品
		--2 AS INDUSTRY_TYPE, --海外
		@EXT_DATE as EXT_DATE,
		LNSL.LNSLMSD_TOP_LINE_APP_AMT,
		LNSL.LNSLMSD_TOP_LINE_LINE_NO,
		LNSL.LNSLMSD_TOP_LINE_CCY,
		LNSL.LNSLMSD_TOP_LINE_CRISK,
		LNSL.LNSLMSD_TOP_LINE_MATURITY
		INTO #TEMP
		FROM OS_LNSMSTD_D_MF LNSM --海外分行授信業務交易主檔
		LEFT JOIN OS_LNSLMSD_D_MF LNSL ON --海外分行額度檔
			LNSMSTD_LINE_NO = LNSLMSD_LINE_NO AND -- 額度號碼
			LNSMSTD_BRANCH_NO = LNSLMSD_BRANCH_NO AND -- 分行編號
			EXISTS (
				SELECT 1
				FROM (
					SELECT LNSLMSD_BRANCH_NO, MAX(LNSLMSD_EXT_DATE) AS MAX_DATE
					FROM OS_LNSLMSD_D_MF
					WHERE LNSLMSD_EXT_DATE <= @EXT_DATE
					GROUP BY LNSLMSD_BRANCH_NO
				) Latest
				WHERE LNSL.LNSLMSD_BRANCH_NO = Latest.LNSLMSD_BRANCH_NO
				AND LNSL.LNSLMSD_EXT_DATE = Latest.MAX_DATE
			)
		WHERE
			 --到期且餘額 = 0 排除
		 -- 取到期日要大於轉檔日的資料，除了催收，催收項目為 LNSMSTD_ACC_CODE_INT_9 IN ('135850003','135850004')，催收的項目會超過到期日
		NOT (LNSMSTD_BALANCE = 0 AND ( LNSLMSD_MATURITY IS NULL OR LNSLMSD_MATURITY < LNSMSTD_EXT_DATE) and LNSMSTD_ACC_CODE_INT_9 not in ('135850003','135850004')) AND
		TRIM(LNSLMSD_COUNTRY_RISK) <> 'TW' AND -- 排除台灣
				EXISTS (
					SELECT 1
					FROM (
						SELECT LNSMSTD_BRANCH_NO, MAX(LNSMSTD_EXT_DATE) AS MAX_DATE
						FROM OS_LNSMSTD_D_MF
						WHERE LNSMSTD_EXT_DATE <= @EXT_DATE
						GROUP BY LNSMSTD_BRANCH_NO
					) Latest
					WHERE LNSM.LNSMSTD_BRANCH_NO = Latest.LNSMSTD_BRANCH_NO
					AND LNSM.LNSMSTD_EXT_DATE = Latest.MAX_DATE
				) AND
			TRIM(lnsmstd_status) <> '2'  -- 排除呆帳

		INSERT INTO MONITORDATA_STAGE (
		BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
		CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
		PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
		SOURCE, CREATOR, LIMIT_MATURITY,EXT_DATE,TOP_Limit_Amount,TOP_Permit_No,TOP_Limit_Cod,TOP_Country_Cod,TOP_Limit_Maturity)
		SELECT BRANCH_NO,Unit_NO,PRODUCT_TYPE,TRAN_NO,Group_NO,TX_DATE,CUSTOMER_NAME,
				CUSTOMER_ID,COUNTRY_COD,CURENCY_COD,TRAN_AMOUNT,PERMIT_NO,LIMIT,LIMIT_COD,MATURITY_DATE,AS_OF_DATE,REVOLVE_MK,FIL9,
				source,creator,LIMIT_MATURITY,EXT_DATE,LNSLMSD_TOP_LINE_APP_AMT,LNSLMSD_TOP_LINE_LINE_NO,LNSLMSD_TOP_LINE_CCY,
				LNSLMSD_TOP_LINE_CRISK,LNSLMSD_TOP_LINE_MATURITY
		From #TEMP
		UNION
		-- 利息要再加上去 LNSMSTD_ACC_CODE_INT_9 in ('135850003','135850004') and LNSMSTD_ACCRUE_INT <> 0
			SELECT BRANCH_NO,Unit_NO,PRODUCT_TYPE,TRAN_NO,Group_NO,TX_DATE,CUSTOMER_NAME,
				CUSTOMER_ID,COUNTRY_COD,CURENCY_COD,LNSMSTD_ACCRUE_INT,PERMIT_NO,LIMIT,
				LIMIT_COD,MATURITY_DATE,AS_OF_DATE,REVOLVE_MK,FIL9 + '_Interest',
				source,creator,LIMIT_MATURITY,EXT_DATE,LNSLMSD_TOP_LINE_APP_AMT,LNSLMSD_TOP_LINE_LINE_NO,LNSLMSD_TOP_LINE_CCY,
				LNSLMSD_TOP_LINE_CRISK,LNSLMSD_TOP_LINE_MATURITY
			From #TEMP
			WHERE LNSMSTD_ACC_CODE_INT_9 in ('135850003','135850004') and LNSMSTD_ACCRUE_INT <> 0
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/02_usp_Souce01_OBBS_By_OSBDKF02_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	01OBBS海外債券(OSBDKF02_MF) 轉檔，根據分行交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce01_OBBS_By_OSBDKF02_MF] @EXT_DATE AS DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

	--Declare @EXT_DATE Date = '2026-09-01';
	Declare @BufferDate INT = 14;
	IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL
			DROP TABLE #TEMP;
	SELECT *
	INTO #TEMP
	FROM OSBDKF02_MF a
	WHERE TRIM(OSBDKF02_ISSUER_COUNTRY) <> 'TW' AND
		-- 檢查是否為最新資料
		EXISTS (
			SELECT 1
			FROM (
				SELECT OSBDKF02_BRANCH_NO, MAX(OSBDKF02_EXT_DATE) AS MAX_DATE
				FROM OSBDKF02_MF
				WHERE OSBDKF02_EXT_DATE <= @EXT_DATE
				GROUP BY OSBDKF02_BRANCH_NO
			) Latest
			WHERE
				a.OSBDKF02_BRANCH_NO = Latest.OSBDKF02_BRANCH_NO AND
				a.OSBDKF02_EXT_DATE = Latest.MAX_DATE
		) AND
		LEFT(OSBDKF02_AC_9, 5) not in ('22501','13007') AND --文件編號：D211150
		(OSBDKF02_MATURITY_DATE IS NULL OR DATEADD(DAY,@BufferDate,OSBDKF02_MATURITY_DATE) >= @EXT_DATE)

	INSERT INTO MONITORDATA_STAGE (
	    BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
	    CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
	    PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE,  FIL9,
	    SOURCE, CREATOR, LIMIT_MATURITY,EXT_DATE)
	SELECT
		TRIM(OSBDKF02_BRANCH_NO) AS BRANCH_NO,
		'077' AS DIVISION_NO,
		'08' AS PRODUCT_TYPE,  -- 08 有價証券投資
		TRIM(OSBDKF02_TRAN_NO) AS TRAN_NO, --交易編號
		'018' AS BUSINESS_UNIT,
		OSBDKF02_DOWN_DATE AS TX_DATE, --訂約日期
		TRIM(OSBDKF02_CUST_NAME1) AS CUSTOMER_NAME,
		TRIM(OSBDKF02_SWIFT_ID) AS CUSTOMER_ID,
		TRIM(OSBDKF02_ISSUER_COUNTRY) AS COUNTRY_COD,
		TRIM(OSBDKF02_CURENCY_COD) AS CURENCY_COD,
		(OSBDKF02_BALANCE_AMT / OSBDKF02_PRICE) *100 AS TRAN_AMOUNT, -- 改抓OSBDKF02_BALANCE_AMT
		TRIM(OSBDKF02_LINE_PERMIT_NO) + OSBDKF02_BRANCH_NO AS PERMIT_NO, --核准編號
		(OSBDKF02_BALANCE_AMT / OSBDKF02_PRICE) *100 AS LIMIT, --核准額度 -- 改抓OSBDKF02_BALANCE_AMT
		TRIM(OSBDKF02_CURENCY_COD) AS LIMIT_COD, --幣別
		OSBDKF02_MATURITY_DATE AS MATURITY_DATE,
		OSBDKF02_TX_DATE AS AS_OF_DATE,
		'OSBDKF02_MF' AS FIL9,
		'01' AS SOURCE,
		'system' AS CREATOR,
		OSBDKF02_MATURITY_DATE AS LIMIT_MATURITY,
		--TRIM(BUSINS_CODE) AS INDUSTRY,
		--2,
		@EXT_DATE AS EXT_DATE


	FROM #TEMP
	--國家風險餘額計算步驟：
	--	一、	依「CUST-NAME1」加總「BOND PRICE」之折美金值加總之金額如小於0，則不計入。
	--	三、	將各「CUST-NAME1」之加總「BOND PRICE」折美金值，依國碼別加總  ???
	WHERE EXISTS (
			SELECT 1
			FROM #TEMP MF2
			WHERE TRIM(MF2.OSBDKF02_CUST_NAME1) = TRIM(#TEMP.OSBDKF02_CUST_NAME1) AND
			MF2.OSBDKF02_BRANCH_NO = #TEMP.OSBDKF02_BRANCH_NO
			GROUP BY TRIM(MF2.OSBDKF02_CUST_NAME1), MF2.OSBDKF02_BRANCH_NO
			HAVING SUM(MF2.OSBDKF02_BOND_PRICE) > 0
		);
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/03_usp_Souce01_OBBS_By_OSFXKF02_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	01OBBS延伸性金融商品FXSWAP(OSFXKF02_MF) 轉檔，根據分行交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce01_OBBS_By_OSFXKF02_MF] @EXT_DATE AS DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

	--Declare @EXT_DATE Date = '2026-09-01';
	Declare @BufferDate INT = 14;
	INSERT INTO MONITORDATA_STAGE (
		BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
		CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
		LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, FIL9,
		SOURCE, CREATOR, LIMIT_MATURITY,CUR_BOUGHT,CUR_SOLD,EXT_DATE)
	SELECT
		TRIM(OSFXKF02_BRANCH_NO) AS BRANCH_NO,
		'077' AS DIVISION_NO,
		'07' AS PRODUCT_TYPE,
		TRIM(OSFXKF02_TRAN_NO) AS TRAN_NO,
		'018' AS BUSINESS_UNIT,
		OSFXKF02_DEL_DATE AS TX_DATE,
		TRIM(OSFXKF02_CUST_NAME1) AS CUSTOMER_NAME,
		TRIM(OSFXKF02_CUATOMER_ID) AS CUSTOMER_ID,
		TRIM(COALESCE(NULLIF(TRIM(OSFXKF02_CPTY_COUNTRY_RISK), ''), OSFXKF02_CPTY_COUNTRY)) AS COUNTRY_COD,
		TRIM(OSFXKF02_OBJECT_CCY) AS CURENCY_COD,
		OSFXKF02_OBJECT_AMT AS TRAN_AMOUNT,
		OSFXKF02_OBJECT_AMT AS LIMIT,
		TRIM(OSFXKF02_OBJECT_CCY) AS LIMIT_COD,
		OSFXKF02_VALUE_DATE0 AS MATURITY_DATE,
		OSFXKF02_TX_DATE AS AS_OF_DATE,
		'OSFXKF02_MF' AS FIL9,
		'01' AS source,
		'system' AS creator,
		OSFXKF02_VALUE_DATE0 AS LIMIT_MATURITY,
		--TRIM(BUSINS_CODE) AS INDUSTRY,
		--2,
		OSFXKF02_CUR_BOUGHT as CUR_BOUGHT,
		OSFXKF02_CUR_SOLD AS CUR_SOLD,
		@EXT_DATE AS EXT_DATE
	FROM OSFXKF02_MF a
	WHERE OSFXKF02_TX_TYPE = '03' AND
		  TRIM(ISNULL(OSFXKF02_CPTY_COUNTRY_RISK,'')) <> 'TW' AND
			EXISTS (
					SELECT 1
					FROM (
						SELECT OSFXKF02_BRANCH_NO, MAX(OSFXKF02_EXT_DATE) AS MAX_DATE
						FROM OSFXKF02_MF
						WHERE OSFXKF02_EXT_DATE <= @EXT_DATE
						GROUP BY OSFXKF02_BRANCH_NO
					) Latest
					WHERE a.OSFXKF02_BRANCH_NO = Latest.OSFXKF02_BRANCH_NO AND
					      a.OSFXKF02_EXT_DATE = Latest.MAX_DATE
				) and
		  (a.OSFXKF02_VALUE_DATE0 is null or DATEADD(DAY,@BufferDate,a.OSFXKF02_VALUE_DATE0) >= @EXT_DATE)
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/04_usp_Souce01_OBBS_By_OSISKF02_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	01OBBS衍伸性商品IRS(OSISKF02_MF) 轉檔，根據分行交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce01_OBBS_By_OSISKF02_MF] @EXT_DATE AS DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE,  FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY, PRODUCT_CODE,EXT_DATE)
		SELECT
			TRIM(OSISKF02_BRANCH_NO) AS BRANCH_NO,
			'077' AS DIVISION_NO,
			'07' AS PRODUCT_TYPE,
			TRIM(OSISKF02_TRAN_NO) AS TRAN_NO,
			'018' AS BUSINESS_UNIT,
			OSISKF02_TRADE_DATE AS TX_DATE,
			TRIM(OSISKF02_CUST_NAME1) AS CUSTOMER_NAME,
			TRIM(OSISKF02_CUATOMER_ID) AS CUSTOMER_ID,
			TRIM(OSISKF02_CPTY_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(OSISKF02_IN_CCY) AS CURENCY_COD,
			OSISKF02_risk_amt AS TRAN_AMOUNT,
			OSISKF02_risk_amt AS LIMIT,
			TRIM(OSISKF02_IN_CCY) AS LIMIT_COD,
			OSISKF02_MATURITY AS MATURITY_DATE,
			OSISKF02_TX_DATE AS AS_OF_DATE,
			'OSISKF02_MF' AS FIL9,
			'01' AS source,
			'system' AS creator,
			OSISKF02_MATURITY AS LIMIT_MATURITY,
			--TRIM(BUSINS_CODE) AS INDUSTRY,
			--2,
			'IRS' AS PRODUCT_CODE,
			@EXT_DATE AS EXT_DATE
		FROM OSISKF02_MF a
		WHERE
			TRIM(OSISKF02_CPTY_COUNTRY_RISK) <> 'TW' AND
			 -- 檢查是否為最新資料
			EXISTS (
				SELECT 1
				FROM (
					SELECT OSISKF02_BRANCH_NO, MAX(OSISKF02_EXT_DATE) AS MAX_DATE
					FROM OSISKF02_MF
					WHERE OSISKF02_EXT_DATE <= @EXT_DATE
					GROUP BY OSISKF02_BRANCH_NO
				) Latest
				WHERE a.OSISKF02_BRANCH_NO = Latest.OSISKF02_BRANCH_NO AND
					a.OSISKF02_EXT_DATE = Latest.MAX_DATE
			) and  (a.OSISKF02_MATURITY is null or DATEADD(DAY,@BufferDate,a.OSISKF02_MATURITY) >= @EXT_DATE)
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/05_usp_Souce01_OBBS_By_OSMMKF02_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	01OOBS 海外拆款與存同業務(OSMMKF02_MF) 轉檔，根據分行交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce01_OBBS_By_OSMMKF02_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		Declare @BufferDate INT = 14;
		--Declare @EXT_DATE Date = '2026-09-01';

		SELECT *,
		CASE TRIM(OSMMKF02_TRAN_TYPE) WHEN '1' THEN '09' -- 09 拆款業務
		ELSE '04' -- 04 存同
		END PRODUCT_TYPE,
		CASE TRIM(OSMMKF02_TRAN_TYPE) WHEN '1' THEN OSMMKF02_MATURITY_DATE
		ELSE DATEFROMPARTS(YEAR(GETDATE()), 12, 31)
		END LIMIT_MATURITY
		INTO #TEMP
		FROM OSMMKF02_MF a
		cross apply(
			select CASE TRIM(OSMMKF02_TRAN_TYPE) WHEN '1' THEN OSMMKF02_MATURITY_DATE
				ELSE isnull(OSMMKF02_MATURITY_DATE,DATEADD(MONTH, 1, GETDATE()))
				END MATURITY_DATE 	
		) b
		WHERE TRIM(OSMMKF02_COUNTRY_RISK) <> 'TW' AND
		(TRIM(OSMMKF02_TRAN_TYPE) = '1' OR -- 1 = 09拆款
		(TRIM(OSMMKF02_TRAN_TYPE) IN ('3','4','5','6') AND -- 3,4,5,6  = 04 存同
			LEFT(TRIM(OSMMKF02_SWIFT_ID), 4) <> 'FCBK')) AND -- FCB 國外分公司(FCBK是 FCB 國內外分行，FCBC 是加州分行，要算入)
		(b.MATURITY_DATE is null or DATEADD(DAY,@BufferDate,b.MATURITY_DATE) >= @EXT_DATE) AND
		EXISTS (
				SELECT 1
				FROM (
					SELECT OSMMKF02_BRANCH_NO, MAX(OSMMKF02_EXT_DATE) AS MAX_DATE
					FROM OSMMKF02_MF
					WHERE OSMMKF02_EXT_DATE <= @EXT_DATE
					GROUP BY OSMMKF02_BRANCH_NO
				) Latest
				WHERE a.OSMMKF02_BRANCH_NO = Latest.OSMMKF02_BRANCH_NO
				AND a.OSMMKF02_EXT_DATE = Latest.MAX_DATE
		)
		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,EXT_DATE)
		SELECT TRIM(OSMMKF02_BRANCH_NO) AS BRANCH_NO,
			'077' AS DIVISION_NO,
			PRODUCT_TYPE AS PRODUCT_TYPE,
			ISNULL(OSMMKF02_TRAN_NO,
				TRIM(OSMMKF02_BRANCH_NO) +
				TRIM(OSMMKF02_TRAN_TYPE) +
				TRIM(OSMMKF02_SWIFT_ID) +
				TRIM(OSMMKF02_CURENCY_COD)) AS TRAN_NO,
			'018' AS BUSINESS_UNIT,
			OSMMKF02_CONTRACT_DATE AS TX_DATE,
			TRIM(OSMMKF02_CUST_NAME1) AS CUSTOMER_NAME,
			TRIM(OSMMKF02_SWIFT_ID) AS CUSTOMER_ID,
			TRIM(OSMMKF02_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(OSMMKF02_CURENCY_COD) AS CURENCY_COD,
			ABS(OSMMKF02_TRAN_AMOUNT) AS TRAN_AMOUNT,
			ABS(OSMMKF02_TRAN_AMOUNT) AS LIMIT,
			TRIM(OSMMKF02_CURENCY_COD) AS LIMIT_COD,
			MATURITY_DATE AS MATURITY_DATE,
			OSMMKF02_TX_DATE AS AS_OF_DATE,
			'OSMMKF02_MF' AS FIL9,
			'01' AS source,
			'system' AS creator,
			LIMIT_MATURITY AS LIMIT_MATURITY,
			--TRIM(BUSINS_CODE) AS INDUSTRY,
			--2,
			@EXT_DATE AS EXT_DATE
		FROM #TEMP
		WHERE
			EXISTS (
			SELECT 1
			FROM #TEMP MF2
			WHERE LEFT(TRIM(MF2.OSMMKF02_SWIFT_ID),4) = LEFT(TRIM(OSMMKF02_SWIFT_ID),4)
			GROUP BY LEFT(TRIM(MF2.OSMMKF02_SWIFT_ID),4),case OSMMKF02_TRAN_TYPE when '1' then 1 else 0 end -- 原本有分 1 = 拆放, 其他存同
			HAVING SUM(ABS(MF2.OSMMKF02_TRAN_AMOUNT)) > 0)
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/06_usp_Souce04_By_LS_LSRSA_D_MF.sql ----------
/****** Object:  StoredProcedure [dbo].[usp_Souce04_By_LS_LSRSA_D_MF]    Script Date: 16/9/2026 下午2:56:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	04存放銀行同業 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce04_By_LS_LSRSA_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		
		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY, EXT_DATE)
		SELECT
			'D01' AS BRANCH_NO,
			'091' AS DIVISION_NO,
			'04' AS PRODUCT_TYPE,
			TRIM(APRV_NO) AS TRAN_NO,
			'018' AS BUSINESS_UNIT,
			EXT_DATE AS TX_DATE,
			TRIM(ENG_NAME) AS CUSTOMER_NAME,
			TRIM(ISIN_CD) AS CUSTOMER_ID,
			TRIM(COUNTRY) AS COUNTRY_COD,
			TRIM(CURRENCY) AS CURENCY_COD,
			LN_BAL AS TRAN_AMOUNT,
			NULL AS PERMIT_NO,
			LN_BAL AS LIMIT,
			TRIM(CURRENCY) AS LIMIT_COD,
			DATEADD(month, 1, GETDATE()) AS MATURITY_DATE,
			EXT_DATE AS AS_OF_DATE,
			'LS_LSRSA_D_MF' AS FIL9,
			'04' AS source,
			'system' AS creator,
			DATEFROMPARTS(YEAR(GETDATE()), 12, 31) AS LIMIT_MATURITY,
			--right(BUSINS_CODE,6) AS INDUSTRY,
			--1,
			@EXT_DATE AS EXT_DATE
		FROM LS_LSRSA_D_MF
		WHERE (SELECT MAX(EXT_DATE) FROM LS_LSRSA_D_MF WHERE EXT_DATE <= @EXT_DATE) = EXT_DATE AND
			LEFT(ACC_CODE, 5) = '11021' AND
			TRIM(COUNTRY) <> 'TW' AND
			LEFT(TRIM(ISIN_CD), 4) <> 'FCBK' 
		--UNION ALL
		--SELECT
		--	'098' AS BRANCH_NO,
		--	'069' AS DIVISION_NO,
		--	'04' AS PRODUCT_TYPE,
		--	NULL AS TRAN_NO,
		--	'016' AS BUSINESS_UNIT,
		--	ACNOD_EXT_DATE AS TX_DATE,
		--	'HSBC (GLOBAL CUSTODY CASH)' AS CUSTOMER_NAME,
		--	'HSBCHKHHGCC' AS CUSTOMER_ID,
		--	'GB' AS COUNTRY_COD,
		--	TRIM(ACNOD_CRCY_CODE) AS CURENCY_COD,
		--	ACNOD_OPER_DATE_BAL_INF AS TRAN_AMOUNT,
		--	NULL AS PERMIT_NO,
		--	ACNOD_OPER_DATE_BAL_INF AS LIMIT,
		--	TRIM(ACNOD_CRCY_CODE) AS LIMIT_COD,
		--	DATEFROMPARTS(YEAR(GETDATE()), 12, 31) AS MATURITY_DATE,
		--	ACNOD_EXT_DATE AS AS_OF_DATE,
		--	'ACNOD_STG' AS FIL9,
		--	'04' AS source,
		--	'system' AS creator,
		--	DATEFROMPARTS(YEAR(GETDATE()), 12, 31) AS LIMIT_MATURITY,
		--	--null AS INDUSTRY,
		--	--null,
		--	@EXT_DATE AS DATADATE
		--FROM ACNOD_STG
		--WHERE ACNOD_BRANCH_CODE = '092' AND
	　--		 ACNOD_ACC5_CODE = '11134' AND
		--	ACNOD_ACC5_SUB_CODE = '001' AND
		--	ACNOD_LAST_BAL_MARK = 'Y' AND
		--	(SELECT MAX(ACNOD_EXT_DATE) FROM ACNOD_STG WHERE ACNOD_EXT_DATE <= @EXT_DATE) = ACNOD_EXT_DATE;

	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END

-- ---------- 02_StoredProcedure/07_usp_Souce06_By_FL_FLMST_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	06外貸系統(外幣貸款系統) 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce06_By_FL_FLMST_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		Declare @MaxFLMST_EXTDATE DATE = (SELECT MAX(FLMST_EXT_DATE) FROM FL_FLMST_D_MF WHERE FLMST_EXT_DATE <= @EXT_DATE)
		Declare @MaxFMLINE_EXTDATE DATE = (SELECT MAX(FMLINE_EXT_DATE) FROM FM_FMLINE_D_MF WHERE FMLINE_EXT_DATE <= @EXT_DATE)
		IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL
			DROP TABLE #TEMP;

		SELECT MF.*,right(mf.BUSINS_CODE,6) INDUSTRY,
				CIF.CIF_CUST_NAME,CR.CountryCode2,
				LINE.FMLINE_LINE_AMT,LINE.FMLINE_REVOLING_TYPE,
				LINE.FMLINE_LINE_EXPIRY,
				LINE.FMLINE_MULT_MERGED_MARK,
				LINE.FMLINE_MULT_MERGED_APRV_NO,
				CUR.CRCY_ENG_NAME AS CURNAME,
				CUR1.CRCY_ENG_NAME AS CURNAME1,
				CASE WHEN FLMST_LOAN_TYPE = '10'
				THEN FLMST_ADVANCE_BALANCE + FLMST_DISCOUNT_INT
				ELSE FLMST_ADVANCE_BALANCE END as TRAN_AMOUNT,
				D.MATURITY_DATE
		INTO #TEMP
		FROM FL_FLMST_D_MF MF
		LEFT JOIN DAILY_CIF_TMP CIF ON REPLACE(FLMST_CUST_ID,' ','') = RTRIM(CIF.CIF_ID_NO) + CIF_ID_SER_NO
		LEFT JOIN FM_FMLINE_D_MF LINE ON
			LINE.FMLINE_EXT_DATE = FLMST_EXT_DATE AND
			LINE.FMLINE_DATE_TYPE = '10' AND
			FLMST_APRV_TYPE_1 = LINE.FMLINE_LINE_TYPE AND
			FLMST_CUST_ID = LINE.FMLINE_CUST_ID AND
			FLMST_RECV_BRANCH = LINE.FMLINE_BRANCH AND
			FLMST_APRV_NO_1 = LINE.FMLINE_APRV_NO
		LEFT JOIN CountryMaster CR on TRIM(FLMST_FINAL_RISK_CNTY) = CR.CountryCode4
		INNER JOIN MIS_CRCY_REF CUR ON TRIM(FLMST_CURENCY) = TRIM(CUR.CRCY_CODE)
		INNER JOIN MIS_CRCY_REF CUR1 ON TRIM(FLMST_APRV_CUR_1) = TRIM(CUR1.CRCY_CODE)
		CROSS APPLY(
			SELECT CASE WHEN FLMST_LOAN_TYPE = '10' 
			THEN FLMST_CLOSE_DATE 
			ELSE FLMST_MATURITY END as MATURITY_DATE
		) D
		WHERE FLMST_EXT_DATE = @MaxFLMST_EXTDATE AND
				TRIM(FLMST_FINAL_RISK_CNTY) NOT IN('0000','1001') AND
				TRIM(FLMST_DATA_TYPE) = '0' AND　-- 待確認
				NOT(FLMST_LOAN_TYPE = '10' AND ISNULL(FLMST_SUBSTITUTE_REMIT_MK, '') = 'N') AND --註記邏輯可能要調整
				TRIM(FLMST_DATA_STATUS) in ('0', '2', '4') and -- 2是催收資料 -- 0 一般資料
				(D.MATURITY_DATE is null or DATEADD(DAY,@BufferDate,D.MATURITY_DATE) >= @EXT_DATE)
		INSERT INTO MONITORDATA_STAGE (
		    BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
		    CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
		    PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,INDUSTRY,INDUSTRY_Type,EXT_DATE)
		SELECT
			TRIM(FLMST_RECV_BRANCH) as BRANCH_NO,
			'064' as DIVISION_NO,
			'02' as PRODUCT_TYPE,
			TRIM(FLMST_LC_NO) as TRAN_NO,
			'011' as BUSINESS_UNIT,
			FLMST_NEGO_DATE as TX_DATE,
			TRIM(CIF_CUST_NAME) as CUSTOMER_NAME,
			TRIM(FLMST_CUST_ID) as CUSTOMER_ID,
			CountryCode2 as COUNTRY_COD,
			TRIM(CURNAME) as CURENCY_COD,
			TRAN_AMOUNT,
			TRIM(FLMST_APRV_NO_1) as PERMIT_NO,
			FMLINE_LINE_AMT as [LIMIT],
			TRIM(CURNAME1) as LIMIT_COD,
			MATURITY_DATE,
			FLMST_EXT_DATE as AS_OF_DATE,
			CASE FMLINE_REVOLING_TYPE WHEN '1' THEN 1
				 ELSE 0
				 END as REVOLVE_MK,
			'FL_FLMST_D_MF1' as FIL9,
			'06' as source,
			'system' as creator,
			FMLINE_LINE_EXPIRY as LIMIT_MATURITY,
			INDUSTRY as INDUSTRY,
			1,
			@EXT_DATE AS EXT_DATE
		FROM #TEMP
		WHERE TRIM(FLMST_LOAN_TYPE) IN ('24','26')
		UNION ALL
		SELECT
			TRIM(FLMST_RECV_BRANCH) as BRANCH_NO,
			'067' as DIVISION_NO,
			'02' as PRODUCT_TYPE,
			TRIM(FLMST_LC_NO) as TRAN_NO,
			'013' as BUSINESS_UNIT,
			FLMST_NEGO_DATE as TX_DATE,
			TRIM(CIF_CUST_NAME) as CUSTOMER_NAME,
			TRIM(FLMST_CUST_ID) as CUSTOMER_ID,
			CountryCode2 as COUNTRY_COD,
			TRIM(CURNAME) as CURENCY_COD,
			TRAN_AMOUNT,
			TRIM(FLMST_APRV_NO_1) as PERMIT_NO,
			FMLINE_LINE_AMT as [LIMIT],
			TRIM(CURNAME1) as LIMIT_COD,
			MATURITY_DATE,
			FLMST_EXT_DATE as AS_OF_DATE,
			CASE FMLINE_REVOLING_TYPE WHEN '1' THEN 1
				 ELSE 0
				 END as REVOLVE_MK,
			'FL_FLMST_D_MF2' as FIL9,
			'06' as source,
			'system' as creator,
			FMLINE_LINE_EXPIRY as LIMIT_MATURITY,
			INDUSTRY as INDUSTRY,
			1,
			@EXT_DATE AS DATADATE
		FROM #TEMP
		WHERE TRIM(FLMST_LOAN_TYPE) IN ('25','27','28','29')
		UNION ALL
		SELECT
			TRIM(FLMST_RECV_BRANCH) as BRANCH_NO,
			CASE TRIM(FLMST_RECV_BRANCH)
				WHEN '091' THEN '091'
				WHEN '095' THEN '077'
			ELSE '064'
			END as DIVISION_NO,
			CASE WHEN FLMST_LOAN_TYPE IN ('01','02','03','04','05','06','07','08','11','12','13')
					THEN '02'
				WHEN FLMST_LOAN_TYPE = '09'
					THEN '01'
				WHEN FLMST_LOAN_TYPE = '10'
					THEN '12'
				ELSE '02'
			END as PRODUCT_TYPE,
			TRIM(FLMST_LC_NO) as TRAN_NO,
			CASE WHEN TRIM(FLMST_RECV_BRANCH) IN ('091','095')
				THEN '018'
			ELSE '011'
			END as BUSINESS_UNIT,
			FLMST_NEGO_DATE as TX_DATE,
			TRIM(CIF_CUST_NAME) as CUSTOMER_NAME,
			TRIM(FLMST_CUST_ID) as CUSTOMER_ID,
			CountryCode2 as COUNTRY_COD,
			TRIM(CURNAME) as CURENCY_COD,
			TRAN_AMOUNT,
			TRIM(FLMST_APRV_NO_1) as PERMIT_NO,
			FMLINE_LINE_AMT as [LIMIT],
			TRIM(CURNAME1) as LIMIT_COD,
		    MATURITY_DATE,
			FLMST_EXT_DATE as AS_OF_DATE,
			CASE FMLINE_REVOLING_TYPE WHEN '1' THEN 1
				 ELSE 0
				 END as REVOLVE_MK,
			'FL_FLMST_D_MF3' as FIL9,
			'06' as source,
			'system' as creator,
			FMLINE_LINE_EXPIRY as LIMIT_MATURITY,
			INDUSTRY as INDUSTRY,
			1,
			@EXT_DATE AS DATADATE
		FROM #TEMP
		WHERE TRIM(FLMST_LOAN_TYPE) NOT IN ('24','25','26','27')
		
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO




-- ---------- 02_StoredProcedure/08_usp_Souce06_By_FM_FMLINE_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	06外貸系統(外幣貸款系統) 額度檔 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce06_By_FM_FMLINE_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		Declare @MaxFLMST_EXTDATE DATE = (SELECT MAX(FLMST_EXT_DATE) FROM FL_FLMST_D_MF WHERE FLMST_EXT_DATE <= @EXT_DATE)
		Declare @MaxFMLINE_EXTDATE DATE = (SELECT MAX(FMLINE_EXT_DATE) FROM FM_FMLINE_D_MF WHERE FMLINE_EXT_DATE <= @EXT_DATE)
		Declare @MaxELLSTAPV_EXTDATE DATE = (SELECT MAX(ELLSTAPV_EXT_DATE) FROM EL_ELLSTAPV_D_MF WHERE ELLSTAPV_EXT_DATE <= @EXT_DATE)
		
		INSERT INTO MONITORDATA_STAGE (
		    BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
		    CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
		    PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,INDUSTRY,INDUSTRY_Type,EXT_DATE)
		SELECT  -- 額度檔
			TRIM(LINE.FMLINE_BRANCH) as BRANCH_NO,
			CASE TRIM(FLMST_RECV_BRANCH)
				WHEN '091' THEN '091'
				WHEN '095' THEN '077'
			ELSE '064'
			END as DIVISION_NO,
			'' as PRODUCT_TYPE, ---目前沒辦法分產品別
			'' as TRAN_NO,
			CASE WHEN TRIM(FLMST_RECV_BRANCH) IN ('091','095')
				THEN '018'
			ELSE '011'
			END as BUSINESS_UNIT,
			LINE.FMLINE_APRV_DATE as TX_DATE,
			TRIM(CIF_CUST_NAME) as CUSTOMER_NAME,
			TRIM(FMLINE_CUST_ID) as CUSTOMER_ID,
			ISNULL(CR.CountryCode2,ELL.RISK_NACTION_ID) as COUNTRY_COD,
			'' as CURENCY_COD,
			0 as TRAN_AMOUNT,
			LINE.FMLINE_APRV_NO as PERMIT_NO,
			LINE.FMLINE_LINE_AMT as [LIMIT],
			CUR.CRCY_ENG_NAME as LIMIT_COD,
			LINE.FMLINE_LINE_EXPIRY as MATURITY_DATE,
			LINE.FMLINE_EXT_DATE as AS_OF_DATE, -- 不確定
			CASE LINE.FMLINE_REVOLING_TYPE WHEN '1' THEN 1
				 ELSE 0
				 END as REVOLVE_MK,
			'FM_FMLINE_D_MF' as FIL9,
			'06' as source,
			'system' as creator,
			FMLINE_LINE_EXPIRY as LIMIT_MATURITY,
			'' as INDUSTRY, -- 待確認
			1,
			@EXT_DATE AS DATADATE
		FROM FM_FMLINE_D_MF LINE
		LEFT JOIN CountryMaster CR on TRIM(LINE.FMLINE_FINAL_RISK_CNTY) = CR.CountryCode4
		LEFT JOIN EL_ELLSTAPV_D_MF ELL ON LINE.FMLINE_CUST_ID = ELL.ELLSTAPV_CUST_ID AND 
			LINE.FMLINE_APRV_NO = ELLSTAPV_APRV_NO AND @MaxELLSTAPV_EXTDATE = ELL.ELLSTAPV_EXT_DATE  -- 未來要串這個去看國別
		-- 未來FM_FMLINE_D_MF 會有多一個欄位是 FMLINE_OBBS_APRV_NO 海外核准號碼，是為了RISKLINEO 匯入是對應 APROVE_NO，如果有就不用匯入RISKLINEO
		-- RISKLINED 核准編號對應 FMLINE_APRV_NO，如果有就排除RISKLINED
		LEFT JOIN FL_FLMST_D_MF FLMST ON
			@MaxFLMST_EXTDATE = FLMST_EXT_DATE AND
			LINE.FMLINE_DATE_TYPE = '10' AND
			FLMST_APRV_TYPE_1 = LINE.FMLINE_LINE_TYPE AND
			FLMST_CUST_ID = LINE.FMLINE_CUST_ID AND
			FLMST_RECV_BRANCH = LINE.FMLINE_BRANCH AND
			FLMST_APRV_NO_1 = LINE.FMLINE_APRV_NO
		LEFT JOIN DAILY_CIF_TMP CIF ON REPLACE(LINE.FMLINE_CUST_ID,' ','') = RTRIM(CIF.CIF_ID_NO) + CIF.CIF_ID_SER_NO
		LEFT JOIN MIS_CRCY_REF CUR ON TRIM(FMLINE_LINE_CURENCY) = TRIM(CUR.CRCY_CODE)
		WHERE FLMST.FLMST_ACNT_BRANCH IS NULL AND LINE.FMLINE_EXT_DATE = @MaxFMLINE_EXTDATE and 
			  ISNULL(CR.CountryCode2,ELL.RISK_NACTION_ID) not in ('TW','') and
			  (FMLINE_LINE_EXPIRY is null or DATEADD(DAY,@BufferDate,CONVERT(DATE,FMLINE_LINE_EXPIRY,112)) >= @EXT_DATE)
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO




-- ---------- 02_StoredProcedure/09_usp_Souce09_By_ARS_SUKBD2_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKBD2附買回之資料擷取 交易最大日期
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKBD2_D_MF] @EXT_DATE DATE
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

        INSERT INTO MONITORDATA_STAGE (
            BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
            CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
            PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, FIL9,
            SOURCE, CREATOR, LIMIT_MATURITY, EXT_DATE)
        SELECT
            TRIM(MF.SUKBD2_BRANCH_NO)                                           AS BRANCH_NO,
            --TRIM(MF.SUKBD2_ACC_BRANCH_NO)                                       AS UNIT_NO,
			TRIM(MF.SUKBD2_BRANCH_NO)                                       AS UNIT_NO,
            '07'                                                                 AS PRODUCT_TYPE,
            TRIM(MF.SUKBD2_TRADE_NO)                                            AS TRAN_NO,
            '016'                                                                AS GROUP_NO,
            MF.SUKBD2_TRADE_DAY                                                 AS TX_DATE,
            TRIM(MF.SUKBD2_ISSUER_ID)                                           AS CUSTOMER_NAME,
            TRIM(MF.SUKBD2_ISSUER_APPID)                                        AS CUSTOMER_ID,
            TRIM(MF.SUKBD2_ISSUER_COUNTRY)                                      AS COUNTRY_COD,
            TRIM(MF.SUKBD2_REPO_CCY)                                            AS CURENCY_COD,
            MF.SUKBD2_REPO_AMOUNT                                                AS TRAN_AMOUNT,
            NULL                                                                 AS PERMIT_NO,
            MF.SUKBD2_REPO_AMOUNT                                                AS [LIMIT],
            NULL                                                                 AS LIMIT_COD,
            MF.SUKBD2_END_DATE                                                   AS MATURITY_DATE,
            MF.SUKBD2_EXT_DATE                                                   AS AS_OF_DATE,
            'ARS_SUKBD2_D_MF'                                                   AS FIL9,
            '09'                                                                 AS SOURCE,
            'system'                                                             AS CREATOR,
            MF.SUKBD2_END_DATE                                                   AS LIMIT_MATURITY,
            --TRIM(MF.BUSINS_CODE)                                                 AS INDUSTRY,
            --1                                                                    AS INDUSTRY_Type,
            @EXT_DATE                                                            AS EXT_DATE
        FROM ARS_SUKBD2_D_MF MF
        WHERE MF.SUKBD2_EXT_DATE = (
                SELECT MAX(SUKBD2_EXT_DATE)
                FROM ARS_SUKBD2_D_MF
                WHERE SUKBD2_EXT_DATE <= @EXT_DATE
              ) AND
              MF.SUKBD2_TRADE_TYPE <> 'RP' AND
              TRIM(MF.SUKBD2_ISSUER_COUNTRY) <> 'TW' AND
			  (MF.SUKBD2_END_DATE is null or DATEADD(DAY,@BufferDate,MF.SUKBD2_END_DATE) >= @EXT_DATE)

    END TRY
    BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
        THROW;
    END CATCH
END
GO

-- ---------- 02_StoredProcedure/10_usp_Souce09_By_ARS_SUKBDO_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKBDO衍伸性商品之資料擷取 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKBDO_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE,  FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY, PRODUCT_CODE,EXT_DATE)
		SELECT
			trim(SUKBDO_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKBDO_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKBDO_DESK)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE, -- 衍生性金融商品
			trim(SUKBDO_POSITIONID) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKBDO_TX_DATE	AS TX_DATE,
			trim(SUKBDO_CUST_NAME) AS CUSTOMER_NAME,
			trim(SUKBDO_CUSTOMER_ID) AS CUSTOMER_ID,
			trim(SUKBDO_CPTY_COUNTRY_RISK) AS COUNTRY_COD,
			'USD' AS CURENCY_COD,
			SUKBDO_RISK_AMT As TRAN_AMOUNT,
			SUKBDO_RISK_AMT AS LIMIT,
			'USD' AS LIMIT_COD,
			SUKBDO_OPTIONEXPIRYDATE	AS MATURITY_DATE,
			SUKBDO_EXT_DATE AS AS_OF_DATE,
			'ARS_SUKBDO_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKBDO_OPTIONEXPIRYDATE as LIMIT_MATURITY,
			--TRIM(BUSINS_CODE) AS INDUSTRY,
			--1,
			'BO' AS PRODUCT_CODE,
			@EXT_DATE AS EXT_DATE
		FROM ARS_SUKBDO_D_MF
		WHERE
			(SUKBDO_OPTIONEXPIRYDATE is null or DATEADD(DAY,@BufferDate,SUKBDO_OPTIONEXPIRYDATE) >= @EXT_DATE) and
			SUKBDO_EXT_DATE = (select max(SUKBDO_EXT_DATE)from ARS_SUKBDO_D_MF WHERE SUKBDO_EXT_DATE <= @EXT_DATE) AND
			SUKBDO_BUY_SELL ='1' AND
			SUKBDO_CPTY_COUNTRY_RISK <> 'TW'


	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/11_usp_Souce09_By_ARS_SUKFRA_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09ARS_SUKFRA_D_MF FRA衍伸性商品之資料擷取 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKFRA_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE,  FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY, PRODUCT_CODE,EXT_DATE)
		SELECT
			trim(SUKFRA_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKFRA_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKFRA_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE, -- 衍生性金融商品
			trim(SUKFRA_TRADE_ID) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKFRA_TRADE_DATE AS TX_DATE,
			trim(SUKFRA_CUST_NAME2) AS CUSTOMER_NAME,
			trim(SUKFRA_CUSTOMER_ID) AS CUSTOMER_ID,
			trim(SUKFRA_CPTY_COUNTRY_RISK)	AS COUNTRY_COD,
			'USD'	AS CURENCY_COD,
			SUKFRA_RISK_AMT As TRAN_AMOUNT,
			SUKFRA_RISK_AMT AS LIMIT,
			'USD' AS LIMIT_COD,
			SUKFRA_MATURITY AS MATURITY_DATE,
			SUKFRA_EXT_DATE AS AS_OF_DATE,
			'ARS_SUKFRA_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKFRA_MATURITY as LIMIT_MATURITY,
			--TRIM(SUKFRA_CPTY_BUSINESS) AS INDUSTRY,
			--1,
			'FRA',
			@EXT_DATE
		FROM ARS_SUKFRA_D_MF
		WHERE SUKFRA_EXT_DATE = (select max(SUKFRA_EXT_DATE) from ARS_SUKFRA_D_MF WHERE SUKFRA_EXT_DATE <= @EXT_DATE) AND
			SUKFRA_BUY_SELL = '1' AND
			SUKFRA_CPTY_COUNTRY_RISK <> 'TW' AND
			(SUKFRA_MATURITY is null or DATEADD(DAY,@BufferDate,SUKFRA_MATURITY) >= @EXT_DATE)

	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/12_usp_Souce09_By_ARS_SUKIRO_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09ARS_SUKIRO_D_MF IRO衍伸性商品之資料擷取 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKIRO_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		INSERT INTO MONITORDATA_STAGE (
		    BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
		    CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
		    LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE,  FIL9,
		    SOURCE, CREATOR, LIMIT_MATURITY, PRODUCT_CODE,EXT_DATE)
		SELECT
			trim(SUKIRO_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKIRO_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKIRO_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE, -- 衍生性金融商品
			trim(SUKIRO_TRADE_ID) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKIRO_TRADE_DATE AS TX_DATE,
			trim(SUKIRO_CUST_NAME2) AS CUSTOMER_NAME,
			trim(SUKIRO_CUSTOMER_ID) AS CUSTOMER_ID,
			trim(SUKIRO_CPTY_COUNTRY_RISK)	AS COUNTRY_COD,
			'USD'	AS CURENCY_COD,
			SUKIRO_RISK_AMT As TRAN_AMOUNT,
			SUKIRO_RISK_AMT AS LIMIT,
			'USD' AS LIMIT_COD,
			SUKIRO_MATURITY_DATE	AS MATURITY_DATE,
			SUKIRO_EXT_DATE AS AS_OF_DATE,
			'ARS_SUKIRO_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKIRO_MATURITY_DATE AS LIMIT_MATURITY,
			--TRIM(SUKIRO_CPTY_BUSINESS) AS INDUSTRY,
			--1,
			'IRO' AS PRODUCT_CODE,
			@EXT_DATE
		FROM
			ARS_SUKIRO_D_MF
		WHERE
			SUKIRO_EXT_DATE = (select max(SUKIRO_EXT_DATE) from ARS_SUKIRO_D_MF WHERE SUKIRO_EXT_DATE <= @EXT_DATE) AND
			SUKIRO_BUY_SELL ='1' AND
			SUKIRO_CPTY_COUNTRY_RISK <> 'TW' AND
			(SUKIRO_MATURITY_DATE is null or DATEADD(DAY,@BufferDate,SUKIRO_MATURITY_DATE) >= @EXT_DATE)

	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/13_usp_Souce09_By_ARS_SUKMST_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09ARS_SUKMST_D_MF IRS衍伸性商品之資料擷取 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKMST_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE,  FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY, PRODUCT_CODE,EXT_DATE)
		SELECT
			trim(SUKMST_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKMST_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKMST_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE, -- 衍生性金融商品
			trim(SUKMST_TRAN_NO) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKMST_TRADE_DATE AS TX_DATE,
			trim(SUKMST_CUST_NAME2) AS CUSTOMER_NAME,
			trim(SUKMST_CUSTOMER_ID) AS CUSTOMER_ID,
			trim(SUKMST_CPTY_COUNTRY_RISK)	AS COUNTRY_COD,
			'USD' AS CURENCY_COD,
			SUKMST_RISK_AMT As TRAN_AMOUNT,
			SUKMST_RISK_AMT AS LIMIT,
			'USD' AS LIMIT_COD,
			SUKMST_MATURITY	AS MATURITY_DATE,
			SUKMST_EXT_DATE AS AS_OF_DATE,
			'ARS_SUKMST_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKMST_MATURITY as LIMIT_MATURITY,
			--TRIM(SUKMST_CPTY_BUSINESS) AS INDUSTRY,
			--1,
			'IRS' AS PRODUCT_CODE,
			@EXT_DATE AS EXT_DATE
		FROM ARS_SUKMST_D_MF MF
		WHERE
			SUKMST_EXT_DATE = (SELECT MAX(SUKMST_EXT_DATE) FROM ARS_SUKMST_D_MF WHERE SUKMST_EXT_DATE <= @EXT_DATE) AND
			SUKMST_BUY_SELL ='1' AND
			ISNULL(SUKMST_DEPOSIT_LINK,'') NOT IN('SPD','DCD') AND
			SUKMST_ESTIMATE_FX <> 0 AND -- 因為SUMMIT來的資料有時會給0，計算會錯(不可以除以0)，要排除
			SUKMST_CPTY_COUNTRY_RISK <> 'TW' AND
			(SUKMST_MATURITY is null or DATEADD(DAY,@BufferDate,SUKMST_MATURITY) >= @EXT_DATE)

	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/14_usp_Souce09_By_ARS_SUKNBD1_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKNBD1債券投資之資料擷取 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKNBD1_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		
		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,EXT_DATE)
		SELECT
			TRIM(SUKBD1_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKBD1_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKBD1_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'08' AS PRODUCT_TYPE,
			TRIM(SUKBD1_TRAN_NO) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKBD1_TX_DATE AS TX_DATE,
			TRIM(SUKBD1_CUST_NAME1) AS CUSTOMER_NAME,
			TRIM(SUKBD1_SWIFT_ID) AS CUSTOMER_ID,
			ISNULL(NULLIF(SUKBD1_ISSUER_COUNTRY,''), TRIM(SUKBD1_GU_LOG_CTY)) AS COUNTRY_COD,
			TRIM(SUKBD1_CURENCY_COD) AS CURENCY_COD,
			CASE UPPER(TRIM(SUKBD1_BUY_SELL)) WHEN 'B' THEN SUKBD1_BALANCE_AMT
											  WHEN 'S' THEN SUKBD1_BALANCE_AMT * -1
			END As TRAN_AMOUNT,
			SUKBD1_LINE_PERMIT_NO AS PERMIT_NO,
			CASE UPPER(TRIM(SUKBD1_BUY_SELL)) WHEN 'B' THEN SUKBD1_BALANCE_AMT
											  WHEN 'S' THEN SUKBD1_BALANCE_AMT * -1
			END AS LIMIT,
			TRIM(SUKBD1_CURENCY_COD) AS LIMIT_COD,
			SUKBD1_MATURITY_DATE AS MATURITY_DATE,
			SUKBD1_EXT_DATE AS AS_OF_DATE,
			0 AS REVOLVE_MK,
			'ARS_SUKNBD1_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKBD1_MATURITY_DATE as LIMIT_MATURITY,
			--TRIM(SUKBD1_ISSUER_BUSINESS) AS INDUSTRY,
			--1,
			@EXT_DATE AS EXT_DATE
		FROM ARS_SUKNBD1_D_MF
		WHERE SUKBD1_EXT_DATE = (SELECT MAX(SUKBD1_EXT_DATE) FROM ARS_SUKNBD1_D_MF WHERE SUKBD1_EXT_DATE <= @EXT_DATE) AND
			(SUKBD1_MATURITY_DATE is null or DATEADD(DAY,@BufferDate,SUKBD1_MATURITY_DATE) >= @EXT_DATE) AND
			EXISTS (
				SELECT 1
				FROM ARS_SUKNBD1_D_MF MF2
				WHERE MF2.SUKBD1_EXT_DATE = ARS_SUKNBD1_D_MF.SUKBD1_EXT_DATE AND
					  MF2.SUKBD1_CUST_NAME1 = ARS_SUKNBD1_D_MF.SUKBD1_CUST_NAME1 AND
					  ISNULL(NULLIF(MF2.SUKBD1_ISSUER_COUNTRY,''), TRIM(MF2.SUKBD1_GU_LOG_CTY)) <> 'TW'
				GROUP BY MF2.SUKBD1_CUST_NAME1
				HAVING SUM( CASE UPPER(TRIM(MF2.SUKBD1_BUY_SELL)) WHEN 'B' THEN MF2.SUKBD1_BALANCE_AMT
																  WHEN 'S' THEN MF2.SUKBD1_BALANCE_AMT * -1
							END) > 0
			) AND
			ISNULL(NULLIF(SUKBD1_ISSUER_COUNTRY,''), TRIM(SUKBD1_GU_LOG_CTY))  <> 'TW' AND
			NOT(SUKBD1_MATURITY_DATE = SUKBD1_EXT_DATE AND
				SUKBD1_CURENCY_COD = 'TWD' AND
				SUKBD1_SECURITY_TYPE = 'BILL' AND
				SUKBD1_SEC_SUB_TYPE ='CP2');
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/15_usp_Souce09_By_ARS_SUKNFO_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKNFO 衍生性商品(外匯選擇權) 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKNFO_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		-- 衍生性金融商品資料

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,CUR_BOUGHT,CUR_SOLD,EXT_DATE)
		SELECT
			TRIM(SUKFO_ACC_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKFO_ACC_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKFO_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE,                                   -- 衍生性金融商品
			TRIM(SUKFO_TRADE_ID) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKFO_TRADE_DATE AS TX_DATE,
			TRIM(SUKFO_CPTY_NAME) AS CUSTOMER_NAME,
			TRIM(SUKFO_BANK_SWIFT_ID) AS CUSTOMER_ID,
			TRIM(SUKFO_CPTY_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(SUKFO_OBJECT_CCY) AS CURENCY_COD,
			SUKFO_OBJECT_AMT AS TRAN_AMOUNT,
			SUKFO_OBJECT_AMT AS LIMIT,
			TRIM(SUKFO_OBJECT_CCY) AS LIMIT_COD,
			SUKFO_VALUE_DATE0 AS MATURITY_DATE,
			SUKFO_EXT_DATE AS AS_OF_DATE,
			'ARS_SUKNFO_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKFO_VALUE_DATE0 as LIMIT_MATURITY,
			--TRIM(SUKFO_CPTY_BUSINESS) AS INDUSTRY,
			--1,
			TRIM(SUKFO_TRAN_BUY) AS CUR_BOUGHT,
			TRIM(SUKFO_TRAN_SELL) AS CUR_SOLD,
			@EXT_DATE
		FROM ARS_SUKNFO_D_MF
		WHERE
			SUKFO_EXT_DATE = (select max(SUKFO_EXT_DATE) from ARS_SUKNFO_D_MF WHERE SUKFO_EXT_DATE <= @EXT_DATE) AND
			(SUKFO_VALUE_DATE0 is null or DATEADD(DAY,@BufferDate,SUKFO_VALUE_DATE0) >= @EXT_DATE) AND
			SUKFO_TRAN_TYPE = 'B' AND
			SUKFO_CPTY_NAME <> 'DCD_ONLINE' AND
			SUKFO_PRAM_CCY IS NULL AND
			SUKFO_CPTY_COUNTRY_RISK <> 'TW';
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/16_usp_Souce09_By_ARS_SUKNFX_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKNFX 衍生性商品(NDF及保證金交易)之資料擷取 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKNFX_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,CUR_BOUGHT,CUR_SOLD,EXT_DATE)
		SELECT
			TRIM(SUKFX_BRANCH_NO) AS BRANCH_NO,
			CASE
				WHEN SUBSTRING(SUKFX_CUSTOMER_ID, 2, 1) < 'A' AND SUKFX_TX_TYPE IN('02', '03') THEN '077'
				WHEN SUKFX_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKFX_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
				END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE,
			TRIM(SUKFX_TRAN_NO) AS TRAN_NO,
			CASE WHEN SUBSTRING(SUKFX_CUSTOMER_ID, 2, 1) < 'A' AND SUKFX_TX_TYPE IN('02', '03') THEN '018'
				 ELSE '016' END AS BUSINESS_UNIT,
			SUKFX_TX_DATE AS TX_DATE,
			TRIM(SUKFX_CUST_NAME1) AS CUSTOMER_NAME,
			TRIM(SUKFX_CUSTOMER_ID) AS CUSTOMER_ID,
			TRIM(SUKFX_CPTY_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(SUKFX_OBJECT_CCY) AS CURENCY_COD,
			SUKFX_OBJECT_AMT As TRAN_AMOUNT,
			NULL AS PERMIT_NO,
			SUKFX_OBJECT_AMT AS LIMIT,
			TRIM(SUKFX_OBJECT_CCY) AS LIMIT_COD,
			SUKFX_VALUE_DATE0 AS MATURITY_DATE,
			SUKFX_EXT_DATE AS AS_OF_DATE,
			0 AS REVOLVE_MK,
			'ARS_SUKNFX_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKFX_VALUE_DATE0 as LIMIT_MATURITY,
			--TRIM(SUKFX_CPTY_BUSINESS) AS INDUSTRY,
			--1,
			SUKFX_CUR_BOUGHT AS CUR_BOUGHT,
			SUKFX_CUR_SOLD AS CUR_SOLD,
			@EXT_DATE
		FROM ARS_SUKNFX_D_MF
		WHERE SUKFX_EXT_DATE = (select MAX(SUKFX_EXT_DATE) FROM ARS_SUKNFX_D_MF WHERE SUKFX_EXT_DATE < @EXT_DATE) AND
			  (SUKFX_VALUE_DATE0 is null or DATEADD(DAY,@BufferDate,SUKFX_VALUE_DATE0) >= @EXT_DATE) AND
			  SUKFX_TX_TYPE IN('02', '03', '04', '05') AND
			  SUKFX_CPTY_COUNTRY_RISK <> 'TW';
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/17_usp_Souce09_By_ARS_SUKNIRS_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKNIRS 衍生性商品(IRS及CCS)之資料擷取 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKNIRS_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,PRODUCT_CODE,EXT_DATE)
		SELECT
			TRIM(SUKIRS_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKIRS_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKIRS_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE,
			TRIM(SUKIRS_TRAN_NO) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKIRS_TX_DATE AS TX_DATE,
			TRIM(SUKIRS_CUST_NAME1) AS CUSTOMER_NAME,
			TRIM(SUKIRS_CUSTOMER_ID) AS CUSTOMER_ID,
			TRIM(SUKIRS_CPTY_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(SUKIRS_IN_CCY) AS CURENCY_COD,
			SUKIRS_IN_AMT As TRAN_AMOUNT,
			SUKIRS_IN_AMT AS LIMIT,
			TRIM(SUKIRS_IN_CCY) AS LIMIT_COD,
			SUKIRS_MATURITY AS MATURITY_DATE,
			SUKIRS_EXT_DATE AS AS_OF_DATE,
			'ARS_SUKNIRS_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKIRS_MATURITY as LIMIT_MATURITY,
			--TRIM(SUKIRS_CPTY_BUSINESS) AS INDUSTRY,
			--1,
			CASE TRIM(SUKIRS_TX_TYPE) WHEN '01' THEN 'QS'
			ELSE 'IRS'
			END AS PRODUCT_CODE,
			@EXT_DATE AS EXT_DATE
		FROM ARS_SUKNIRS_D_MF
		WHERE
			SUKIRS_EXT_DATE = (SELECT MAX(SUKIRS_EXT_DATE) FROM ARS_SUKNIRS_D_MF WHERE SUKIRS_EXT_DATE < @EXT_DATE) AND
			(SUKIRS_MATURITY is null or DATEADD(DAY,@BufferDate,SUKIRS_MATURITY) >= @EXT_DATE) AND
			  ISNULL(SUKIRS_DEPOSIT_LINK,'') NOT IN ('SPD','DCD') AND
			SUKIRS_CPTY_COUNTRY_RISK <> 'TW';
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/18_usp_Souce09_By_ARS_SUKNMM_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKNMM 拆款業務之資料擷取 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKNMM_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,EXT_DATE)
		SELECT
			TRIM(SUKMM_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKMM_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKMM_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			CASE TRIM(SUKMM_TRN_TYPE) WHEN '1' THEN '09'   -- 「09拆款」
									  WHEN '3' THEN '04'   -- 「04存同」
				 END AS PRODUCT_TYPE,
			TRIM(SUKMM_TRAN_NO) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKMM_TX_DATE AS TX_DATE,
			TRIM(SUKMM_CUST_NAME1) AS CUSTOMER_NAME,
			TRIM(SUKMM_SWIFT_ID) AS CUSTOMER_ID,
			TRIM(SUKMM_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(SUKMM_CURENCY_COD) AS CURENCY_COD,
			ABS(SUKMM_TRAN_AMOUNT) AS TRAN_AMOUNT,
			NULL AS PERMIT_NO,
			ABS(SUKMM_TRAN_AMOUNT) AS [LIMIT],
			TRIM(SUKMM_CURENCY_COD) AS LIMIT_COD,
			SUKMM_MATURITY_DATE AS MATURITY_DATE,
			SUKMM_EXT_DATE AS AS_OF_DATE,
			1 AS REVOLVE_MK,
			'ARS_SUKNMM_D_MF' AS FIL9,
			'09' AS source,
			'system' AS creator,
			SUKMM_MATURITY_DATE AS LIMIT_MATURITY,
			--TRIM(SUKMM_CPTY_TYPE) AS INDUSTRY,
			--1,
			@EXT_DATE AS EXT_DATE
		FROM ARS_SUKNMM_D_MF
		WHERE
			SUKMM_EXT_DATE = (select max(SUKMM_EXT_DATE) from ARS_SUKNMM_D_MF WHERE SUKMM_EXT_DATE <= @EXT_DATE) AND
			(SUKMM_MATURITY_DATE is null or DATEADD(DAY,@BufferDate,SUKMM_MATURITY_DATE) >= @EXT_DATE) AND
			  
			TRIM(SUKMM_TRN_TYPE) IN ('1','3') AND -- 只抓取正的
			SUKMM_COUNTRY_RISK <> 'TW' AND
			EXISTS (
				SELECT 1
				FROM ARS_SUKNMM_D_MF MF2
				WHERE	MF2.SUKMM_TRN_TYPE = ARS_SUKNMM_D_MF.SUKMM_TRN_TYPE AND -- 只抓取正的
						MF2.SUKMM_COUNTRY_RISK = ARS_SUKNMM_D_MF.SUKMM_COUNTRY_RISK AND
						MF2.SUKMM_EXT_DATE = ARS_SUKNMM_D_MF.SUKMM_EXT_DATE AND
						MF2.SUKMM_MATURITY_DATE = ARS_SUKNMM_D_MF.SUKMM_MATURITY_DATE AND
						LEFT(MF2.SUKMM_SWIFT_ID, 4) = LEFT(SUKMM_SWIFT_ID, 4)
				GROUP BY LEFT(MF2.SUKMM_SWIFT_ID, 4)
				HAVING SUM(ABS(MF2.SUKMM_TRAN_AMOUNT)) > 0)
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/19_usp_Souce09_By_ARS_SUKSWP_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKSWP 之資料擷取 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKSWP_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,PRODUCT_CODE,EXT_DATE)
		SELECT
			TRIM(SUKSWP_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKSWP_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKSWP_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE,
			TRIM(SUKSWP_EXTERNAL_ID) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKSWP_TX_DATE AS TX_DATE,
			TRIM(SUKSWP_CUST_NAME) AS CUSTOMER_NAME,
			TRIM(SUKSWP_CUSTOMER_ID) AS CUSTOMER_ID,
			TRIM(SUKSWP_CPTY_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(SUKSWP_CURRENCY) AS CURENCY_COD,
			SUKSWP_RISK_AMT As TRAN_AMOUNT,
			SUKSWP_RISK_AMT AS LIMIT,
			TRIM(SUKSWP_CURRENCY) AS LIMIT_COD,
			SUKSWP_OPTIONEXPIRYDATE AS MATURITY_DATE,
			SUKSWP_EXT_DATE AS AS_OF_DATE,
			'ARS_SUKSWP_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKSWP_OPTIONEXPIRYDATE as LIMIT_MATURITY,
			--TRIM(SUKSWP_CPTY_BUSINESS) AS INDUSTRY,
			--1,
			'IRO' AS PRODUCT_CODE,
			@EXT_DATE AS EXT_DATE
		FROM ARS_SUKSWP_D_MF
		WHERE SUKSWP_EXT_DATE = (select max(SUKSWP_EXT_DATE) from ARS_SUKSWP_D_MF WHERE SUKSWP_EXT_DATE <= @EXT_DATE) AND
			(SUKSWP_OPTIONEXPIRYDATE is null or DATEADD(DAY,@BufferDate,SUKSWP_OPTIONEXPIRYDATE) >= @EXT_DATE) AND
			SUKSWP_BUY_SELL ='B' AND
			SUKSWP_CPTY_COUNTRY_RISK <> 'TW';
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/20_usp_Souce01_OBBS_By_OS_LNSLMSD_D_MF.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	01OBBS之海外各業務額度資料(MF_OS_LNSLMSD_D_MF) 轉檔，根據分行交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce01_OBBS_By_OS_LNSLMSD_D_MF] @EXT_DATE AS DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		-- Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
		BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
		CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
		PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
		SOURCE, CREATOR, LIMIT_MATURITY,EXT_DATE,TOP_Limit_Amount,TOP_Permit_No,Top_Limit_Cod,TOP_Country_Cod,TOP_Limit_Maturity)
		-- 未動用但仍有效的授信額度
		SELECT
			TRIM(LNSLMSD_BRANCH_NO) AS BRANCH_NO, --分行代號
			'077' AS DIVISION_NO,--處級單位代號
			case Trim(LNSLMSD_LINE_TYPE)
				WHEN 'SL' THEN '01'  -- 聯合貸款
				WHEN 'SG' THEN '12'  -- 保證
			ELSE '02' -- 一般放款
			end AS PRODUCT_TYPE,--產品別
			'' AS TRAN_NO,--交易代號
			'018' AS BUSINESS_UNIT,--事業群代號
			LNSLMSD_BGN_DATE AS TX_DATE,--交易日期
			TRIM(LNSLMSD_CUSTOMER_NAME) AS CUSTOMER_NAME,--客戶姓名
			TRIM(LNSLMSD_CUSTOMER_ID) AS CUSTOMER_ID,--客戶 ID
			TRIM(LNSLMSD_COUNTRY_RISK) AS COUNTRY_COD, --國家別
			TRIM(LNSLMSD_CURRENCY) AS CURENCY_COD,--幣別
			0 AS TRAN_AMOUNT, --交易金額
			TRIM(LNSLMSD_APP_NO) AS PERMIT_NO,--核准編號
			LNSLMSD_APP_AMT AS LIMIT,--核准額度
			TRIM(LNSLMSD_CURRENCY) AS LIMIT_COD,--核准幣別
			LNSLMSD_MATURITY AS MATURITY_DATE, --到期日
			LNSLMSD_DATA_DATE AS AS_OF_DATE, --資料日期
			CASE TRIM(LNSLMSD_CIRCLE)
				WHEN 'Y' THEN 1
			ELSE 0
			END AS REVOLVE_MK,--是否循環
			'OS_LNSLMSD_D_MF' AS FIL9,
			'01' AS source,
			'system' AS creator,
			LNSLMSD_MATURITY AS LIMIT_MATURITY, -- 額度到期日
			--TRIM(a.BUSINS_CODE) AS INDUSTRY,
			--2,--海外
			@EXT_DATE AS DATADATE,
			LNSLMSD_TOP_LINE_APP_AMT,
			LNSLMSD_TOP_LINE_LINE_NO,
			LNSLMSD_TOP_LINE_CCY,
			LNSLMSD_TOP_LINE_CRISK,
			LNSLMSD_TOP_LINE_MATURITY
		FROM OS_LNSLMSD_D_MF a
		Left join OS_LNSMSTD_D_MF b on trim(a.LNSLMSD_BRANCH_NO) = trim(b.LNSMSTD_BRANCH_NO) and
						Trim(a.LNSLMSD_LINE_NO) = trim(b.LNSMSTD_LINE_NO) and
						EXISTS (
							SELECT 1
							FROM (
								SELECT LNSMSTD_BRANCH_NO, MAX(LNSMSTD_EXT_DATE) AS MAX_DATE
								FROM OS_LNSMSTD_D_MF
								WHERE LNSMSTD_EXT_DATE <= @EXT_DATE
								GROUP BY LNSMSTD_BRANCH_NO
							) Latest
							WHERE b.LNSMSTD_BRANCH_NO = Latest.LNSMSTD_BRANCH_NO AND
								  b.LNSMSTD_EXT_DATE = Latest.MAX_DATE
						)
		WHERE EXISTS (
				SELECT 1
				FROM (
					SELECT LNSLMSD_BRANCH_NO, MAX(LNSLMSD_EXT_DATE) AS MAX_DATE
					FROM OS_LNSLMSD_D_MF
					WHERE LNSLMSD_EXT_DATE <= @EXT_DATE
					GROUP BY LNSLMSD_BRANCH_NO
				) Latest
				WHERE a.LNSLMSD_BRANCH_NO = Latest.LNSLMSD_BRANCH_NO AND
						a.LNSLMSD_EXT_DATE = Latest.MAX_DATE
				) AND
				TRIM(LNSLMSD_LINE_TYPE) IN ('SL','LN','SG','IM','OD','BP') AND
				TRIM(ISNULL(LNSLMSD_COUNTRY_RISK,'')) <> 'TW' AND
				LNSLMSD_LINE_NO IS NOT NULL AND 
				(a.LNSLMSD_MATURITY is null or DATEADD(DAY,@BufferDate,a.LNSLMSD_MATURITY) >= @EXT_DATE) and
				b.LNSMSTD_STATUS <> '2' AND
				b.LNSMSTD_LINE_NO IS NULL
				--LOAN:LN;
				--IMPORT:IM;
				--EXPORT:EX;
				--OVERDRAFT:OD;
				--CLEANBILL:CB;
				--GUARANTEE:SG
				--ACCEPTANCE:AC
				--SYNDICATED:SL
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/21_usp_UpdateMonitorDataUnit.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		allen
-- Create date: 20260424
-- Description:	更新指定轉檔日期MonitorData資料
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_UpdateMonitorDataUnit] @EXT_DATE as date
AS
BEGIN
	SET NOCOUNT ON;
    BEGIN TRY
		
		--Declare @EXT_DATE Date = '2026-09-01';
		update m set GROUP_NO =ISNULL(a.GroupCode,m.GROUP_NO) ,
				　	 UNIT_NO = ISNULL(b.UnitCode,m.UNIT_NO) ,
					BRANCH_NO = ISNULL(c.BankCode,m.BRANCH_NO),
					[YEAR] = YEAR(@EXT_DATE),
					[Month] = MONTH(@EXT_DATE),
					[Week] = dbo.ufn_GetWeekOfMonth(@EXT_DATE)
		from MONITORDATA_STAGE m
		left join BankGroup a on left(dbo.ufn_CodePrefix(a.GroupCode),3) = m.GROUP_NO
		left join BankUnit b  on left(dbo.ufn_CodePrefix(b.UnitCode),3) = m.UNIT_NO
		left join BankBranch c on left(dbo.ufn_CodePrefix(c.BankCode),3) = m.BRANCH_NO AND
								 left(dbo.ufn_CodePrefix(b.UnitCode),3) = m.UNIT_NO AND
								b.PK_Id = c.FK_BankUnit
		where m.EXT_DATE = @EXT_DATE
	END TRY
    BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
        THROW;
    END CATCH
END
GO

-- ---------- 02_StoredProcedure/22_usp_UpdateMonitorDataCNWeights.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Allen
-- Create date: 20250923
-- Description:	將指定轉入日期的MonitorData Update WEIGHTS 中國權重
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_UpdateMonitorDataCNWeights](@EXT_DATE AS DATE)
AS
BEGIN
	SET NOCOUNT ON;
    BEGIN TRY
		-- 指定客戶名稱，且中國交易國的中國權重為0
		-- 建立表格變數存放要排除的客戶
		DECLARE @ExcludedCustomers TABLE (
			CustomerName NVARCHAR(255)
		);
		-- 插入要排除的客戶名稱
		INSERT INTO @ExcludedCustomers (CustomerName) VALUES
			('BOC_CNT'),
			('CCB_TPDBU'),
			('BKCOMM_TPE'),
			('BOC_TPE_DBU'),
			('BANK OF CHINA LTD. TAIPEI'),
			('CHINA CONSTRUCTION BK CORP. TAIPEI'),
			('BANK OF COMMUNICATIONS, TAIPEI'),
			('BANK OF CHINA LIMITED TAIPEI BRANCH');
		-- 中國風險加權計算方式
		-- 1. 指定客戶 為 0
		-- 2. 產品別 04、09 且到期日天數 小於 92 為 20（其他產品別不適用短天期減權）
		-- 3. 其餘 100
		UPDATE M SET WEIGHTS = CASE WHEN EXISTS (
											SELECT 1
											FROM @ExcludedCustomers e
											WHERE e.CustomerName = M.CUSTOMER_NAME
										) THEN '0'
									WHEN M.PRODUCT_TYPE IN ('04','09')
										 AND DATEDIFF(DAY,@EXT_DATE,M.MATURITY_DATE) < 92 THEN 20
									ELSE 100 END
		FROM MONITORDATA_STAGE M
		WHERE M.EXT_DATE = @EXT_DATE AND COUNTRY_COD = 'CN'
	END TRY
    BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
        THROW;
    END CATCH
END
GO

-- ---------- 02_StoredProcedure/23_usp_UpdateMonitorDataPruduct07RiskFactor.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Allen
-- Create date: 20250923
-- Description:	將MonitorData指定轉入日期 and 產品類別為 07 衍伸性金融商品
--				根據到期日與轉檔日得出剩餘天數 與 風險類型 取得風險係數，Update 交易額度與核准額度
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_UpdateMonitorDataPruduct07RiskFactor](@EXT_DATE AS DATE)
AS
BEGIN
	SET NOCOUNT ON;
    BEGIN TRY
		UPDATE MONITORDATA_STAGE
		SET RISKFACTOR = dbo.ufn_FinancialRiskFactor(DATEDIFF(DAY, @EXT_DATE, MATURITY_DATE),
			PRODUCT_CODE,CUR_BOUGHT,CUR_SOLD)
		WHERE EXT_DATE = @EXT_DATE AND PRODUCT_TYPE = '07';
	END TRY
    BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
        THROW;
    END CATCH
END
--SELECT
--	pm.FK_GlobalID_FinancialProductCategory,
--    G.Name_TN,
--    PM.ProductTypeName,
--    PM.ProductCode,
--	RFD.FK_ProductID,
--	RFD.FK_PeriodID,
--    PD.PeriodName,
--    PD.MinDays,
--    PD.MaxDays,
--    RFD.RiskFactor
--FROM FinancialRiskFactorData RFD
--INNER JOIN FinancialProductMaster PM ON RFD.FK_ProductID = PM.PK_ID
--INNER JOIN Global G ON PM.FK_GlobalID_FinancialProductCategory = G.Id
--INNER JOIN FinancialRiskFactorPeriodDay PD ON RFD.FK_PeriodID = PD.PK_ID
----ORDER BY PM.PK_ID

--SELECT
--    G.Name_TN AS ProductCategory,
--    PM.ProductTypeName,
--    PM.ProductCode,
--    [1] AS 'Days_2',
--    [2] AS 'Days_7',
--    [3] AS 'Days_30',
--    [4] AS 'Days_31_60',
--    [5] AS 'Days_61_91',
--    [6] AS 'Days_92_182',
--    [7] AS 'Days_183_270',
--    [8] AS 'Days_271_365',
--    [9] AS 'Days_366_456',
--    [10] AS 'Days_457_547',
--    [11] AS 'Days_548_635',
--    [12] AS 'Days_636_730',
--    [13] AS 'Days_731_1095',
--    [14] AS 'Days_1096_1825',
--    [15] AS 'Days_1826_2555',
--    [16] AS 'Days_2556_3650',
--    [17] AS 'Days_3651_5475',
--    [18] AS 'Days_5476_7300',
--    [19] AS 'Days_7301_9131',
--    [20] AS 'Days_9132_10958'
--FROM (
--    SELECT
--        G.Name_TN,
--        PM.ProductTypeName,
--        PM.ProductCode,
--        PM.PK_ID,
--        RFD.FK_PeriodID,
--        RFD.RiskFactor
--    FROM FinancialRiskFactorData RFD
--    INNER JOIN FinancialProductMaster PM ON RFD.FK_ProductID = PM.PK_ID
--    INNER JOIN Global G ON PM.FK_GlobalID_FinancialProductCategory = G.Id
--) AS SourceTable
--PIVOT (
--    MAX(RiskFactor)
--    FOR FK_PeriodID IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18],[19],[20])
--) AS PivotTable
--INNER JOIN FinancialProductMaster PM ON PivotTable.PK_ID = PM.PK_ID
--INNER JOIN Global G ON PM.FK_GlobalID_FinancialProductCategory = G.Id
--ORDER BY PM.PK_ID;
GO

-- ---------- 02_StoredProcedure/24_usp_UpdateMonitorDataFPEXR_RateUSD.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Allen
-- Create date: 20250916
-- Description:	將指定轉入日期的MonitorData Update 交易金額(美金)核准金額(美金)與交易匯率更新
-- Modify:		新增 TRAN_FXRATE／LIMIT_FXRATE 落地保存實際套用的匯率，供追溯與後續計算使用
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_UpdateMonitorDataFPEXR_RateUSD](@EXT_DATE AS DATE)
AS
BEGIN
	SET NOCOUNT ON;
    BEGIN TRY
		-- 交易金額(美金)與交易匯率更新
		--非柬埔寨幣使用FPEXR_STG(FPEXR_STG是台幣匯率檔，要再除一次美金)
		-- 柬埔寨幣用ACOLRT_STG 匯率檔

		-- Declare @EXT_DATE Date = '2026-09-01';
		UPDATE M
		SET
			TRAN_FXRATE = CASE
				WHEN M.CURENCY_COD = 'KHR' THEN ACO_TRAN.ACOLRT_RATE
				WHEN M.CURENCY_COD = 'TWD' THEN 1 / FPE2_TRAN.FPEXR_RATE
				ELSE FPE_TRAN.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
			END,
			TO_USD_AMT = CASE
				WHEN M.CURENCY_COD = 'KHR' THEN M.TRAN_AMOUNT * ACO_TRAN.ACOLRT_RATE
				WHEN M.CURENCY_COD = 'TWD' THEN M.TRAN_AMOUNT / FPE2_TRAN.FPEXR_RATE
				ELSE M.TRAN_AMOUNT * FPE_TRAN.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
			END,
			LIMIT_FXRATE = CASE
				WHEN M.LIMIT_COD = 'KHR' THEN ACO_TRAN.ACOLRT_RATE
				WHEN M.LIMIT_COD = 'TWD' THEN 1 / FPE2_TRAN.FPEXR_RATE
				WHEN M.LIMIT_COD IS NULL THEN  -- 如果沒有額度幣別，使用交易幣別
					CASE
						WHEN M.CURENCY_COD = 'KHR' THEN ACO_TRAN.ACOLRT_RATE
						ELSE FPE_TRAN.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
					END
				ELSE FPE_LIMIT.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
			END,
			TO_USD_LIMIT = CASE
				WHEN M.LIMIT_COD = 'KHR' THEN M.LIMIT * ACO_TRAN.ACOLRT_RATE
				WHEN M.LIMIT_COD = 'TWD' THEN M.LIMIT / FPE2_TRAN.FPEXR_RATE
				WHEN M.LIMIT_COD IS NULL THEN  -- 如果沒有額度幣別，使用交易幣別
					CASE
						WHEN M.CURENCY_COD = 'KHR' THEN M.LIMIT * ACO_TRAN.ACOLRT_RATE
						ELSE M.LIMIT * FPE_TRAN.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
					END
				ELSE M.LIMIT * FPE_LIMIT.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
			END,
			TOP_Limit_USD_Amount = CASE
				WHEN M.TOP_Limit_Cod = 'KHR' THEN M.TOP_Limit_Amount * ACO_TRAN.ACOLRT_RATE
				WHEN M.TOP_Limit_Cod = 'TWD' THEN M.TOP_Limit_Amount / FPE2_TRAN.FPEXR_RATE
				ELSE M.TOP_Limit_Amount * FPE_TOP_LIMIT.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
				END
		FROM MONITORDATA_STAGE M
		-- 匯率檔美金
		LEFT JOIN FPEXR_STG FPE2_TRAN ON FPE2_TRAN.FPEXR_CRCY_CODE = '01' 
			AND FPE2_TRAN.FPEXR_DATE =  M.EXT_DATE
		-- 匯率檔2 柬埔寨 對 美金
		LEFT JOIN ACOLRT_STG ACO_TRAN ON ACO_TRAN.ACOLRT_DATE = M.EXT_DATE 
			AND ACO_TRAN.ACOLRT_LOCAL_CURENCY = '01' AND ACOLRT_CURENCY = '91'

		-- 交易幣別代號 JOIN
		LEFT JOIN MIS_CRCY_REF CRCY_TRAN ON CRCY_TRAN.CRCY_ENG_NAME = M.CURENCY_COD
		-- 匯率檔JOIN
		LEFT JOIN FPEXR_STG FPE_TRAN ON CRCY_TRAN.CRCY_CODE = FPE_TRAN.FPEXR_CRCY_CODE
			AND FPE_TRAN.FPEXR_DATE = M.EXT_DATE 

		-- 核准額度幣別相關JOIN（僅當額度幣別存在且不同於交易幣別時）
		LEFT JOIN MIS_CRCY_REF CRCY_LIMIT ON CRCY_LIMIT.CRCY_ENG_NAME = M.LIMIT_COD AND M.LIMIT_COD IS NOT NULL
		LEFT JOIN FPEXR_STG FPE_LIMIT ON CRCY_LIMIT.CRCY_CODE = FPE_LIMIT.FPEXR_CRCY_CODE
			AND FPE_LIMIT.FPEXR_DATE = M.EXT_DATE

		-- 根核准額度幣別相關JOIN（僅當額度幣別存在且不同於交易幣別時）
		LEFT JOIN MIS_CRCY_REF CRCY_TOP_Limit ON CRCY_TOP_Limit.CRCY_ENG_NAME = M.TOP_Limit_Cod AND M.TOP_Limit_Cod IS NOT NULL
		LEFT JOIN FPEXR_STG FPE_TOP_LIMIT ON CRCY_TOP_Limit.CRCY_CODE = FPE_TOP_LIMIT.FPEXR_CRCY_CODE
			AND FPE_TOP_LIMIT.FPEXR_DATE = M.EXT_DATE
		WHERE M.EXT_DATE = @EXT_DATE
	END TRY
    BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
        THROW;
    END CATCH
END
GO

-- ---------- 02_StoredProcedure/25_usp_UpdateMonitorDataCalculatedUsdAmount.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Create date: 20260807
-- Description:	依 WEIGHTS（usp_UpdateMonitorDataCNWeights）與 RISKFACTOR
--   （usp_UpdateMonitorDataPruduct07RiskFactor）套用後的計算後美金金額，
--   落地至 CAL_TO_USD_AMT／CAL_TO_USD_LIMIT。
-- 執行順序：必須排在 usp_UpdateMonitorDataFPEXR_RateUSD、
--   usp_UpdateMonitorDataCNWeights、usp_UpdateMonitorDataPruduct07RiskFactor 之後執行。
-- TODO：CAL_TO_USD_AMT／CAL_TO_USD_LIMIT 的實際計算公式待補（依 WEIGHTS/RISKFACTOR
--   套用規則），目前僅建立 SP 骨架與欄位落地位置，SET 子句先寫成 no-op。
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_UpdateMonitorDataCalculatedUsdAmount](@EXT_DATE AS DATE)
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		UPDATE M
		SET
			-- TODO: 套用 WEIGHTS/RISKFACTOR 的計算公式，例如：
			CAL_TO_USD_AMT = isnull(M.TO_USD_AMT,0)  * (isnull(M.RISKFACTOR,100)/100),
			-- TODO: 套用 WEIGHTS/RISKFACTOR 的計算公式
			CAL_TO_USD_LIMIT = isnull(M.TO_USD_LIMIT,0) * (isnull(M.RISKFACTOR,100)/100)
		FROM MONITORDATA_STAGE M
		WHERE M.EXT_DATE = @EXT_DATE;
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
		PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH
END
GO




-- ---------- 02_StoredProcedure/26_usp_UpdateMonitorDataLimit.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		allen
-- Create date: 20260424
-- Description:	更新指定轉檔日期MonitorData資料
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_UpdateMonitorDataLimit] @EXT_DATE as date
AS
BEGIN
	SET NOCOUNT ON;
    BEGIN TRY
		update m set CAL_TO_USD_LIMIT = CAL_TO_USD_AMT
		from MONITORDATA_STAGE m
		where m.EXT_DATE = @EXT_DATE AND LIMIT_MATURITY <= @EXT_DATE
	END TRY
    BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
        THROW;
    END CATCH
END
GO

-- ---------- 02_StoredProcedure/27_usp_UpdateMonitorDataIndustry.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2026/09/07
-- Description:	Update MonitorData 行業別更新

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_UpdateMonitorDataIndustry] @EXT_DATE AS DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		
		update a set INDUSTRY = right(ISNULL(b.INDCODE,c.INDCODE),6) ,
		INDUSTRY_Type = case when b.INDCODE is not null then 2
						     when c.INDCODE is not null then 1
							 else null
						end
		from MONITORDATA_STAGE a
		left join INDUSTRY_Overseas b on b.BranchCode = left(dbo.ufn_CodePrefix(a.BRANCH_NO),3) and b.CustomerId = a.CUSTOMER_ID
		left join INDUSTRY_Internal c on c.CustomerId = a.CUSTOMER_ID
		where EXT_DATE = @EXT_DATE
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO



-- ---------- 02_StoredProcedure/28_usp_TransferData.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	轉檔流程呼叫入口
--   2026/09/16 改為寫入 MONITORDATA_STAGE（暫存表），正式表 MONITORDATA 由
--              usp_MonitorData_Publish 在所有來源都完成後以短交易一次換入，
--              避免長時間鎖住正式表影響前端查詢。
--   參數：
--     @EXT_DATE        轉檔日期
--     @RetentionDays   STAGE 保留天數；開頭會清掉 EXT_DATE 早於 (@EXT_DATE - @RetentionDays) 的暫存資料，
--                      預設 7 天，留幾天供事後對照，避免暫存表無限長大
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_TransferData]
	@EXT_DATE AS DATE,
	@RetentionDays INT = 7
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		IF @EXT_DATE IS NULL
			THROW 50000, '@EXT_DATE 為空值', 1;
		IF @RetentionDays IS NULL OR @RetentionDays < 0
			SET @RetentionDays = 7;

		-- 清掉本次日期在暫存表的舊資料（重跑時不會累積），以及超過保留天數的歷史暫存資料
		DELETE MONITORDATA_STAGE
		WHERE EXT_DATE = @EXT_DATE
		   OR EXT_DATE < DATEADD(DAY, -@RetentionDays, @EXT_DATE);

		-- DW 資料轉檔（以下 SP 皆寫入 MONITORDATA_STAGE）
		exec usp_Souce01_OBBS_By_OS_LNSMSTD_D_MF @EXT_DATE -- 交易檔
		exec usp_Souce01_OBBS_By_OSBDKF02_MF @EXT_DATE -- 交易檔
		exec usp_Souce01_OBBS_By_OSFXKF02_MF @EXT_DATE -- 交易檔
		exec usp_Souce01_OBBS_By_OSISKF02_MF @EXT_DATE -- 交易檔
		exec usp_Souce01_OBBS_By_OSMMKF02_MF @EXT_DATE -- 交易檔
		exec usp_Souce04_By_LS_LSRSA_D_MF @EXT_DATE  -- 交易檔
		exec usp_Souce06_By_FL_FLMST_D_MF @EXT_DATE  -- 交易檔
		exec usp_Souce09_By_ARS_SUKBD2_D_MF @EXT_DATE -- 交易檔
		exec usp_Souce09_By_ARS_SUKBDO_D_MF @EXT_DATE -- 交易檔
		exec usp_Souce09_By_ARS_SUKFRA_D_MF @EXT_DATE -- 交易檔
		exec usp_Souce09_By_ARS_SUKIRO_D_MF @EXT_DATE -- 交易檔
		exec usp_Souce09_By_ARS_SUKMST_D_MF @EXT_DATE -- 交易檔
		exec usp_Souce09_By_ARS_SUKNBD1_D_MF @EXT_DATE -- 交易檔
		exec usp_Souce09_By_ARS_SUKNFO_D_MF @EXT_DATE -- 交易檔
		exec usp_Souce09_By_ARS_SUKNFX_D_MF @EXT_DATE -- 交易檔
		exec usp_Souce09_By_ARS_SUKNIRS_D_MF @EXT_DATE -- 交易檔
		exec usp_Souce09_By_ARS_SUKNMM_D_MF @EXT_DATE -- 交易檔
		exec usp_Souce09_By_ARS_SUKSWP_D_MF @EXT_DATE -- 交易檔
		exec usp_Souce01_OBBS_By_OS_LNSLMSD_D_MF @EXT_DATE -- 額度檔
		exec usp_Souce06_By_FM_FMLINE_D_MF @EXT_DATE  -- 額度檔

	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO

-- ---------- 02_StoredProcedure/29_usp_MonitorData_Publish.sql ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		System
-- Create date: 2026/09/16
-- Description:	把 MONITORDATA_STAGE 內指定日期（可再限定來源）的資料換入正式表 MONITORDATA。
--   整個換入動作在一個短交易內完成：DELETE 正式表該範圍 → INSERT…SELECT 自暫存表，
--   正式表只在這幾秒被鎖，前端查詢不再被整段轉檔（數分鐘）擋住。
--   欄位清單由 sys.columns 動態取「兩表共有、且非 IDENTITY」的欄位，
--   正式表日後加欄位時只要暫存表也加了，本 SP 不用改；暫存表漏加則直接報錯。
--
--   參數：
--     @EXT_DATE   要換入的轉檔日期（必填）
--     @SOURCES    逗號分隔的 SOURCE 清單，例如 '10,12,13,14,18'；NULL = 該日期全部來源
--     @FIL9       再以 FIL9 限定（Source11 的 RiskLineD／RiskLineO 共用 SOURCE=11，靠 FIL9 區分）；NULL = 不限定
--   回傳一列：DeletedCount（正式表刪除筆數）、InsertedCount（自暫存表插入筆數）
--
--   注意：本 SP 不檢查該日期在正式表是否已有 Mark／Lock 或簽核中資料，重新換入會以暫存表內容為準
--        （Mark／Lock 歸零）。簽核中表單由呼叫端（TransferDataAPI）在呼叫前自動作廢。
--
--   WITH EXECUTE AS OWNER：DELETE／INSERT 是以 sp_executesql 動態執行，動態 SQL 不適用擁有權鏈，
--   若以呼叫者身分執行，程式帳號需要直接持有 MONITORDATA 的 DELETE／INSERT 權限；
--   改以 SP 擁有者（dbo）身分執行，程式帳號只需要 EXECUTE 本 SP。
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_MonitorData_Publish]
	@EXT_DATE DATE,
	@SOURCES NVARCHAR(MAX) = NULL,
	@FIL9 NVARCHAR(100) = NULL
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;
	SET XACT_ABORT ON;

	IF @EXT_DATE IS NULL
		THROW 50000, N'@EXT_DATE 為空值', 1;

	-- 1. 解析 @SOURCES 成字串常值清單 N'10', N'12', ...（不依賴 STRING_SPLIT，任何版本都能跑）
	DECLARE @SourceLiteral NVARCHAR(MAX) = NULL;
	IF @SOURCES IS NOT NULL AND LTRIM(RTRIM(@SOURCES)) <> N''
	BEGIN
		DECLARE @SourceList TABLE ([SOURCE] NVARCHAR(100) NOT NULL PRIMARY KEY);
		DECLARE @Remain NVARCHAR(MAX) = @SOURCES + N',';
		DECLARE @Pos INT = CHARINDEX(N',', @Remain);
		WHILE @Pos > 0
		BEGIN
			DECLARE @Item NVARCHAR(100) = LTRIM(RTRIM(SUBSTRING(@Remain, 1, @Pos - 1)));
			IF @Item <> N'' AND NOT EXISTS (SELECT 1 FROM @SourceList WHERE [SOURCE] = @Item)
				INSERT INTO @SourceList ([SOURCE]) VALUES (@Item);
			SET @Remain = SUBSTRING(@Remain, @Pos + 1, LEN(@Remain));
			SET @Pos = CHARINDEX(N',', @Remain);
		END
		IF NOT EXISTS (SELECT 1 FROM @SourceList)
		BEGIN
			-- 前一個陳述式是 WHILE 的 END，沒有分號，THROW 前要補一個
			;THROW 50001, N'@SOURCES 解析後沒有任何有效來源', 1;
		END

		SET @SourceLiteral = (
			SELECT STUFF((
				SELECT N', N''' + REPLACE([SOURCE], N'''', N'''''') + N''''
				FROM @SourceList
				ORDER BY [SOURCE]
				FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 2, N''));
	END

	-- 2. 正式表有而暫存表沒有的欄位視為部署不完整，直接擋下
	DECLARE @MissingInStage NVARCHAR(MAX) = (
		SELECT STUFF((
			SELECT N', ' + m.name
			FROM sys.columns m
			WHERE m.object_id = OBJECT_ID(N'[dbo].[MONITORDATA]')
			  AND m.is_identity = 0
			  AND NOT EXISTS (
				SELECT 1 FROM sys.columns s
				WHERE s.object_id = OBJECT_ID(N'[dbo].[MONITORDATA_STAGE]') AND s.name = m.name)
			FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 2, N''));
	IF @MissingInStage IS NOT NULL
	BEGIN
		DECLARE @MissingMsg NVARCHAR(4000) = N'MONITORDATA_STAGE 缺少欄位：' + @MissingInStage + N'，無法發佈。';
		THROW 50002, @MissingMsg, 1;
	END

	-- 3. 兩表共有、非 IDENTITY 的欄位清單，依正式表欄位順序
	DECLARE @Columns NVARCHAR(MAX) = (
		SELECT STUFF((
			SELECT N', ' + QUOTENAME(m.name)
			FROM sys.columns m
			INNER JOIN sys.columns s
				ON s.object_id = OBJECT_ID(N'[dbo].[MONITORDATA_STAGE]') AND s.name = m.name
			WHERE m.object_id = OBJECT_ID(N'[dbo].[MONITORDATA]')
			  AND m.is_identity = 0
			ORDER BY m.column_id
			FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 2, N''));
	IF @Columns IS NULL
		THROW 50003, N'找不到可發佈的欄位', 1;

	-- 4. 篩選條件兩邊共用，確保刪與插的範圍一致
	DECLARE @Where NVARCHAR(MAX) = N' WHERE [EXT_DATE] = @EXT_DATE';
	IF @SourceLiteral IS NOT NULL
		SET @Where += N' AND [SOURCE] IN (' + @SourceLiteral + N')';
	IF @FIL9 IS NOT NULL
		SET @Where += N' AND [FIL9] = @FIL9';

	DECLARE @DeleteSql NVARCHAR(MAX) =
		N'DELETE [dbo].[MONITORDATA]' + @Where + N'; SET @Affected = @@ROWCOUNT;';
	DECLARE @InsertSql NVARCHAR(MAX) =
		N'INSERT INTO [dbo].[MONITORDATA] (' + @Columns + N') ' +
		N'SELECT ' + @Columns + N' FROM [dbo].[MONITORDATA_STAGE]' + @Where + N'; SET @Affected = @@ROWCOUNT;';
	DECLARE @Params NVARCHAR(200) = N'@EXT_DATE DATE, @FIL9 NVARCHAR(100), @Affected INT OUTPUT';

	DECLARE @DeletedCount INT = 0, @InsertedCount INT = 0;

	-- 5. 整日發佈時暫存表若一筆都沒有，代表上游（DW／各來源）根本沒產出，不能把正式表既有的那一天清掉；
	--    限定來源的單跑則允許 0 筆（該來源當天確實沒資料時，正確狀態就是 0 筆）。
	IF @SourceLiteral IS NULL AND @FIL9 IS NULL
	   AND NOT EXISTS (SELECT 1 FROM [dbo].[MONITORDATA_STAGE] WHERE [EXT_DATE] = @EXT_DATE)
	BEGIN
		DECLARE @EmptyMsg NVARCHAR(4000) = N'MONITORDATA_STAGE 沒有 ' + CONVERT(NVARCHAR(10), @EXT_DATE, 120) + N' 的任何資料，拒絕發佈以免清空正式表該日資料。';
		THROW 50004, @EmptyMsg, 1;
	END

	-- 6. 短交易換入
	BEGIN TRY
		BEGIN TRANSACTION;

		EXEC sys.sp_executesql @DeleteSql, @Params,
			@EXT_DATE = @EXT_DATE, @FIL9 = @FIL9, @Affected = @DeletedCount OUTPUT;

		EXEC sys.sp_executesql @InsertSql, @Params,
			@EXT_DATE = @EXT_DATE, @FIL9 = @FIL9, @Affected = @InsertedCount OUTPUT;

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF XACT_STATE() <> 0
			ROLLBACK TRANSACTION;
		DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
		PRINT '發佈 MONITORDATA 發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

	SELECT @DeletedCount AS DeletedCount, @InsertedCount AS InsertedCount;
END
GO

-- ---------- 03_Drop/Drop_Unused_Source_Procedures.sql ----------
-- =============================================
-- 移除已不再被 usp_TransferData 呼叫、仍直接寫正式表 MONITORDATA 的舊來源 SP，
-- 避免日後誤呼叫繞過暫存表流程。可重複執行。
--   usp_Souce01_OBBS_By_OS_LNSMSTD_D_MF_OS_LNSLMSD_D_MF：已拆成 LNSMSTD／LNSLMSD 兩支
--   usp_Souce04_By_LS_LSRSA_D_MF_ACNOD_STG：ACNOD_STG 合併改由 C# 端處理，改呼叫 usp_Souce04_By_LS_LSRSA_D_MF
-- =============================================
DROP PROCEDURE IF EXISTS [dbo].[usp_Souce01_OBBS_By_OS_LNSMSTD_D_MF_OS_LNSLMSD_D_MF];
GO
DROP PROCEDURE IF EXISTS [dbo].[usp_Souce04_By_LS_LSRSA_D_MF_ACNOD_STG];
GO

