SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	01OBBS之海外各業務交易資料(OS_LNSMSTD_D_MF) 轉檔，根據分行交易最大日期 交易檔

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce01_OBBS_By_OS_LNSMSTD_D_MF] @EXT_DATE AS DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL
			DROP TABLE #TEMP;

		SELECT DISTINCT Trim(LNSMSTD_BRANCH_NO) AS BRANCH_NO,
		'077' AS Unit_NO,--處級單位代號
		case Trim(LNSMSTD_TX_TYPE)
			WHEN 'SL' THEN '01'  -- 聯合貸款
			WHEN 'GU' THEN '12'  -- 保證
			WHEN 'E3' THEN '03'  -- 保兌
			--WHEN 'E5' THEN '10'  -- 應收帳款承購 --賢欽 2025/11/13 說不用
		ELSE '02' -- 一般放款
		end AS PRODUCT_TYPE,--產品別
		Trim(LNSMSTD_TX_NO) AS TRAN_NO,--交易代號
		'018' AS Group_NO, --事業群代號 海外分行只有海外事業群 所以018
		cast(LNSMSTD_BEGIN_DATE as date) AS TX_DATE, --原始初貸日 = 交易日期
		Trim(LNSLMSD_CUSTOMER_NAME) AS CUSTOMER_NAME, --客戶姓名 -- 空要抓 c100 ，依據跟客戶ID 分行
		Trim(LNSMSTD_CUSTOMER_ID) AS CUSTOMER_ID, -- 客戶ID
		Trim(Isnull(LNSLMSD_COUNTRY_RISK,Isnull(LNSLMSD_REG_COUNTRY,''))) AS COUNTRY_COD,--交易國家 空 要抓c100
		Trim(LNSMSTD_CURRENCY) AS CURENCY_COD, --幣別
		LNSMSTD_BALANCE AS TRAN_AMOUNT, -- 交易金額
		Trim(LNSLMSD_APP_NO) AS PERMIT_NO,--核准編號
		ISNULL(LNSLMSD_APP_AMT,LNSMSTD_BALANCE) AS LIMIT,--核准額度  空 抓 交易金額
		ISNULL(Trim(LNSLMSD_CURRENCY),LNSMSTD_CURRENCY) AS LIMIT_COD, --核准幣別 空 抓交易幣別
		LEFT(LNSMSTD_MATURITY, 8) AS MATURITY_DATE,--到期日
		LNSMSTD_DATA_DATE AS AS_OF_DATE,--資料日期
		CASE TRIM(Isnull(LNSLMSD_CIRCLE,'')) WHEN 'Y' THEN 1 ELSE 0 END AS REVOLVE_MK,--是否循環 空 為 0
		'OS_LNSMSTD_D_MF' AS FIL9,-- 行業別主檔 只有授信產品
		'01' AS source,
		'system' AS creator,
		LNSMSTD_ACC_CODE_INT_9, -- 判斷是否為利息
		LNSMSTD_ACCRUE_INT,--利息
		LNSLMSD_MATURITY AS LIMIT_MATURITY, --額度到期日 空 可能要無限大
		--TRIM(LNSM.BUSINS_CODE) AS INDUSTRY, -- 行業別主檔 只有授信產品
		--2 AS INDUSTRY_TYPE, --海外
		@EXT_DATE as EXT_DATE,
		LNSL.LNSLMSD_TOP_LINE_APP_AMT,
		LNSL.LNSLMSD_TOP_LINE_LINE_NO,
		LNSL.LNSLMSD_TOP_LINE_CCY,
		LNSL.LNSLMSD_TOP_LINE_CRISK,
		LNSL.LNSLMSD_TOP_LINE_MATURITY
		INTO #TEMP
		FROM OS_LNSMSTD_D_MF LNSM --海外分行授信業務交易主檔
		LEFT JOIN OS_LNSLMSD_D_MF LNSL ON --海外分行額度檔
			LNSMSTD_LINE_NO = LNSLMSD_LINE_NO AND -- 額度號碼
			LNSMSTD_BRANCH_NO = LNSLMSD_BRANCH_NO AND -- 分行編號
			EXISTS (
				SELECT 1
				FROM (
					SELECT LNSLMSD_BRANCH_NO, MAX(LNSLMSD_EXT_DATE) AS MAX_DATE
					FROM OS_LNSLMSD_D_MF
					WHERE LNSLMSD_EXT_DATE <= @EXT_DATE
					GROUP BY LNSLMSD_BRANCH_NO
				) Latest
				WHERE LNSL.LNSLMSD_BRANCH_NO = Latest.LNSLMSD_BRANCH_NO
				AND LNSL.LNSLMSD_EXT_DATE = Latest.MAX_DATE
			)
		WHERE
			 --到期且餘額 = 0 排除
		 -- 取到期日要大於轉檔日的資料，除了催收，催收項目為 LNSMSTD_ACC_CODE_INT_9 IN ('135850003','135850004')，催收的項目會超過到期日
		NOT (LNSMSTD_BALANCE = 0 AND ( LNSLMSD_MATURITY IS NULL OR LNSLMSD_MATURITY < LNSMSTD_EXT_DATE) and LNSMSTD_ACC_CODE_INT_9 not in ('135850003','135850004')) AND
		TRIM(LNSLMSD_COUNTRY_RISK) <> 'TW' AND -- 排除台灣
				EXISTS (
					SELECT 1
					FROM (
						SELECT LNSMSTD_BRANCH_NO, MAX(LNSMSTD_EXT_DATE) AS MAX_DATE
						FROM OS_LNSMSTD_D_MF
						WHERE LNSMSTD_EXT_DATE <= @EXT_DATE
						GROUP BY LNSMSTD_BRANCH_NO
					) Latest
					WHERE LNSM.LNSMSTD_BRANCH_NO = Latest.LNSMSTD_BRANCH_NO
					AND LNSM.LNSMSTD_EXT_DATE = Latest.MAX_DATE
				) AND
			TRIM(lnsmstd_status) <> '2'  -- 排除呆帳

		INSERT INTO MONITORDATA_STAGE (
		BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
		CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
		PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
		SOURCE, CREATOR, LIMIT_MATURITY,EXT_DATE,TOP_Limit_Amount,TOP_Permit_No,TOP_Limit_Cod,TOP_Country_Cod,TOP_Limit_Maturity)
		SELECT BRANCH_NO,Unit_NO,PRODUCT_TYPE,TRAN_NO,Group_NO,TX_DATE,CUSTOMER_NAME,
				CUSTOMER_ID,COUNTRY_COD,CURENCY_COD,TRAN_AMOUNT,PERMIT_NO,LIMIT,LIMIT_COD,MATURITY_DATE,AS_OF_DATE,REVOLVE_MK,FIL9,
				source,creator,LIMIT_MATURITY,EXT_DATE,LNSLMSD_TOP_LINE_APP_AMT,LNSLMSD_TOP_LINE_LINE_NO,LNSLMSD_TOP_LINE_CCY,
				LNSLMSD_TOP_LINE_CRISK,LNSLMSD_TOP_LINE_MATURITY
		From #TEMP
		UNION
		-- 利息要再加上去 LNSMSTD_ACC_CODE_INT_9 in ('135850003','135850004') and LNSMSTD_ACCRUE_INT <> 0
			SELECT BRANCH_NO,Unit_NO,PRODUCT_TYPE,TRAN_NO,Group_NO,TX_DATE,CUSTOMER_NAME,
				CUSTOMER_ID,COUNTRY_COD,CURENCY_COD,LNSMSTD_ACCRUE_INT,PERMIT_NO,LIMIT,
				LIMIT_COD,MATURITY_DATE,AS_OF_DATE,REVOLVE_MK,FIL9 + '_Interest',
				source,creator,LIMIT_MATURITY,EXT_DATE,LNSLMSD_TOP_LINE_APP_AMT,LNSLMSD_TOP_LINE_LINE_NO,LNSLMSD_TOP_LINE_CCY,
				LNSLMSD_TOP_LINE_CRISK,LNSLMSD_TOP_LINE_MATURITY
			From #TEMP
			WHERE LNSMSTD_ACC_CODE_INT_9 in ('135850003','135850004') and LNSMSTD_ACCRUE_INT <> 0
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
