SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	01OBBS延伸性金融商品FXSWAP(OSFXKF02_MF) 轉檔，根據分行交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce01_OBBS_By_OSFXKF02_MF] @EXT_DATE AS DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

	--Declare @EXT_DATE Date = '2026-09-01';
	Declare @BufferDate INT = 14;
	INSERT INTO MONITORDATA_STAGE (
		BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
		CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
		LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, FIL9,
		SOURCE, CREATOR, LIMIT_MATURITY,CUR_BOUGHT,CUR_SOLD,EXT_DATE)
	SELECT
		TRIM(OSFXKF02_BRANCH_NO) AS BRANCH_NO,
		'077' AS DIVISION_NO,
		'07' AS PRODUCT_TYPE,
		TRIM(OSFXKF02_TRAN_NO) AS TRAN_NO,
		'018' AS BUSINESS_UNIT,
		OSFXKF02_DEL_DATE AS TX_DATE,
		TRIM(OSFXKF02_CUST_NAME1) AS CUSTOMER_NAME,
		TRIM(OSFXKF02_CUATOMER_ID) AS CUSTOMER_ID,
		TRIM(COALESCE(NULLIF(TRIM(OSFXKF02_CPTY_COUNTRY_RISK), ''), OSFXKF02_CPTY_COUNTRY)) AS COUNTRY_COD,
		TRIM(OSFXKF02_OBJECT_CCY) AS CURENCY_COD,
		OSFXKF02_OBJECT_AMT AS TRAN_AMOUNT,
		OSFXKF02_OBJECT_AMT AS LIMIT,
		TRIM(OSFXKF02_OBJECT_CCY) AS LIMIT_COD,
		OSFXKF02_VALUE_DATE0 AS MATURITY_DATE,
		OSFXKF02_TX_DATE AS AS_OF_DATE,
		'OSFXKF02_MF' AS FIL9,
		'01' AS source,
		'system' AS creator,
		OSFXKF02_VALUE_DATE0 AS LIMIT_MATURITY,
		--TRIM(BUSINS_CODE) AS INDUSTRY,
		--2,
		OSFXKF02_CUR_BOUGHT as CUR_BOUGHT,
		OSFXKF02_CUR_SOLD AS CUR_SOLD,
		@EXT_DATE AS EXT_DATE
	FROM OSFXKF02_MF a
	WHERE OSFXKF02_TX_TYPE = '03' AND
		  TRIM(ISNULL(OSFXKF02_CPTY_COUNTRY_RISK,'')) <> 'TW' AND
			EXISTS (
					SELECT 1
					FROM (
						SELECT OSFXKF02_BRANCH_NO, MAX(OSFXKF02_EXT_DATE) AS MAX_DATE
						FROM OSFXKF02_MF
						WHERE OSFXKF02_EXT_DATE <= @EXT_DATE
						GROUP BY OSFXKF02_BRANCH_NO
					) Latest
					WHERE a.OSFXKF02_BRANCH_NO = Latest.OSFXKF02_BRANCH_NO AND
					      a.OSFXKF02_EXT_DATE = Latest.MAX_DATE
				) and
		  (a.OSFXKF02_VALUE_DATE0 is null or DATEADD(DAY,@BufferDate,a.OSFXKF02_VALUE_DATE0) >= @EXT_DATE)
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
