SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	01OBBS衍伸性商品IRS(OSISKF02_MF) 轉檔，根據分行交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce01_OBBS_By_OSISKF02_MF] @EXT_DATE AS DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE,  FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY, PRODUCT_CODE,EXT_DATE)
		SELECT
			TRIM(OSISKF02_BRANCH_NO) AS BRANCH_NO,
			'077' AS DIVISION_NO,
			'07' AS PRODUCT_TYPE,
			TRIM(OSISKF02_TRAN_NO) AS TRAN_NO,
			'018' AS BUSINESS_UNIT,
			OSISKF02_TRADE_DATE AS TX_DATE,
			TRIM(OSISKF02_CUST_NAME1) AS CUSTOMER_NAME,
			TRIM(OSISKF02_CUATOMER_ID) AS CUSTOMER_ID,
			TRIM(OSISKF02_CPTY_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(OSISKF02_IN_CCY) AS CURENCY_COD,
			OSISKF02_risk_amt AS TRAN_AMOUNT,
			OSISKF02_risk_amt AS LIMIT,
			TRIM(OSISKF02_IN_CCY) AS LIMIT_COD,
			OSISKF02_MATURITY AS MATURITY_DATE,
			OSISKF02_TX_DATE AS AS_OF_DATE,
			'OSISKF02_MF' AS FIL9,
			'01' AS source,
			'system' AS creator,
			OSISKF02_MATURITY AS LIMIT_MATURITY,
			--TRIM(BUSINS_CODE) AS INDUSTRY,
			--2,
			'IRS' AS PRODUCT_CODE,
			@EXT_DATE AS EXT_DATE
		FROM OSISKF02_MF a
		WHERE
			TRIM(OSISKF02_CPTY_COUNTRY_RISK) <> 'TW' AND
			 -- 檢查是否為最新資料
			EXISTS (
				SELECT 1
				FROM (
					SELECT OSISKF02_BRANCH_NO, MAX(OSISKF02_EXT_DATE) AS MAX_DATE
					FROM OSISKF02_MF
					WHERE OSISKF02_EXT_DATE <= @EXT_DATE
					GROUP BY OSISKF02_BRANCH_NO
				) Latest
				WHERE a.OSISKF02_BRANCH_NO = Latest.OSISKF02_BRANCH_NO AND
					a.OSISKF02_EXT_DATE = Latest.MAX_DATE
			) and  (a.OSISKF02_MATURITY is null or DATEADD(DAY,@BufferDate,a.OSISKF02_MATURITY) >= @EXT_DATE)
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
