SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	01OOBS 海外拆款與存同業務(OSMMKF02_MF) 轉檔，根據分行交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce01_OBBS_By_OSMMKF02_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		Declare @BufferDate INT = 14;
		--Declare @EXT_DATE Date = '2026-09-01';

		SELECT *,
		CASE TRIM(OSMMKF02_TRAN_TYPE) WHEN '1' THEN '09' -- 09 拆款業務
		ELSE '04' -- 04 存同
		END PRODUCT_TYPE,
		CASE TRIM(OSMMKF02_TRAN_TYPE) WHEN '1' THEN OSMMKF02_MATURITY_DATE
		ELSE DATEFROMPARTS(YEAR(GETDATE()), 12, 31)
		END LIMIT_MATURITY
		INTO #TEMP
		FROM OSMMKF02_MF a
		cross apply(
			select CASE TRIM(OSMMKF02_TRAN_TYPE) WHEN '1' THEN OSMMKF02_MATURITY_DATE
				ELSE isnull(OSMMKF02_MATURITY_DATE,DATEADD(MONTH, 1, GETDATE()))
				END MATURITY_DATE 	
		) b
		WHERE TRIM(OSMMKF02_COUNTRY_RISK) <> 'TW' AND
		(TRIM(OSMMKF02_TRAN_TYPE) = '1' OR -- 1 = 09拆款
		(TRIM(OSMMKF02_TRAN_TYPE) IN ('3','4','5','6') AND -- 3,4,5,6  = 04 存同
			LEFT(TRIM(OSMMKF02_SWIFT_ID), 4) <> 'FCBK')) AND -- FCB 國外分公司(FCBK是 FCB 國內外分行，FCBC 是加州分行，要算入)
		(b.MATURITY_DATE is null or DATEADD(DAY,@BufferDate,b.MATURITY_DATE) >= @EXT_DATE) AND
		EXISTS (
				SELECT 1
				FROM (
					SELECT OSMMKF02_BRANCH_NO, MAX(OSMMKF02_EXT_DATE) AS MAX_DATE
					FROM OSMMKF02_MF
					WHERE OSMMKF02_EXT_DATE <= @EXT_DATE
					GROUP BY OSMMKF02_BRANCH_NO
				) Latest
				WHERE a.OSMMKF02_BRANCH_NO = Latest.OSMMKF02_BRANCH_NO
				AND a.OSMMKF02_EXT_DATE = Latest.MAX_DATE
		)
		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,EXT_DATE)
		SELECT TRIM(OSMMKF02_BRANCH_NO) AS BRANCH_NO,
			'077' AS DIVISION_NO,
			PRODUCT_TYPE AS PRODUCT_TYPE,
			ISNULL(OSMMKF02_TRAN_NO,
				TRIM(OSMMKF02_BRANCH_NO) +
				TRIM(OSMMKF02_TRAN_TYPE) +
				TRIM(OSMMKF02_SWIFT_ID) +
				TRIM(OSMMKF02_CURENCY_COD)) AS TRAN_NO,
			'018' AS BUSINESS_UNIT,
			OSMMKF02_CONTRACT_DATE AS TX_DATE,
			TRIM(OSMMKF02_CUST_NAME1) AS CUSTOMER_NAME,
			TRIM(OSMMKF02_SWIFT_ID) AS CUSTOMER_ID,
			TRIM(OSMMKF02_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(OSMMKF02_CURENCY_COD) AS CURENCY_COD,
			ABS(OSMMKF02_TRAN_AMOUNT) AS TRAN_AMOUNT,
			ABS(OSMMKF02_TRAN_AMOUNT) AS LIMIT,
			TRIM(OSMMKF02_CURENCY_COD) AS LIMIT_COD,
			MATURITY_DATE AS MATURITY_DATE,
			OSMMKF02_TX_DATE AS AS_OF_DATE,
			'OSMMKF02_MF' AS FIL9,
			'01' AS source,
			'system' AS creator,
			LIMIT_MATURITY AS LIMIT_MATURITY,
			--TRIM(BUSINS_CODE) AS INDUSTRY,
			--2,
			@EXT_DATE AS EXT_DATE
		FROM #TEMP
		WHERE
			EXISTS (
			SELECT 1
			FROM #TEMP MF2
			WHERE LEFT(TRIM(MF2.OSMMKF02_SWIFT_ID),4) = LEFT(TRIM(OSMMKF02_SWIFT_ID),4)
			GROUP BY LEFT(TRIM(MF2.OSMMKF02_SWIFT_ID),4),case OSMMKF02_TRAN_TYPE when '1' then 1 else 0 end -- 原本有分 1 = 拆放, 其他存同
			HAVING SUM(ABS(MF2.OSMMKF02_TRAN_AMOUNT)) > 0)
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
