SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	06外貸系統(外幣貸款系統) 額度檔 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce06_By_FM_FMLINE_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;
		Declare @MaxFLMST_EXTDATE DATE = (SELECT MAX(FLMST_EXT_DATE) FROM FL_FLMST_D_MF WHERE FLMST_EXT_DATE <= @EXT_DATE)
		Declare @MaxFMLINE_EXTDATE DATE = (SELECT MAX(FMLINE_EXT_DATE) FROM FM_FMLINE_D_MF WHERE FMLINE_EXT_DATE <= @EXT_DATE)
		Declare @MaxELLSTAPV_EXTDATE DATE = (SELECT MAX(ELLSTAPV_EXT_DATE) FROM EL_ELLSTAPV_D_MF WHERE ELLSTAPV_EXT_DATE <= @EXT_DATE)
		
		INSERT INTO MONITORDATA_STAGE (
		    BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
		    CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
		    PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,INDUSTRY,INDUSTRY_Type,EXT_DATE)
		SELECT  -- 額度檔
			TRIM(LINE.FMLINE_BRANCH) as BRANCH_NO,
			CASE TRIM(FLMST_RECV_BRANCH)
				WHEN '091' THEN '091'
				WHEN '095' THEN '077'
			ELSE '064'
			END as DIVISION_NO,
			'' as PRODUCT_TYPE, ---目前沒辦法分產品別
			'' as TRAN_NO,
			CASE WHEN TRIM(FLMST_RECV_BRANCH) IN ('091','095')
				THEN '018'
			ELSE '011'
			END as BUSINESS_UNIT,
			LINE.FMLINE_APRV_DATE as TX_DATE,
			TRIM(CIF_CUST_NAME) as CUSTOMER_NAME,
			TRIM(FMLINE_CUST_ID) as CUSTOMER_ID,
			ISNULL(CR.CountryCode2,ELL.RISK_NACTION_ID) as COUNTRY_COD,
			'' as CURENCY_COD,
			0 as TRAN_AMOUNT,
			LINE.FMLINE_APRV_NO as PERMIT_NO,
			LINE.FMLINE_LINE_AMT as [LIMIT],
			CUR.CRCY_ENG_NAME as LIMIT_COD,
			LINE.FMLINE_LINE_EXPIRY as MATURITY_DATE,
			LINE.FMLINE_EXT_DATE as AS_OF_DATE, -- 不確定
			CASE LINE.FMLINE_REVOLING_TYPE WHEN '1' THEN 1
				 ELSE 0
				 END as REVOLVE_MK,
			'FM_FMLINE_D_MF' as FIL9,
			'06' as source,
			'system' as creator,
			FMLINE_LINE_EXPIRY as LIMIT_MATURITY,
			'' as INDUSTRY, -- 待確認
			1,
			@EXT_DATE AS DATADATE
		FROM FM_FMLINE_D_MF LINE
		LEFT JOIN CountryMaster CR on TRIM(LINE.FMLINE_FINAL_RISK_CNTY) = CR.CountryCode4
		LEFT JOIN EL_ELLSTAPV_D_MF ELL ON LINE.FMLINE_CUST_ID = ELL.ELLSTAPV_CUST_ID AND 
			LINE.FMLINE_APRV_NO = ELLSTAPV_APRV_NO AND @MaxELLSTAPV_EXTDATE = ELL.ELLSTAPV_EXT_DATE  -- 未來要串這個去看國別
		-- 未來FM_FMLINE_D_MF 會有多一個欄位是 FMLINE_OBBS_APRV_NO 海外核准號碼，是為了RISKLINEO 匯入是對應 APROVE_NO，如果有就不用匯入RISKLINEO
		-- RISKLINED 核准編號對應 FMLINE_APRV_NO，如果有就排除RISKLINED
		LEFT JOIN FL_FLMST_D_MF FLMST ON
			@MaxFLMST_EXTDATE = FLMST_EXT_DATE AND
			LINE.FMLINE_DATE_TYPE = '10' AND
			FLMST_APRV_TYPE_1 = LINE.FMLINE_LINE_TYPE AND
			FLMST_CUST_ID = LINE.FMLINE_CUST_ID AND
			FLMST_RECV_BRANCH = LINE.FMLINE_BRANCH AND
			FLMST_APRV_NO_1 = LINE.FMLINE_APRV_NO
		LEFT JOIN DAILY_CIF_TMP CIF ON REPLACE(LINE.FMLINE_CUST_ID,' ','') = RTRIM(CIF.CIF_ID_NO) + CIF.CIF_ID_SER_NO
		LEFT JOIN MIS_CRCY_REF CUR ON TRIM(FMLINE_LINE_CURENCY) = TRIM(CUR.CRCY_CODE)
		WHERE FLMST.FLMST_ACNT_BRANCH IS NULL AND LINE.FMLINE_EXT_DATE = @MaxFMLINE_EXTDATE and 
			  ISNULL(CR.CountryCode2,ELL.RISK_NACTION_ID) not in ('TW','') and
			  (FMLINE_LINE_EXPIRY is null or DATEADD(DAY,@BufferDate,CONVERT(DATE,FMLINE_LINE_EXPIRY,112)) >= @EXT_DATE)
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO



