SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09ARS_SUKMST_D_MF IRS衍伸性商品之資料擷取 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKMST_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE,  FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY, PRODUCT_CODE,EXT_DATE)
		SELECT
			trim(SUKMST_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKMST_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKMST_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE, -- 衍生性金融商品
			trim(SUKMST_TRAN_NO) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKMST_TRADE_DATE AS TX_DATE,
			trim(SUKMST_CUST_NAME2) AS CUSTOMER_NAME,
			trim(SUKMST_CUSTOMER_ID) AS CUSTOMER_ID,
			trim(SUKMST_CPTY_COUNTRY_RISK)	AS COUNTRY_COD,
			'USD' AS CURENCY_COD,
			SUKMST_RISK_AMT As TRAN_AMOUNT,
			SUKMST_RISK_AMT AS LIMIT,
			'USD' AS LIMIT_COD,
			SUKMST_MATURITY	AS MATURITY_DATE,
			SUKMST_EXT_DATE AS AS_OF_DATE,
			'ARS_SUKMST_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKMST_MATURITY as LIMIT_MATURITY,
			--TRIM(SUKMST_CPTY_BUSINESS) AS INDUSTRY,
			--1,
			'IRS' AS PRODUCT_CODE,
			@EXT_DATE AS EXT_DATE
		FROM ARS_SUKMST_D_MF MF
		WHERE
			SUKMST_EXT_DATE = (SELECT MAX(SUKMST_EXT_DATE) FROM ARS_SUKMST_D_MF WHERE SUKMST_EXT_DATE <= @EXT_DATE) AND
			SUKMST_BUY_SELL ='1' AND
			ISNULL(SUKMST_DEPOSIT_LINK,'') NOT IN('SPD','DCD') AND
			SUKMST_ESTIMATE_FX <> 0 AND -- 因為SUMMIT來的資料有時會給0，計算會錯(不可以除以0)，要排除
			SUKMST_CPTY_COUNTRY_RISK <> 'TW' AND
			(SUKMST_MATURITY is null or DATEADD(DAY,@BufferDate,SUKMST_MATURITY) >= @EXT_DATE)

	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
