SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKNBD1債券投資之資料擷取 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKNBD1_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		
		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,EXT_DATE)
		SELECT
			TRIM(SUKBD1_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKBD1_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKBD1_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'08' AS PRODUCT_TYPE,
			TRIM(SUKBD1_TRAN_NO) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKBD1_TX_DATE AS TX_DATE,
			TRIM(SUKBD1_CUST_NAME1) AS CUSTOMER_NAME,
			TRIM(SUKBD1_SWIFT_ID) AS CUSTOMER_ID,
			ISNULL(NULLIF(SUKBD1_ISSUER_COUNTRY,''), TRIM(SUKBD1_GU_LOG_CTY)) AS COUNTRY_COD,
			TRIM(SUKBD1_CURENCY_COD) AS CURENCY_COD,
			CASE UPPER(TRIM(SUKBD1_BUY_SELL)) WHEN 'B' THEN SUKBD1_BALANCE_AMT
											  WHEN 'S' THEN SUKBD1_BALANCE_AMT * -1
			END As TRAN_AMOUNT,
			SUKBD1_LINE_PERMIT_NO AS PERMIT_NO,
			CASE UPPER(TRIM(SUKBD1_BUY_SELL)) WHEN 'B' THEN SUKBD1_BALANCE_AMT
											  WHEN 'S' THEN SUKBD1_BALANCE_AMT * -1
			END AS LIMIT,
			TRIM(SUKBD1_CURENCY_COD) AS LIMIT_COD,
			SUKBD1_MATURITY_DATE AS MATURITY_DATE,
			SUKBD1_EXT_DATE AS AS_OF_DATE,
			0 AS REVOLVE_MK,
			'ARS_SUKNBD1_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKBD1_MATURITY_DATE as LIMIT_MATURITY,
			--TRIM(SUKBD1_ISSUER_BUSINESS) AS INDUSTRY,
			--1,
			@EXT_DATE AS EXT_DATE
		FROM ARS_SUKNBD1_D_MF
		WHERE SUKBD1_EXT_DATE = (SELECT MAX(SUKBD1_EXT_DATE) FROM ARS_SUKNBD1_D_MF WHERE SUKBD1_EXT_DATE <= @EXT_DATE) AND
			(SUKBD1_MATURITY_DATE is null or DATEADD(DAY,@BufferDate,SUKBD1_MATURITY_DATE) >= @EXT_DATE) AND
			EXISTS (
				SELECT 1
				FROM ARS_SUKNBD1_D_MF MF2
				WHERE MF2.SUKBD1_EXT_DATE = ARS_SUKNBD1_D_MF.SUKBD1_EXT_DATE AND
					  MF2.SUKBD1_CUST_NAME1 = ARS_SUKNBD1_D_MF.SUKBD1_CUST_NAME1 AND
					  ISNULL(NULLIF(MF2.SUKBD1_ISSUER_COUNTRY,''), TRIM(MF2.SUKBD1_GU_LOG_CTY)) <> 'TW'
				GROUP BY MF2.SUKBD1_CUST_NAME1
				HAVING SUM( CASE UPPER(TRIM(MF2.SUKBD1_BUY_SELL)) WHEN 'B' THEN MF2.SUKBD1_BALANCE_AMT
																  WHEN 'S' THEN MF2.SUKBD1_BALANCE_AMT * -1
							END) > 0
			) AND
			ISNULL(NULLIF(SUKBD1_ISSUER_COUNTRY,''), TRIM(SUKBD1_GU_LOG_CTY))  <> 'TW' AND
			NOT(SUKBD1_MATURITY_DATE = SUKBD1_EXT_DATE AND
				SUKBD1_CURENCY_COD = 'TWD' AND
				SUKBD1_SECURITY_TYPE = 'BILL' AND
				SUKBD1_SEC_SUB_TYPE ='CP2');
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
