SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKNFO 衍生性商品(外匯選擇權) 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKNFO_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		-- 衍生性金融商品資料

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,CUR_BOUGHT,CUR_SOLD,EXT_DATE)
		SELECT
			TRIM(SUKFO_ACC_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKFO_ACC_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKFO_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE,                                   -- 衍生性金融商品
			TRIM(SUKFO_TRADE_ID) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKFO_TRADE_DATE AS TX_DATE,
			TRIM(SUKFO_CPTY_NAME) AS CUSTOMER_NAME,
			TRIM(SUKFO_BANK_SWIFT_ID) AS CUSTOMER_ID,
			TRIM(SUKFO_CPTY_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(SUKFO_OBJECT_CCY) AS CURENCY_COD,
			SUKFO_OBJECT_AMT AS TRAN_AMOUNT,
			SUKFO_OBJECT_AMT AS LIMIT,
			TRIM(SUKFO_OBJECT_CCY) AS LIMIT_COD,
			SUKFO_VALUE_DATE0 AS MATURITY_DATE,
			SUKFO_EXT_DATE AS AS_OF_DATE,
			'ARS_SUKNFO_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKFO_VALUE_DATE0 as LIMIT_MATURITY,
			--TRIM(SUKFO_CPTY_BUSINESS) AS INDUSTRY,
			--1,
			TRIM(SUKFO_TRAN_BUY) AS CUR_BOUGHT,
			TRIM(SUKFO_TRAN_SELL) AS CUR_SOLD,
			@EXT_DATE
		FROM ARS_SUKNFO_D_MF
		WHERE
			SUKFO_EXT_DATE = (select max(SUKFO_EXT_DATE) from ARS_SUKNFO_D_MF WHERE SUKFO_EXT_DATE <= @EXT_DATE) AND
			(SUKFO_VALUE_DATE0 is null or DATEADD(DAY,@BufferDate,SUKFO_VALUE_DATE0) >= @EXT_DATE) AND
			SUKFO_TRAN_TYPE = 'B' AND
			SUKFO_CPTY_NAME <> 'DCD_ONLINE' AND
			SUKFO_PRAM_CCY IS NULL AND
			SUKFO_CPTY_COUNTRY_RISK <> 'TW';
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
