SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	09SUKNIRS 衍生性商品(IRS及CCS)之資料擷取 交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce09_By_ARS_SUKNIRS_D_MF] @EXT_DATE DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		--Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
			BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
			CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
			LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, FIL9,
			SOURCE, CREATOR, LIMIT_MATURITY,PRODUCT_CODE,EXT_DATE)
		SELECT
			TRIM(SUKIRS_BRANCH_NO) AS BRANCH_NO,
			CASE WHEN SUKIRS_BRANCH_NO IN('098','095','082') AND UPPER(TRIM(SUKIRS_SUPERVISOR)) = 'STRUCTS_PD'
				THEN '089'
				ELSE '069'
			END AS DIVISION_NO,
			'07' AS PRODUCT_TYPE,
			TRIM(SUKIRS_TRAN_NO) AS TRAN_NO,
			'016' AS BUSINESS_UNIT,
			SUKIRS_TX_DATE AS TX_DATE,
			TRIM(SUKIRS_CUST_NAME1) AS CUSTOMER_NAME,
			TRIM(SUKIRS_CUSTOMER_ID) AS CUSTOMER_ID,
			TRIM(SUKIRS_CPTY_COUNTRY_RISK) AS COUNTRY_COD,
			TRIM(SUKIRS_IN_CCY) AS CURENCY_COD,
			SUKIRS_IN_AMT As TRAN_AMOUNT,
			SUKIRS_IN_AMT AS LIMIT,
			TRIM(SUKIRS_IN_CCY) AS LIMIT_COD,
			SUKIRS_MATURITY AS MATURITY_DATE,
			SUKIRS_EXT_DATE AS AS_OF_DATE,
			'ARS_SUKNIRS_D_MF' as FIL9,
			'09' as source,
			'system' as creator,
			SUKIRS_MATURITY as LIMIT_MATURITY,
			--TRIM(SUKIRS_CPTY_BUSINESS) AS INDUSTRY,
			--1,
			CASE TRIM(SUKIRS_TX_TYPE) WHEN '01' THEN 'QS'
			ELSE 'IRS'
			END AS PRODUCT_CODE,
			@EXT_DATE AS EXT_DATE
		FROM ARS_SUKNIRS_D_MF
		WHERE
			SUKIRS_EXT_DATE = (SELECT MAX(SUKIRS_EXT_DATE) FROM ARS_SUKNIRS_D_MF WHERE SUKIRS_EXT_DATE < @EXT_DATE) AND
			(SUKIRS_MATURITY is null or DATEADD(DAY,@BufferDate,SUKIRS_MATURITY) >= @EXT_DATE) AND
			  ISNULL(SUKIRS_DEPOSIT_LINK,'') NOT IN ('SPD','DCD') AND
			SUKIRS_CPTY_COUNTRY_RISK <> 'TW';
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
