SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		AllenChen
-- Create date: 2025/10/17
-- Description:	01OBBS之海外各業務額度資料(MF_OS_LNSLMSD_D_MF) 轉檔，根據分行交易最大日期

-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_Souce01_OBBS_By_OS_LNSLMSD_D_MF] @EXT_DATE AS DATE
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY

		-- Declare @EXT_DATE Date = '2026-09-01';
		Declare @BufferDate INT = 14;

		INSERT INTO MONITORDATA_STAGE (
		BRANCH_NO, UNIT_NO, PRODUCT_TYPE, TRAN_NO, GROUP_NO, TX_DATE,
		CUSTOMER_NAME, CUSTOMER_ID, COUNTRY_COD, CURENCY_COD, TRAN_AMOUNT,
		PERMIT_NO, LIMIT, LIMIT_COD, MATURITY_DATE, AS_OF_DATE, REVOLVE_MK, FIL9,
		SOURCE, CREATOR, LIMIT_MATURITY,EXT_DATE,TOP_Limit_Amount,TOP_Permit_No,Top_Limit_Cod,TOP_Country_Cod,TOP_Limit_Maturity)
		-- 未動用但仍有效的授信額度
		SELECT
			TRIM(LNSLMSD_BRANCH_NO) AS BRANCH_NO, --分行代號
			'077' AS DIVISION_NO,--處級單位代號
			case Trim(LNSLMSD_LINE_TYPE)
				WHEN 'SL' THEN '01'  -- 聯合貸款
				WHEN 'SG' THEN '12'  -- 保證
			ELSE '02' -- 一般放款
			end AS PRODUCT_TYPE,--產品別
			'' AS TRAN_NO,--交易代號
			'018' AS BUSINESS_UNIT,--事業群代號
			LNSLMSD_BGN_DATE AS TX_DATE,--交易日期
			TRIM(LNSLMSD_CUSTOMER_NAME) AS CUSTOMER_NAME,--客戶姓名
			TRIM(LNSLMSD_CUSTOMER_ID) AS CUSTOMER_ID,--客戶 ID
			TRIM(LNSLMSD_COUNTRY_RISK) AS COUNTRY_COD, --國家別
			TRIM(LNSLMSD_CURRENCY) AS CURENCY_COD,--幣別
			0 AS TRAN_AMOUNT, --交易金額
			TRIM(LNSLMSD_APP_NO) AS PERMIT_NO,--核准編號
			LNSLMSD_APP_AMT AS LIMIT,--核准額度
			TRIM(LNSLMSD_CURRENCY) AS LIMIT_COD,--核准幣別
			LNSLMSD_MATURITY AS MATURITY_DATE, --到期日
			LNSLMSD_DATA_DATE AS AS_OF_DATE, --資料日期
			CASE TRIM(LNSLMSD_CIRCLE)
				WHEN 'Y' THEN 1
			ELSE 0
			END AS REVOLVE_MK,--是否循環
			'OS_LNSLMSD_D_MF' AS FIL9,
			'01' AS source,
			'system' AS creator,
			LNSLMSD_MATURITY AS LIMIT_MATURITY, -- 額度到期日
			--TRIM(a.BUSINS_CODE) AS INDUSTRY,
			--2,--海外
			@EXT_DATE AS DATADATE,
			LNSLMSD_TOP_LINE_APP_AMT,
			LNSLMSD_TOP_LINE_LINE_NO,
			LNSLMSD_TOP_LINE_CCY,
			LNSLMSD_TOP_LINE_CRISK,
			LNSLMSD_TOP_LINE_MATURITY
		FROM OS_LNSLMSD_D_MF a
		Left join OS_LNSMSTD_D_MF b on trim(a.LNSLMSD_BRANCH_NO) = trim(b.LNSMSTD_BRANCH_NO) and
						Trim(a.LNSLMSD_LINE_NO) = trim(b.LNSMSTD_LINE_NO) and
						EXISTS (
							SELECT 1
							FROM (
								SELECT LNSMSTD_BRANCH_NO, MAX(LNSMSTD_EXT_DATE) AS MAX_DATE
								FROM OS_LNSMSTD_D_MF
								WHERE LNSMSTD_EXT_DATE <= @EXT_DATE
								GROUP BY LNSMSTD_BRANCH_NO
							) Latest
							WHERE b.LNSMSTD_BRANCH_NO = Latest.LNSMSTD_BRANCH_NO AND
								  b.LNSMSTD_EXT_DATE = Latest.MAX_DATE
						)
		WHERE EXISTS (
				SELECT 1
				FROM (
					SELECT LNSLMSD_BRANCH_NO, MAX(LNSLMSD_EXT_DATE) AS MAX_DATE
					FROM OS_LNSLMSD_D_MF
					WHERE LNSLMSD_EXT_DATE <= @EXT_DATE
					GROUP BY LNSLMSD_BRANCH_NO
				) Latest
				WHERE a.LNSLMSD_BRANCH_NO = Latest.LNSLMSD_BRANCH_NO AND
						a.LNSLMSD_EXT_DATE = Latest.MAX_DATE
				) AND
				TRIM(LNSLMSD_LINE_TYPE) IN ('SL','LN','SG','IM','OD','BP') AND
				TRIM(ISNULL(LNSLMSD_COUNTRY_RISK,'')) <> 'TW' AND
				LNSLMSD_LINE_NO IS NOT NULL AND 
				(a.LNSLMSD_MATURITY is null or DATEADD(DAY,@BufferDate,a.LNSLMSD_MATURITY) >= @EXT_DATE) and
				b.LNSMSTD_STATUS <> '2' AND
				b.LNSMSTD_LINE_NO IS NULL
				--LOAN:LN;
				--IMPORT:IM;
				--EXPORT:EX;
				--OVERDRAFT:OD;
				--CLEANBILL:CB;
				--GUARANTEE:SG
				--ACCEPTANCE:AC
				--SYNDICATED:SL
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
		THROW;
	END CATCH

END
GO
