SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Allen
-- Create date: 20250916
-- Description:	將指定轉入日期的MonitorData Update 交易金額(美金)核准金額(美金)與交易匯率更新
-- Modify:		新增 TRAN_FXRATE／LIMIT_FXRATE 落地保存實際套用的匯率，供追溯與後續計算使用
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[usp_UpdateMonitorDataFPEXR_RateUSD](@EXT_DATE AS DATE)
AS
BEGIN
	SET NOCOUNT ON;
    BEGIN TRY
		-- 交易金額(美金)與交易匯率更新
		--非柬埔寨幣使用FPEXR_STG(FPEXR_STG是台幣匯率檔，要再除一次美金)
		-- 柬埔寨幣用ACOLRT_STG 匯率檔

		-- Declare @EXT_DATE Date = '2026-09-01';
		UPDATE M
		SET
			TRAN_FXRATE = CASE
				WHEN M.CURENCY_COD = 'KHR' THEN ACO_TRAN.ACOLRT_RATE
				WHEN M.CURENCY_COD = 'TWD' THEN 1 / FPE2_TRAN.FPEXR_RATE
				ELSE FPE_TRAN.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
			END,
			TO_USD_AMT = CASE
				WHEN M.CURENCY_COD = 'KHR' THEN M.TRAN_AMOUNT * ACO_TRAN.ACOLRT_RATE
				WHEN M.CURENCY_COD = 'TWD' THEN M.TRAN_AMOUNT / FPE2_TRAN.FPEXR_RATE
				ELSE M.TRAN_AMOUNT * FPE_TRAN.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
			END,
			LIMIT_FXRATE = CASE
				WHEN M.LIMIT_COD = 'KHR' THEN ACO_TRAN.ACOLRT_RATE
				WHEN M.LIMIT_COD = 'TWD' THEN 1 / FPE2_TRAN.FPEXR_RATE
				WHEN M.LIMIT_COD IS NULL THEN  -- 如果沒有額度幣別，使用交易幣別
					CASE
						WHEN M.CURENCY_COD = 'KHR' THEN ACO_TRAN.ACOLRT_RATE
						ELSE FPE_TRAN.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
					END
				ELSE FPE_LIMIT.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
			END,
			TO_USD_LIMIT = CASE
				WHEN M.LIMIT_COD = 'KHR' THEN M.LIMIT * ACO_TRAN.ACOLRT_RATE
				WHEN M.LIMIT_COD = 'TWD' THEN M.LIMIT / FPE2_TRAN.FPEXR_RATE
				WHEN M.LIMIT_COD IS NULL THEN  -- 如果沒有額度幣別，使用交易幣別
					CASE
						WHEN M.CURENCY_COD = 'KHR' THEN M.LIMIT * ACO_TRAN.ACOLRT_RATE
						ELSE M.LIMIT * FPE_TRAN.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
					END
				ELSE M.LIMIT * FPE_LIMIT.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
			END,
			TOP_Limit_USD_Amount = CASE
				WHEN M.TOP_Limit_Cod = 'KHR' THEN M.TOP_Limit_Amount * ACO_TRAN.ACOLRT_RATE
				WHEN M.TOP_Limit_Cod = 'TWD' THEN M.TOP_Limit_Amount / FPE2_TRAN.FPEXR_RATE
				ELSE M.TOP_Limit_Amount * FPE_TOP_LIMIT.FPEXR_RATE / FPE2_TRAN.FPEXR_RATE
				END
		FROM MONITORDATA_STAGE M
		-- 匯率檔美金
		LEFT JOIN FPEXR_STG FPE2_TRAN ON FPE2_TRAN.FPEXR_CRCY_CODE = '01' 
			AND FPE2_TRAN.FPEXR_DATE =  M.EXT_DATE
		-- 匯率檔2 柬埔寨 對 美金
		LEFT JOIN ACOLRT_STG ACO_TRAN ON ACO_TRAN.ACOLRT_DATE = M.EXT_DATE 
			AND ACO_TRAN.ACOLRT_LOCAL_CURENCY = '01' AND ACOLRT_CURENCY = '91'

		-- 交易幣別代號 JOIN
		LEFT JOIN MIS_CRCY_REF CRCY_TRAN ON CRCY_TRAN.CRCY_ENG_NAME = M.CURENCY_COD
		-- 匯率檔JOIN
		LEFT JOIN FPEXR_STG FPE_TRAN ON CRCY_TRAN.CRCY_CODE = FPE_TRAN.FPEXR_CRCY_CODE
			AND FPE_TRAN.FPEXR_DATE = M.EXT_DATE 

		-- 核准額度幣別相關JOIN（僅當額度幣別存在且不同於交易幣別時）
		LEFT JOIN MIS_CRCY_REF CRCY_LIMIT ON CRCY_LIMIT.CRCY_ENG_NAME = M.LIMIT_COD AND M.LIMIT_COD IS NOT NULL
		LEFT JOIN FPEXR_STG FPE_LIMIT ON CRCY_LIMIT.CRCY_CODE = FPE_LIMIT.FPEXR_CRCY_CODE
			AND FPE_LIMIT.FPEXR_DATE = M.EXT_DATE

		-- 根核准額度幣別相關JOIN（僅當額度幣別存在且不同於交易幣別時）
		LEFT JOIN MIS_CRCY_REF CRCY_TOP_Limit ON CRCY_TOP_Limit.CRCY_ENG_NAME = M.TOP_Limit_Cod AND M.TOP_Limit_Cod IS NOT NULL
		LEFT JOIN FPEXR_STG FPE_TOP_LIMIT ON CRCY_TOP_Limit.CRCY_CODE = FPE_TOP_LIMIT.FPEXR_CRCY_CODE
			AND FPE_TOP_LIMIT.FPEXR_DATE = M.EXT_DATE
		WHERE M.EXT_DATE = @EXT_DATE
	END TRY
    BEGIN CATCH
        DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
        PRINT '發生錯誤: ' + @ErrorMsg;
        THROW;
    END CATCH
END
GO
