SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MailLog_GroupMapping](
	[PK_Id] [int] IDENTITY(1,1) NOT NULL,
	[FK_LogId] [int] NOT NULL,
	[FK_MailGroupId] [int] NOT NULL,
 CONSTRAINT [PK_MailLog_GroupMapping] PRIMARY KEY CLUSTERED
(
	[PK_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[MailLog_GroupMapping]  WITH CHECK ADD  CONSTRAINT [FK_MailLog_GroupMapping_MailLog] FOREIGN KEY([FK_LogId])
REFERENCES [dbo].[MailLog] ([PK_Id])
GO
ALTER TABLE [dbo].[MailLog_GroupMapping] CHECK CONSTRAINT [FK_MailLog_GroupMapping_MailLog]
GO
