SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MailLog_CcCustomMapping](
	[PK_Id] [int] IDENTITY(1,1) NOT NULL,
	[FK_LogId] [int] NOT NULL,
	[CustomMail] [nvarchar](300) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL,
 CONSTRAINT [PK_MailLog_CcCustomMapping] PRIMARY KEY CLUSTERED
(
	[PK_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_TAB]
) ON [NCRMS_TAB]
GO
ALTER TABLE [dbo].[MailLog_CcCustomMapping]  WITH CHECK ADD  CONSTRAINT [FK_MailLog_CcCustomMapping_MailLog] FOREIGN KEY([FK_LogId])
REFERENCES [dbo].[MailLog] ([PK_Id])
GO
ALTER TABLE [dbo].[MailLog_CcCustomMapping] CHECK CONSTRAINT [FK_MailLog_CcCustomMapping_MailLog]
GO
