SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MailLog_CcGroupMapping](
	[PK_Id] [int] IDENTITY(1,1) NOT NULL,
	[FK_LogId] [int] NOT NULL,
	[FK_MailGroupId] [int] NOT NULL,
 CONSTRAINT [PK_Mail_CcGroupMapping] PRIMARY KEY CLUSTERED
(
	[PK_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_TAB]
) ON [NCRMS_TAB]
GO
ALTER TABLE [dbo].[MailLog_CcGroupMapping]  WITH CHECK ADD  CONSTRAINT [FK_Mail_CcGroupMapping_MailGroup] FOREIGN KEY([FK_MailGroupId])
REFERENCES [dbo].[MailGroup] ([PK_Id])
GO
ALTER TABLE [dbo].[MailLog_CcGroupMapping] CHECK CONSTRAINT [FK_Mail_CcGroupMapping_MailGroup]
GO
ALTER TABLE [dbo].[MailLog_CcGroupMapping]  WITH CHECK ADD  CONSTRAINT [FK_Mail_CcGroupMapping_MailLog] FOREIGN KEY([FK_LogId])
REFERENCES [dbo].[MailLog] ([PK_Id])
GO
ALTER TABLE [dbo].[MailLog_CcGroupMapping] CHECK CONSTRAINT [FK_Mail_CcGroupMapping_MailLog]
GO
