SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MIS_CRCY_REF](
	[CRCY_CHN_NAME] [char](10) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	[CRCY_ENG_NAME] [char](3) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL,
	[CRCY_CODE] [char](2) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL,
 CONSTRAINT [PK_MIS_CRCY_REF_1] PRIMARY KEY CLUSTERED
(
	[CRCY_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
SET ANSI_PADDING OFF
GO
