SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[News_Views](
	[PK_Id] [int] IDENTITY(1,1) NOT NULL,
	[FK_NewsId] [int] NOT NULL,
	[Views] [int] NOT NULL,
 CONSTRAINT [PK_News_Views] PRIMARY KEY CLUSTERED
(
	[PK_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[News_Views]  WITH CHECK ADD  CONSTRAINT [FK_News_Views_News] FOREIGN KEY([FK_NewsId])
REFERENCES [dbo].[News] ([PK_Id])
GO
ALTER TABLE [dbo].[News_Views] CHECK CONSTRAINT [FK_News_Views_News]
GO
