SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PostFileMapping](
	[PK_Id] [int] IDENTITY(1,1) NOT NULL,
	[FK_PostId] [int] NOT NULL,
	[FK_FileCenterId] [int] NOT NULL,
	[Create_date] [datetime] NULL,
	[Create_user] [nvarchar](10) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL,
 CONSTRAINT [PK_PostFileMapping] PRIMARY KEY CLUSTERED
(
	[PK_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_TAB]
) ON [NCRMS_TAB]
GO
ALTER TABLE [dbo].[PostFileMapping]  WITH CHECK ADD  CONSTRAINT [FK_PostFileMapping_Post] FOREIGN KEY([FK_PostId])
REFERENCES [dbo].[Post] ([PK_Id])
GO
ALTER TABLE [dbo].[PostFileMapping] CHECK CONSTRAINT [FK_PostFileMapping_Post]
GO
