SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PostCountryType](
	[PK_Id] [int] IDENTITY(1,1) NOT NULL,
	[FK_CountryId] [int] NOT NULL,
	[FK_PostId] [int] NOT NULL,
 CONSTRAINT [PK_PostCountryType] PRIMARY KEY CLUSTERED
(
	[PK_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_TAB]
) ON [NCRMS_TAB]
GO
ALTER TABLE [dbo].[PostCountryType]  WITH CHECK ADD  CONSTRAINT [FK_PostCountryType_CountryMaster] FOREIGN KEY([FK_CountryId])
REFERENCES [dbo].[CountryMaster] ([PK_Id])
GO
ALTER TABLE [dbo].[PostCountryType] CHECK CONSTRAINT [FK_PostCountryType_CountryMaster]
GO
ALTER TABLE [dbo].[PostCountryType]  WITH CHECK ADD  CONSTRAINT [FK_PostCountryType_Post] FOREIGN KEY([FK_PostId])
REFERENCES [dbo].[Post] ([PK_Id])
GO
ALTER TABLE [dbo].[PostCountryType] CHECK CONSTRAINT [FK_PostCountryType_Post]
GO
