SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Post_Views](
	[PK_Id] [int] IDENTITY(1,1) NOT NULL,
	[FK_PostId] [int] NOT NULL,
	[Views] [int] NOT NULL,
 CONSTRAINT [PK_Post_Views] PRIMARY KEY CLUSTERED
(
	[PK_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_TAB]
) ON [NCRMS_TAB]
GO
ALTER TABLE [dbo].[Post_Views]  WITH CHECK ADD  CONSTRAINT [FK_Post_Views_Post] FOREIGN KEY([FK_PostId])
REFERENCES [dbo].[Post] ([PK_Id])
GO
ALTER TABLE [dbo].[Post_Views] CHECK CONSTRAINT [FK_Post_Views_Post]
GO
