SET NOCOUNT ON;
SET XACT_ABORT ON;

-- usp_Souce04_By_LS_LSRSA_D_MF_ACNOD_STG 的第一個分支用
--   WHERE (SELECT MAX(EXT_DATE) FROM LS_LSRSA_D_MF WHERE EXT_DATE <= @EXT_DATE) = EXT_DATE
-- 找最新一批資料，LS_LSRSA_D_MF 目前沒有索引，子查詢跟外層比對都要全表掃描。
-- 第二個分支用的 ACNOD_STG 已經有 IX_ACNOD_STG（ACNOD_EXT_DATE）索引，此處不重複處理。

IF OBJECT_ID(N'[dbo].[LS_LSRSA_D_MF]', N'U') IS NULL
    THROW 59230, N'缺少資料表 dbo.LS_LSRSA_D_MF。', 1;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[LS_LSRSA_D_MF]') AND [name] = N'IX_LS_LSRSA_D_MF_ExtDate')
    THROW 59231, N'dbo.LS_LSRSA_D_MF 已存在索引 IX_LS_LSRSA_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;

BEGIN TRY
    BEGIN TRANSACTION;

    CREATE NONCLUSTERED INDEX [IX_LS_LSRSA_D_MF_ExtDate] ON [dbo].[LS_LSRSA_D_MF]
    (
        [EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
