SET NOCOUNT ON;
SET XACT_ABORT ON;

-- usp_Souce09_By_ARS_* 系列 SP（11 支）都用同一種寫法找「全表最新一批資料」：
--   WHERE <欄位>_EXT_DATE = (SELECT MAX(<欄位>_EXT_DATE) FROM 來源表 WHERE <欄位>_EXT_DATE < @EXT_DATE)
-- 這 11 張 ARS_SUK* 來源表目前完全沒有索引（heap table），子查詢跟外層比對都要各自
-- 全表掃描一次。這裡統一補上資料日期欄位的索引，比照既有 dbo.ACNOD_STG（IX_ACNOD_STG）
-- 的作法，只鍵值不加 INCLUDE，先解決「整張表掃兩遍」這個最大的成本。

IF OBJECT_ID(N'[dbo].[ARS_SUKBD2_D_MF]', N'U') IS NULL
    THROW 59240, N'缺少資料表 dbo.ARS_SUKBD2_D_MF。', 1;
IF OBJECT_ID(N'[dbo].[ARS_SUKBDO_D_MF]', N'U') IS NULL
    THROW 59241, N'缺少資料表 dbo.ARS_SUKBDO_D_MF。', 1;
IF OBJECT_ID(N'[dbo].[ARS_SUKFRA_D_MF]', N'U') IS NULL
    THROW 59242, N'缺少資料表 dbo.ARS_SUKFRA_D_MF。', 1;
IF OBJECT_ID(N'[dbo].[ARS_SUKIRO_D_MF]', N'U') IS NULL
    THROW 59243, N'缺少資料表 dbo.ARS_SUKIRO_D_MF。', 1;
IF OBJECT_ID(N'[dbo].[ARS_SUKMST_D_MF]', N'U') IS NULL
    THROW 59244, N'缺少資料表 dbo.ARS_SUKMST_D_MF。', 1;
IF OBJECT_ID(N'[dbo].[ARS_SUKNBD1_D_MF]', N'U') IS NULL
    THROW 59245, N'缺少資料表 dbo.ARS_SUKNBD1_D_MF。', 1;
IF OBJECT_ID(N'[dbo].[ARS_SUKNFO_D_MF]', N'U') IS NULL
    THROW 59246, N'缺少資料表 dbo.ARS_SUKNFO_D_MF。', 1;
IF OBJECT_ID(N'[dbo].[ARS_SUKNFX_D_MF]', N'U') IS NULL
    THROW 59247, N'缺少資料表 dbo.ARS_SUKNFX_D_MF。', 1;
IF OBJECT_ID(N'[dbo].[ARS_SUKNIRS_D_MF]', N'U') IS NULL
    THROW 59248, N'缺少資料表 dbo.ARS_SUKNIRS_D_MF。', 1;
IF OBJECT_ID(N'[dbo].[ARS_SUKSWP_D_MF]', N'U') IS NULL
    THROW 59249, N'缺少資料表 dbo.ARS_SUKSWP_D_MF。', 1;
IF OBJECT_ID(N'[dbo].[ARS_SUKNMM_D_MF]', N'U') IS NULL
    THROW 59250, N'缺少資料表 dbo.ARS_SUKNMM_D_MF。', 1;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[ARS_SUKBD2_D_MF]') AND [name] = N'IX_ARS_SUKBD2_D_MF_ExtDate')
    THROW 59251, N'dbo.ARS_SUKBD2_D_MF 已存在索引 IX_ARS_SUKBD2_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[ARS_SUKBDO_D_MF]') AND [name] = N'IX_ARS_SUKBDO_D_MF_ExtDate')
    THROW 59252, N'dbo.ARS_SUKBDO_D_MF 已存在索引 IX_ARS_SUKBDO_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[ARS_SUKFRA_D_MF]') AND [name] = N'IX_ARS_SUKFRA_D_MF_ExtDate')
    THROW 59253, N'dbo.ARS_SUKFRA_D_MF 已存在索引 IX_ARS_SUKFRA_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[ARS_SUKIRO_D_MF]') AND [name] = N'IX_ARS_SUKIRO_D_MF_ExtDate')
    THROW 59254, N'dbo.ARS_SUKIRO_D_MF 已存在索引 IX_ARS_SUKIRO_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[ARS_SUKMST_D_MF]') AND [name] = N'IX_ARS_SUKMST_D_MF_ExtDate')
    THROW 59255, N'dbo.ARS_SUKMST_D_MF 已存在索引 IX_ARS_SUKMST_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[ARS_SUKNBD1_D_MF]') AND [name] = N'IX_ARS_SUKNBD1_D_MF_ExtDate')
    THROW 59256, N'dbo.ARS_SUKNBD1_D_MF 已存在索引 IX_ARS_SUKNBD1_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[ARS_SUKNFO_D_MF]') AND [name] = N'IX_ARS_SUKNFO_D_MF_ExtDate')
    THROW 59257, N'dbo.ARS_SUKNFO_D_MF 已存在索引 IX_ARS_SUKNFO_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[ARS_SUKNFX_D_MF]') AND [name] = N'IX_ARS_SUKNFX_D_MF_ExtDate')
    THROW 59258, N'dbo.ARS_SUKNFX_D_MF 已存在索引 IX_ARS_SUKNFX_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[ARS_SUKNIRS_D_MF]') AND [name] = N'IX_ARS_SUKNIRS_D_MF_ExtDate')
    THROW 59259, N'dbo.ARS_SUKNIRS_D_MF 已存在索引 IX_ARS_SUKNIRS_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[ARS_SUKSWP_D_MF]') AND [name] = N'IX_ARS_SUKSWP_D_MF_ExtDate')
    THROW 59260, N'dbo.ARS_SUKSWP_D_MF 已存在索引 IX_ARS_SUKSWP_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[ARS_SUKNMM_D_MF]') AND [name] = N'IX_ARS_SUKNMM_D_MF_ExtDate')
    THROW 59261, N'dbo.ARS_SUKNMM_D_MF 已存在索引 IX_ARS_SUKNMM_D_MF_ExtDate，請先確認是否已執行過本腳本。', 1;

BEGIN TRY
    BEGIN TRANSACTION;

    CREATE NONCLUSTERED INDEX [IX_ARS_SUKBD2_D_MF_ExtDate] ON [dbo].[ARS_SUKBD2_D_MF]
    (
        [SUKBD2_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_ARS_SUKBDO_D_MF_ExtDate] ON [dbo].[ARS_SUKBDO_D_MF]
    (
        [SUKBDO_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_ARS_SUKFRA_D_MF_ExtDate] ON [dbo].[ARS_SUKFRA_D_MF]
    (
        [SUKFRA_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_ARS_SUKIRO_D_MF_ExtDate] ON [dbo].[ARS_SUKIRO_D_MF]
    (
        [SUKIRO_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_ARS_SUKMST_D_MF_ExtDate] ON [dbo].[ARS_SUKMST_D_MF]
    (
        [SUKMST_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_ARS_SUKNBD1_D_MF_ExtDate] ON [dbo].[ARS_SUKNBD1_D_MF]
    (
        [SUKBD1_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_ARS_SUKNFO_D_MF_ExtDate] ON [dbo].[ARS_SUKNFO_D_MF]
    (
        [SUKFO_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_ARS_SUKNFX_D_MF_ExtDate] ON [dbo].[ARS_SUKNFX_D_MF]
    (
        [SUKFX_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_ARS_SUKNIRS_D_MF_ExtDate] ON [dbo].[ARS_SUKNIRS_D_MF]
    (
        [SUKIRS_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_ARS_SUKSWP_D_MF_ExtDate] ON [dbo].[ARS_SUKSWP_D_MF]
    (
        [SUKSWP_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_ARS_SUKNMM_D_MF_ExtDate] ON [dbo].[ARS_SUKNMM_D_MF]
    (
        [SUKMM_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
