SET NOCOUNT ON;
SET XACT_ABORT ON;

-- usp_Souce01_OBBS_By_* 系列 SP 都用同一種寫法找「各分行最新一批資料」：
--   SELECT BRANCH_NO, MAX(EXT_DATE) FROM 來源表 WHERE EXT_DATE <= @EXT_DATE GROUP BY BRANCH_NO
-- 再拿分行+最大日期回去比對整張表。這 6 張來源表目前完全沒有索引（heap table），
-- 上述 GROUP BY 跟回頭比對都只能全表掃描，資料量成長後會愈跑愈慢。
-- 這裡統一補上 (分行, 資料日期) 的複合索引，讓 GROUP BY MAX 用 Stream Aggregate、
-- 回頭比對用 Index Seek。
--
-- OS_LNSMSTD_D_MF（海外分行授信業務交易主檔）與 OS_LNSLMSD_D_MF（海外分行額度檔）
-- 除了上述 GROUP BY 邏輯外，兩表互相以 (分行, 額度號碼, 資料日期) 三欄 JOIN／
-- LEFT JOIN 找「額度對不到主檔」的資料，所以索引多補上額度號碼欄位。

IF OBJECT_ID(N'[dbo].[OSBDKF02_MF]', N'U') IS NULL
    THROW 59210, N'缺少資料表 dbo.OSBDKF02_MF。', 1;
IF OBJECT_ID(N'[dbo].[OSFXKF02_MF]', N'U') IS NULL
    THROW 59211, N'缺少資料表 dbo.OSFXKF02_MF。', 1;
IF OBJECT_ID(N'[dbo].[OSISKF02_MF]', N'U') IS NULL
    THROW 59212, N'缺少資料表 dbo.OSISKF02_MF。', 1;
IF OBJECT_ID(N'[dbo].[OSMMKF02_MF]', N'U') IS NULL
    THROW 59213, N'缺少資料表 dbo.OSMMKF02_MF。', 1;
IF OBJECT_ID(N'[dbo].[OS_LNSMSTD_D_MF]', N'U') IS NULL
    THROW 59214, N'缺少資料表 dbo.OS_LNSMSTD_D_MF。', 1;
IF OBJECT_ID(N'[dbo].[OS_LNSLMSD_D_MF]', N'U') IS NULL
    THROW 59215, N'缺少資料表 dbo.OS_LNSLMSD_D_MF。', 1;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[OSBDKF02_MF]') AND [name] = N'IX_OSBDKF02_MF_BranchExtDate')
    THROW 59216, N'dbo.OSBDKF02_MF 已存在索引 IX_OSBDKF02_MF_BranchExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[OSFXKF02_MF]') AND [name] = N'IX_OSFXKF02_MF_BranchExtDate')
    THROW 59217, N'dbo.OSFXKF02_MF 已存在索引 IX_OSFXKF02_MF_BranchExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[OSISKF02_MF]') AND [name] = N'IX_OSISKF02_MF_BranchExtDate')
    THROW 59218, N'dbo.OSISKF02_MF 已存在索引 IX_OSISKF02_MF_BranchExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[OSMMKF02_MF]') AND [name] = N'IX_OSMMKF02_MF_BranchExtDate')
    THROW 59219, N'dbo.OSMMKF02_MF 已存在索引 IX_OSMMKF02_MF_BranchExtDate，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[OS_LNSMSTD_D_MF]') AND [name] = N'IX_OS_LNSMSTD_D_MF_BranchExtDateLine')
    THROW 59220, N'dbo.OS_LNSMSTD_D_MF 已存在索引 IX_OS_LNSMSTD_D_MF_BranchExtDateLine，請先確認是否已執行過本腳本。', 1;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[dbo].[OS_LNSLMSD_D_MF]') AND [name] = N'IX_OS_LNSLMSD_D_MF_BranchExtDateLine')
    THROW 59221, N'dbo.OS_LNSLMSD_D_MF 已存在索引 IX_OS_LNSLMSD_D_MF_BranchExtDateLine，請先確認是否已執行過本腳本。', 1;

BEGIN TRY
    BEGIN TRANSACTION;

    CREATE NONCLUSTERED INDEX [IX_OSBDKF02_MF_BranchExtDate] ON [dbo].[OSBDKF02_MF]
    (
        [OSBDKF02_BRANCH_NO] ASC,
        [OSBDKF02_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_OSFXKF02_MF_BranchExtDate] ON [dbo].[OSFXKF02_MF]
    (
        [OSFXKF02_BRANCH_NO] ASC,
        [OSFXKF02_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_OSISKF02_MF_BranchExtDate] ON [dbo].[OSISKF02_MF]
    (
        [OSISKF02_BRANCH_NO] ASC,
        [OSISKF02_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_OSMMKF02_MF_BranchExtDate] ON [dbo].[OSMMKF02_MF]
    (
        [OSMMKF02_BRANCH_NO] ASC,
        [OSMMKF02_EXT_DATE] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_OS_LNSMSTD_D_MF_BranchExtDateLine] ON [dbo].[OS_LNSMSTD_D_MF]
    (
        [LNSMSTD_BRANCH_NO] ASC,
        [LNSMSTD_EXT_DATE] ASC,
        [LNSMSTD_LINE_NO] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    CREATE NONCLUSTERED INDEX [IX_OS_LNSLMSD_D_MF_BranchExtDateLine] ON [dbo].[OS_LNSLMSD_D_MF]
    (
        [LNSLMSD_BRANCH_NO] ASC,
        [LNSLMSD_EXT_DATE] ASC,
        [LNSLMSD_LINE_NO] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [NCRMS_IDX];

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
